### ISSUE TITLE
Integration error: alexa_media - Integration 'alexa_media' not found.

### ISSUE THREAD

**Issue by yan14** [custom-components/alexa_media_player#1438] opened 2021-11-23 11:12 UTC
**Describe the bug**
Since updating to 3.10.13, I get the error "Integration error: alexa_media - Integration 'alexa_media' not found." in my logs

**To Reproduce**
1. Update to 3.10.13
2. Restart
3. Log Error "Integration error: alexa_media - Integration 'alexa_media' not found.

**System details**
 - Home-assistant (version):  2021.11.5
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.13
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by josepdomotica** [comment] 2021-11-23 11:14
Same here:

Logger: homeassistant.setup
Source: setup.py:178
First occurred: 12:10:38 (1 occurrences)
Last logged: 12:10:38

Setup failed for alexa_media: Integration not found.

**Comment by alandtse** [comment] 2021-11-23 11:20
You shouldn't install 3.10.13 unless you're on 2021.12.x of HA. Please downgrade.

**Comment by ghostsam45** [comment] 2021-11-23 11:25
v3.10.14
Fix
Require 2021.12.0 (994a2fb)

version not available for the moment ;)

**Comment by Stooovie** [comment] 2021-11-23 12:51
> You shouldn't install 3.10.13 unless you're on 2021.12.x of HA. Please downgrade.

downgrade to what?

**Comment by josepdomotica** [comment] 2021-11-23 13:01
> Same here:
> 
> Logger: homeassistant.setup Source: setup.py:178 First occurred: 12:10:38 (1 occurrences) Last logged: 12:10:38
> 
> Setup failed for alexa_media: Integration not found.

I'm downgrade to v3.10.12 and now works fine (remove from integrations, reboot and reinstall from v3.10.12; then +add Amazon account again)

**Comment by hareeshmu** [comment] 2021-11-23 14:15
Latest version 3.10.14 gives this error while adding the integration:

`2021-11-23 19:40:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 972, in _find_and_load_unlocked
  File "", line 228, in _call_with_frames_removed
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 680, in _load_unlocked
  File "", line 850, in exec_module
  File "", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in 
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in 
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in 
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in 
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 36, in 
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in 
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 29, in 
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 732, in 
    def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
AttributeError: module 'async_timeout' has no attribute 'Timeout'`

**Comment by alandtse** [comment] 2021-11-23 20:29
Dupe of #1434

**Closed** 2021-11-23 20:30 UTC
