### ISSUE TITLE
Error since 107.x

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#615] opened 2020-03-29 07:16 UTC
**Describe the bug**
Since the update some yaml beaviours changed.
One of them is this error I receive after each execution.
Before, everything worked fine

**To Reproduce**
````
- id: '20046'
  alias: Set Volume level
  trigger:
   - platform: time
     at: '04:30'
   - platform: time
     at: '16:00'
  condition:
  action:
   - service: media_player.volume_set
     data_template:
        entity_id: media_player.wohnzimmer
        volume_level: 0.4
   - service: media_player.volume_set
     data_template:
        entity_id: media_player.kuche
        volume_level: 0.3
   - service: media_player.volume_set
     data_template:
        entity_id: media_player.schlafzimmer
        volume_level: 0.6
   - service: media_player.volume_set
     data_template:
        entity_id: media_player.office
        volume_level: 0.3
   - service: media_player.volume_set
     data_template:
        entity_id: media_player.fitnessraum
        volume_level: 0.4
**Expected behavior**
A clear and concise description of what you expected to happen.
````
**System details**
 - Home-assistant (version): 107.7
 - Hassio (Yes/No): Yes
 - alexa_media : v2.5.8
 - alexapy (version from `pip show alexapy` or HA startup): the verion which comes with 107.7 or v2.5.8

**Logs**
````
Set Volume level: Error executing script. Unexpected error for call_service at pos 2: Too Many Requests
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 138, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 233, in _async_call_service_step
    context=self._context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 882, in async_set_volume_level
    await self.alexa_api.set_volume(volume)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 589, in set_volume
    await self.send_sequence("Alexa.DeviceControls.Volume", value=volume * 100)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 296, in send_sequence
    await self.run_behavior(node_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 247, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 118, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 111, in _request
    raise AlexapyTooManyRequestsError(response.reason)
alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests
Erfolgreich gespeichert
````

**Additional context**

**Comment by Pirol62** [comment] 2020-03-29 07:28
The issue might be solved by adding delays between the service call. 
I did it and the first manual trigger of this automation produced no log entries.
But the situation indicates from my perspective, that there might be a general performance issue.

**Comment by alandtse** [comment] 2020-03-29 10:06
Duplicate of #612.  Please comment there.

**Closed by alandtse** 2020-03-29 10:06 UTC
