### ISSUE TITLE
Unable to login in 2.8.0 after cookie expires

### ISSUE THREAD

**Issue by ThisBytes5** [custom-components/alexa_media_player#733] opened 2020-05-19 12:20 UTC
**After upgrading to 2.8.0 I received a notification:**
Configurator
Click button to configure Alexa Media Player - Begin - wayne.com

**Clicking configure brings up this window:**
Alexa Media Player - Begin - AmazonEmailAddress
Please hit confirm to begin login attempt.

**Clicking Confirm**
This causes a second duplicate notification to show up, then disappear and one of the notifications stick around.

**What I've done to try and fix it:**
1) rolled back to 2.7.5 
        same notifications and issues above
2) uninstalled the component, rebooted, re-installed 2.80, went through init set up
        Given error email address already registered
3) Deleted the token for my account from storage, rebooted, tried to re-register
        User/pass screen would go away and come back, no error
4) rolled back to 2.7.5
     This appears to fix the issue, but only because I deleted my token in step 3

Home Assistant 0.109.6
HASSIO: Yes
Alexa_media: __version__ = "2.8.0"
alexapy: not sure how to get this

I attached the logs for step 3 & 4.
EDIT: Logs downloaded so removed.

**Comment by tiagofreire-pt** [comment] 2020-05-19 14:44
I'm also having a similar issue, as the configuration has broken and after re-installing it I can't no longer login. As it stalls after filling the credentials and hit "login".

The issue is not present on 2.7.5.

**Comment by alandtse** [comment] 2020-05-19 15:28
@ThisBytes5 Thanks. I assume you scrubbed your email address in the logs as it's not an actual email address in the logs. However, I did see a password in the logs so I removed the logs from your post. Please note that it may have been spidered so you may want to change your password to be safe.

Your logs are saying you're logging in with version 2.8.0. Can you confirm which version you're actually on? I'm not seeing anything particularly with the initial login for steps 1 and 2 in the logs.

@tiagofreire-pt I'd need to see the logs for when it's breaking to help you.

**Comment by Photo64** [comment] 2020-05-19 17:26
I am also receiving this same error and message after upgrading to 2.8

**Comment by ohadbenita** [comment] 2020-05-20 04:33
Happens to me as well.

**Comment by acelauwc** [comment] 2020-05-20 04:34
Happens to me as well.

**Comment by ohadbenita** [comment] 2020-05-20 05:12
> **After upgrading to 2.8.0 I received a notification:**
> Configurator
> Click button to configure Alexa Media Player - Begin - wayne.com
> 
> **Clicking configure brings up this window:**
> Alexa Media Player - Begin - AmazonEmailAddress
> Please hit confirm to begin login attempt.
> 
> **Clicking Confirm**
> This causes a second duplicate notification to show up, then disappear and one of the notifications stick around.
> 
> **What I've done to try and fix it:**
> 
> 1. rolled back to 2.7.5
>    same notifications and issues above
> 2. uninstalled the component, rebooted, re-installed 2.80, went through init set up
>    Given error email address already registered
> 3. Deleted the token for my account from storage, rebooted, tried to re-register
>    User/pass screen would go away and come back, no error
> 4. rolled back to 2.7.5
>    This appears to fix the issue, but only because I deleted my token in step 3
> 
> Home Assistant 0.109.6
> HASSIO: Yes
> Alexa_media: **version** = "2.8.0"
> alexapy: not sure how to get this
> 
> I attached the logs for step 3 & 4.
> EDIT: Logs downloaded so removed.

Were you able to rollback ? if so - what's the procedure you followed to get things back to work ?

**Comment by ThisBytes5** [comment] 2020-05-20 11:54
> Your logs are saying you're logging in with version 2.8.0. Can you confirm which version you're actually on? I'm not seeing anything particularly with the initial login for steps 1 and 2 in the logs.

The logs are from my attempt to login with 2.8.0 after deleting my /config/.storage/alexa_media.wayne.com.pickle folder.

I'm asked for the user/pass then click the submit/ok/confirm (sorry don't remember button name) and it blinks, then comes back up. 

To get things to fully work I rolled back to 2.7.5 after this and it all worked fine, I got the Capticha request filled it out and was back up and running.

**Comment by ThisBytes5** [comment] 2020-05-20 11:58
> Were you able to rollback ? if so - what's the procedure you followed to get things back to work ?

Delete /config/.storage/alexa_media.wayne.com.pickle
Uninstall the intergration
reboot
re-install the intergration
Go to intergrations
add it
go through set up again

I didn't have to make any other changes, all of my automation started working again after this.
Keep in mind the steps above are from memory, and after trying lots of different things so may not be a 100% accurate.

**Comment by danielpervan** [comment] 2020-05-20 14:56
Deleting the token and reinstalling 2.8.0 seems to have fixed the problem for me.

My steps were specifically:

Delete /config/.storage/alexa_media.wayne.com.pickle
Reinstall Alexa Media Player
Reboot
Click on notification and fill out captcha

**Comment by Photo64** [comment] 2020-05-20 15:09
> Deleting the token and reinstalling 2.8.0 seems to have fixed the problem for me.
> 
> My steps were specifically:
> 
> Delete /config/.storage/alexa_media.wayne.com.pickle
> Reinstall Alexa Media Player
> Reboot
> Click on notification and fill out captcha

I followed these steps and mine is now working again thanks @danielpervan

**Comment by ohadbenita** [comment] 2020-05-20 15:49
After removing the token as suggested removal and installation through HACS & the integrations page, it seems to go back to normal, thanks @danielpervan @ThisBytes5

**Comment by alandtse** [comment] 2020-05-20 16:27
> Deleting the token and reinstalling 2.8.0 seems to have fixed the problem for me.

As a note, the reinstall is likely not necessary. The issue is the .pickle file is expired and putting the login system in a weird state.  Deleting it should resolve this.

**Comment by ThisBytes5** [comment] 2020-05-20 17:09
> > leting the token and reinstalling 2.8.0 seems to have fixed the problem for me.
> > My steps were specifically:
> > Delete /config/.storage/alexa_media.wayne.com.pickle
> > Reinstall Alexa Media Player
> > Reboot
> > Click on notification and fill out captcha
> 
> I followed these steps and mine is now working again thanks @danielpervan

**Comment by ThisBytes5** [comment] 2020-05-20 17:12
Sorry hit wrong button, thought I was hitting cancel when replying, not closing the issue.

I have attempted the steps reported by @danielpervan  and I still just get the screen flash when the Captcha is supposed to come up. 

I even went as far as removing everything (HAC install, integration, and pickle file) and rebooted reinstalled 2.8.0 and still don't get the Captcha.

**Comment by ThisBytes5** [comment] 2020-05-20 17:17
Ok, so this is what I just did (and it works)
1) uninstall the HACS component
2) Remove the intergration
3) Delete the pickle file
4) reboot
5) re-install the hacs component (2.8.0)
6) reboot
7) add the integration

at this point I got the captcha and was able to get 2.8.0 working

**Comment by cmille34** [comment] 2020-05-20 17:17
I followed the steps that @danielpervan suggested but it was still just flashing the screen rather than actually providing the next screen with the captcha. I opened a new Chrome browser in incognito mode and went through adding the Alexa integration that way and it worked first try in a new clean browser.  Another thing to try possibly.

**Comment by lowfat32** [comment] 2020-05-20 17:22
> 
> 
> I followed the steps that @danielpervan suggested but it was still just flashing the screen rather than actually providing the next screen with the captcha. I opened a new Chrome browser in incognito mode and went through adding the Alexa integration that way and it worked first try in a new clean browser. Another thing to try possibly.

Unfortunately this didn't work for me either. 

One time out of the dozen or so I've tried, the captcha did show up. After I entered it, it just went back to the initial login screen asking for username / password.

**Comment by genem2** [comment] 2020-05-20 19:48
After following @ThisBytes5 [steps above](https://github.com/custom-components/alexa_media_player/issues/733#issuecomment-631610805), I finally got this working again. However, it took more restarts once I noticed that this component was still showing a red box in the HACS. After another restart, I was finally able to see the Captcha, but only via the HA Notification.

Then, I had to restart again in order to see the next HA notification for my **second** account.  

Under Integrations, clicking the blue button to set it (for either the first or second account) , never got me past the initial email/pwd screen.

**Comment by mackflix** [comment] 2020-05-21 04:27
FWIW ... I don't believe this has anything to do with v2.80 (or any other release for that matter) ... Here's why I say this: I experienced the exact same issue as OP on current version. I then took a cloned SD Card that's been sitting idle in storage for weeks and popped it in the Pi. On boot up I was met with the exact same issue, before touching anything, the config notification was waiting there to be clicked. This SD Card is running v2.5.6 on HA v.107.1

No idea what this means, but it certainly wasn't caused by updating anything, as the cloned SD card was working fine when put in storage and now it's not.

I'm sure minds greater than mine will figure it out from here ;)

**Comment by thejeffreystone** [comment] 2020-05-21 04:49
Ok, I'm good again. I just stood on the shoulder of giants...

Fix Issue by:

1. Deleted Alexa Media Integration from HACS
2. Rebooted and ensured all custom components are gone. 
3. Installed Alexa Media Player Integration v 2.8.0 from HACS
4. Rebooted (Without this I could not get passed the login to get the Captcha despite it appearing as if you could go straight to integrations page)
5. Go to Configuration -> Integrations 
6. Add Alexa Media Player Integration
7. Entered Credentials and hit submit
8. Enter Captcha and hit submit

Verified HA saw the media player devices again. I'll test the TTS in the morning.

**Comment by rkbest13** [comment] 2020-05-21 16:40
Having the same issues will all the alexa_media_player disabled and notification for a configuration that never succeeds. 
https://imgur.com/a/HomU3C3

**Comment by rkbest13** [comment] 2020-05-21 16:49
> Deleting the token and reinstalling 2.8.0 seems to have fixed the problem for me.
> 
> My steps were specifically:
> 
> Delete /config/.storage/alexa_media.wayne.com.pickle
> Reinstall Alexa Media Player
> Reboot
> Click on notification and fill out captcha

This did not work for me!

**Comment by rkbest13** [comment] 2020-05-21 20:08
> Ok, so this is what I just did (and it works)
> 
> 1. uninstall the HACS component
> 2. Remove the integration
> 3. Delete the pickle file
> 4. reboot
> 5. re-install the hacs component (2.8.0)
> 6. reboot
> 7. add the integration
> 
> at this point I got the captcha and was able to get 2.8.0 working

So after reinstalling of HACS, I am not presented with the setup as it was the first time. I added a new github token and HACS appeared on side menu. but inside I only see a list of repositories and front menu. 
Screenshots for reference. https://imgur.com/a/eiUGIvO
What's wrong and how to fix this? Followed steps as new install with additional step of remove the earlier integration item of HACS.

**Comment by rkbest13** [comment] 2020-05-21 20:35
So, I somehow got alexa_media player back. But only device and DND entities populated. All others are greyed out of not available. i.e., Bunch of them ech0_dot_next reminder, everywhere repeat switch, next alarm, next timer FOR EACH device I have. Though I don't need them yet. having broken status bugs me something might not work. 
https://imgur.com/a/8tcfi8B

**Comment by Mohannadshariefhome** [comment] 2020-05-22 01:53
I cant locate the storage file, can someone help please

**Comment by alandtse** [comment] 2020-05-22 07:04
> So after reinstalling of HACS, I am not presented with the setup as it was the first time.

The instruction meant reinstall the component in HACS. You didn't need to reinstall HACS itself. Also this is the wrong forum to discuss HACS issues.

> All others are greyed out of not available. i.e., Bunch of them ech0_dot_next reminder, everywhere repeat switch, next alarm, next timer FOR EACH device I have.

That's the desired HA behavior if a device is not available. The various alarms/switches (e.g., shuffle) only become available if you have something scheduled or you're playing media that supports it.

**Comment by borisfeldman** [comment] 2020-05-22 07:12
No matter what I did (even with most of the steps above) I could **not** get the flow to display the captcha. The initial login pop up would just blink and that was it.

What finally solved it for me was the suggestion of running the flow in Chrome incognito. That worked immediately.

Back in business. Thanks all!

**Comment by rkbest13** [comment] 2020-05-22 13:38
@alandtse The devices re back online an available now after reinstall.

**Comment by stvnmbr1** [comment] 2020-05-22 18:37
i tried all steps above, in the order described, still only blinks.
reinstall, reboot,...
have 2FA, tried normal and with temp password

**Comment by codycodes** [comment] 2020-05-23 00:33
Also having the same persistent notification loop problem as OP but haven't gotten to a resolution yet. I tried reinstalling the custom component several times but have the same issue. Also tried an incognito window. The only things I can think that I haven't done are to reboot the server and to reinstall HACS itself. I probably won't do the latter but I'm sure I'll get around to the former sometime this weekend. I'm hoping a solution comes up soon and it's as simple as an update to the component in HACS! Though I'm not sure if this is something actually wrong with the custom component code or what. Oh the joys of debugging!

**Comment by alandtse** [comment] 2020-05-23 06:50
I've cleaned up the thread a bit. See workaround above.

If you are still having the error, please try replacing your files with the files in the linked PR. 

Please note, I will **need** logs to debug further. 

If you're uncomfortable replacing your files, then you can still help by providing logs but let me know that it's not using the PR version. I am particularly trying to find the "Verification Needed" page html identified at the end of [here](https://github.com/custom-components/alexa_media_player/issues/735#issuecomment-632091319.)

**Comment by poudenes** [comment] 2020-05-23 07:13
> Ok, so this is what I just did (and it works)
> 
> 1. uninstall the component from HACS
> 2. Remove the integration
> 3. Delete the pickle file `/config/.storage/`
> 4. reboot
> 5. re-install the component (2.8.0) in HACS
> 6. reboot
> 7. add the integration
> 
> at this point I got the captcha and was able to get 2.8.0 working
> 
> EDIT: Admin edit to clarify steps.

Did this step, keep loop in the captcha part. After trying many times and fill in the correct captcha every time it did work finally.

**Comment by stvnmbr1** [comment] 2020-05-23 10:00
Working now for me. Updated to latest hassio, redid all workaround steps
and capchta was showing !

Op za 23 mei 2020 09:13 schreef poudenes <notifications@github.com>:

**Comment by grtessman** [comment] 2020-05-23 20:02
> I've cleaned up the thread a bit. See workaround above.
> 
> If you are still having the error, please try replacing your files with the files in the linked PR.
> 
> Please note, I will **need** logs to debug further.
> 
> If you're uncomfortable replacing your files, then you can still help by providing logs but let me know that it's not using the PR version. I am particularly trying to find the "Verification Needed" page html identified at the end of [here](https://github.com/custom-components/alexa_media_player/issues/735#issuecomment-632091319.)

I'd like to do this, Is there a link to download these files somewhere?  I'm not finding it.

**Comment by alandtse** [comment] 2020-05-23 20:21
> I'd like to do this, Is there a link to download these files somewhere? I'm not finding it.

On the right side of the page, search for `Linked pull requests`.

**Comment by grtessman** [comment] 2020-05-24 00:21
> > I'd like to do this, Is there a link to download these files somewhere? I'm not finding it.
> 
> On the right side of the page, search for `Linked pull requests`.

After I click Linked pull requests, then I choose "Files changed" then select "View" file on each individual file and then "Raw" to view the full file and save it?  

I see one of the checks failed:  https://github.com/custom-components/alexa_media_player/pull/744/checks?check_run_id=701545381 and might make them less likely to pull it?

**Comment by grtessman** [comment] 2020-05-24 00:40
OK,  I copied the files over one by one and Installed new integration alexa media player and I got the captcha!  This fix seemed to be the only thing that worked for me.  Nice job and thank you very much @alandtse !

**Comment by alandtse** [comment] 2020-05-24 02:24
Thanks @grtessman . I'll merge it in. The HACS fail is just a cosmetic bug. The deprecated warnings are already addressed in Dev.

**Closed** 2020-05-24 02:25 UTC

**Comment by sheminasalam** [comment] 2020-06-04 05:17
> Ok, so this is what I just did (and it works)
> 
> 1. uninstall the component from HACS
> 2. Remove the integration
> 3. Delete the pickle file `/config/.storage/`
> 4. reboot
> 5. re-install the component (2.8.0) in HACS
> 6. reboot
> 7. add the integration
> 
> at this point I got the captcha and was able to get 2.8.0 working
> 
> EDIT: Admin edit to clarify steps.

this worked for me too
