### ISSUE TITLE
Login / 2FA / captcha error with 2.8.0. Cannot login anymore!

### ISSUE THREAD

**Issue by energywave** [custom-components/alexa_media_player#735] opened 2020-05-21 00:31 UTC
**Describe the bug**
Just updated to 2.8.0. After some reboots I've got a notification to insert captcha for Amazon login. I did it several times. The first nothing happens (no error shown/logged) but the notification still there. From the second time an error is showing in the bottom (log attached). So I'm out of my account, cannot use it anymore.

**To Reproduce**
1. Amazon should request the captcha, frankly I don't know what to do for it. Maybe some wrong password attempt? (I didn't however)
2. Reboot HA
3. A notification will show that request to insert the captcha
4. Insert the correct captcha
5. You'll notice that the notification is still there
6. Reinsert the captcha
7. The error is shown for a second on the bottom and saved in the log file

**Expected behavior**
Correct login, all should work then.

**System details**
 - Home-assistant (version): 0.110.0
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 2.8.0
 - alexapy (version from `pip show alexapy` or HA startup): cannot verify

**Logs**
```
2020-05-21 02:18:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2876995792] local variable 'config_id' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/configurator.py", line 28, in configuration_callback
    setup_platform_callback, hass, config_entry, login, callback_data
  File "/config/custom_components/alexa_media/configurator.py", line 174, in setup_platform_callback
    await test_login_status(hass, config_entry, login, alexa_setup_callback)
  File "/config/custom_components/alexa_media/configurator.py", line 203, in test_login_status
    await hass.async_add_job(request_configuration, hass, config_entry, login)
  File "/config/custom_components/alexa_media/configurator.py", line 143, in request_configuration
    hass.data[DATA_ALEXAMEDIA]["accounts"][email]["configurator"].append(config_id)
UnboundLocalError: local variable 'config_id' referenced before assignment

```

**Additional context**
I tried to install 2.7.5 from HACS, reboot. Same problem. Maybe the problem is in HA 0.110.0?
Please help, I'm out of Alexa :(

**Comment by justinoreilly** [comment] 2020-05-21 00:49
I also have the same issue. I attempted a full uninstall with no success.

**Comment by energywave** [comment] 2020-05-21 12:10
I've tried again today and the problem is even worse: clicking the notification from the web interface this is showing
![image](https://user-images.githubusercontent.com/2051567/82548955-79bdcd80-9b5c-11ea-907f-e8b0165880ef.png)
I'll try to remove the token (I don't know how to do it but I'll investigate) and report here if it works.

**Comment by energywave** [comment] 2020-05-21 13:38
Further trials.
I've removed the .pickle file in the .storage directory, restarted no way.
Removed __pycache__ files in alexa_media directory (don't know it that's important).
So I've tried to remove integration and readd it. There is no way!

I'll show you with screenshots step by step:

1. I insert data (user and password are good, I'm using LastPass and checked with a normal login, they're ok) on the first form.
![image](https://user-images.githubusercontent.com/2051567/82564025-5739ad80-9b78-11ea-9865-7413cdbbcaba.png)
2. Insert captcha
![image](https://user-images.githubusercontent.com/2051567/82564111-805a3e00-9b78-11ea-9c18-45e3351c34fe.png)
3. I'm requested the verify method, 1 or 0 ??? What's this? Seems not documented... I've tried both 0 or 1, same result
![image](https://user-images.githubusercontent.com/2051567/82564215-ac75bf00-9b78-11ea-8322-9fdc422d6873.png)
4. When pressing "send" link on the previous dialog I'm returning to the first one with this error:
![image](https://user-images.githubusercontent.com/2051567/82564263-c3b4ac80-9b78-11ea-97bd-bfb8efca3ca2.png)

Two files are created in the config folder a get and a post html file. I've compared them, they're identical and they looks like this (I can send you privately them, don't know if they contains some data to hide):
![image](https://user-images.githubusercontent.com/2051567/82564331-e3e46b80-9b78-11ea-89c8-01092f822704.png)

So, with the latest update 0.110.x and 2.8.0 alexa is totally broken :( Please help!

**Comment by energywave** [comment] 2020-05-21 14:35
Ok, I managed to login and I'm getting Alexa again working with HA.
I had not enabled 2FA on my Amazon account, but at login an SMS request was made (why?).
So I enabled 2FA on my Amazon account with an authenticator app and only then the login in alexa_meda config flow was successful.
So, there should be something not correctly managed if 2FA is not enabled and an SMS verify is requested.
This has to be addressed as many people could remain stuck like I was.

**Comment by energywave** [comment] 2020-05-21 17:50
Now it seems to work but in the log I've found many of these errors:
```
2020-05-21 18:48:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 150, in async_send_add_or_update_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 211, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id'

```

**Comment by alandtse** [comment] 2020-05-22 07:01
The alexa error is from the official component. Also the error message appears to indicate a network error.

Amazon is the one sending you a verification request. By enabling 2FA, it gives Amazon another path to verify.  If you send me the html files I can take a look to see if it's an issue where we're not processing the page correctly. Of course, if you're past that page now, you may not have it anymore.

**Comment by alandtse** [comment] 2020-05-22 07:02
Also, this is likely a dupe of #733. I'm only keeping it open because of the verification request screen.

**Comment by energywave** [comment] 2020-05-22 10:02
I also thinked that could be a duplicate of #733 but I couldn't see the log there so I'm not sure. Furthermore he resolved by deleting the tickle file and reinstalling 2.8.0 while I could not resolve in that way. That lead me to think there could be something different. Maybe amazon.it instead of .com or the account configured differently, who knows.
About the network error I can exclude at 100% that. Every attempt lead to the "Error connecting, check network and retry" label at the login screen, but that's certainly something like a catch all that write that because my HA is connected via LAN, my connection is fiber and my IP addresses are all well ordered, I don't have connection issues (I'm a programmer, I work with networks).
But every attempt lead to network error...
Yeah, you had correct intuition, as I managed to login with 2FA enabled.... my old html are gone.
But that should not so difficult to reproduce, using an account without 2FA enabled.

**Comment by lbouriez** [comment] 2020-05-22 18:43
I dont see the captcha, the image is not loading. Any idea how to fix it ?

**Comment by alandtse** [comment] 2020-05-22 20:01
@energywave The issue is that Amazon only sometimes sends the verification page. Unless we have an account that is in that state, we can't replicate it. Since you don't have the html file anymore, I'll close this out and pursue this in the other thread.

@lbouriez Click confirm and it should try to reload.

**Closed by alandtse** 2020-05-22 20:01 UTC

**Comment by condemil** [comment] 2020-05-24 15:55
> @energywave The issue is that Amazon only sometimes sends the verification page. Unless we have an account that is in that state, we can't replicate it. Since you don't have the html file anymore, I'll close this out and pursue this in the other thread.
> 
> @lbouriez Click confirm and it should try to reload.

My account is in that state and updating to 2.8.1 didn't resolve the issue that entered captcha is accepted and I see "local variable 'config_id' referenced before assignment" errors. I don't see any html files in the configuration directory, do I need to enable debug somewhere?

**Comment by energywave** [comment] 2020-05-24 17:15
Exactly! You have to enable advanced debug (don't know how it was in english before translation) when you add the account. I don't know if there is (probably so) a YAML parameter to enable that. If you remove and readd the account you can specify the option, you'll find a checkbox for that. You can see it in my screenshots. Maybe those html can help the dev a lot! :)

**Comment by condemil** [comment] 2020-05-24 19:17
Checked the sources and found debug in `.storage/core.config_entries`.

**Comment by alandtse** [comment] 2020-05-24 19:32
@condemil Logs are necessary to figure out the error. You can access the Advanced Debugging option when you add an integration.
