### ISSUE TITLE
Platform alexa_media does not generate unique IDs

### ISSUE THREAD

**Issue by broyuken** [custom-components/alexa_media_player#1356] opened 2021-08-19 16:28 UTC
**Describe the bug**

**To Reproduce**
Upgrade to core-2021.8.8
Install AMP
Look at logs

**System details**
 - Home-assistant (version): core-2021.8.8
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).Yes
 - alexa_media  (version from `const.py` or HA startup): v3.10.8
 - alexapy (version from `pip show alexapy` or HA startup): unknown
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

2021-08-19 12:22:40 ERROR (MainThread) [homeassistant.components.media_player] Platform alexa_media does not generate unique IDs. ID XXXXXXXXXXXXXXXXXXXXXXX already exists - ignoring media_player.master_bathroom_echo

This pops up for most but not all of my alexa devices on HA startup.

**Comment by alandtse** [comment] 2021-08-21 04:25
Do you have more than one instance running or are you running multiple accounts that share devices? You will need to exclude the extra devices from one of the accounts.

**Comment by broyuken** [comment] 2021-08-21 11:11
Nope, 1 instance, 1 account.

**Comment by alandtse** [comment] 2021-08-21 18:02
This happens every restart? Please provide logs for one of the restarts.

**Comment by broyuken** [comment] 2021-08-23 15:46
I just turned on debug, restarted and the errors are gone now, who knows.

**Comment by alandtse** [comment] 2021-09-10 08:07
Closing since this is a random bug.  Reboots normally get rid of it, but as soon as it's reproducible I can take another look.

**Closed by alandtse** 2021-09-10 08:07 UTC
