### ISSUE TITLE
Restarting Home Assistant with Alexa timer configured causes hang (due to "KeyError occurred. Arguments: ('originalDate',)")

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/alexa_media_player#633] opened 2020-04-07 18:43 UTC
**Describe the bug**

If a timer is set up on an Alexa device when Home Assistant is restarted, the alexa_media component will fail to start up followed by a full hang of Home Assistant.

The error appears to be "KeyError occurred. Arguments: ('originalDate',)". I added some additional debug logging and looks like the timer doesn't have the **originalDate** or **originalTime** properties that the component is looking for:

```
{'alarmTime': 0,
 'createdDate': 1586191069120,
 'deviceSerialNumber': '*****************',
 'deviceType': '*************',
 'id': 'A3***cbd',
 'lastOccurrenceTimeInMilli': 0,
 'lastUpdatedDate': 0,
 'notificationIndex': '********-****-****-****-************',
 'recurrenceEligibility': False,
 'remainingTime': 0,
 'sound': {'displayName': 'Simple Timer',
           'id': 'system_alerts_melodic_02',
           'providerId': 'ECHO',
           'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3'},
 'status': 'OFF',
 'triggerTime': 0,
 'type': 'Timer',
 'version': '4'}

```

**To Reproduce**
Create a timer on an Alexa device
Restart Home Assistant

Deleting the timer allows Home Assistant to start up successfully.

**Expected behavior**

Home Assistant starts normally, with the alexa_media component working.

**Screenshots**

**System details**
 - Home-assistant (version): 0.107.7
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.5.11
 - alexapy (version from `pip show alexapy` or HA startup): 1.5.2

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```text
2020-04-07 18:28:45 DEBUG (MainThread) [custom_components.alexa_media] s*************n@b**************k: Found 11 devices, 11 bluetooth
2020-04-07 18:28:45 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: failure caught due to exception: An exception of type KeyError occurred. Arguments:
('originalDate',)
2020-04-07 18:28:45 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: Try: 4/5 after waiting 40 seconds result: False
2020-04-07 18:30:05 ERROR (MainThread) [homeassistant.core] Error doing job: Unclosed client session
```

**Additional context**

**Comment by aneisch** [comment] 2020-04-08 00:15
Same issue, will try to debug if I get a moment..

**Comment by alandtse** [comment] 2020-04-08 00:44
Looks like the API changed since timers didn't use those fields.

**Comment by Infi-St** [comment] 2020-04-08 01:01
I think this is the same issue, my timers stopped working sometime yesterday or today:

2020-04-07 19:29:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 152, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 234, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 921, in ws_handler
    login_obj, no_throttle=True
  File "/config/custom_components/alexa_media/__init__.py", line 469, in update_devices
    await process_notifications(login_obj, raw_notifications)
  File "/config/custom_components/alexa_media/__init__.py", line 607, in process_notifications
    n_date = notification["originalDate"]
KeyError: 'originalDate'

**Comment by alandtse** [comment] 2020-04-08 01:07
Please test.

**Comment by Infi-St** [comment] 2020-04-08 01:12
applied your fix, am now getting this error on startup:
2020-04-07 21:11:20 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 152, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 234, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 922, in ws_handler
    login_obj, no_throttle=True
  File "/config/custom_components/alexa_media/__init__.py", line 469, in update_devices
    await process_notifications(login_obj, raw_notifications)
  File "/config/custom_components/alexa_media/__init__.py", line 602, in process_notifications
    n_dev_id = notification["deviceSerialNumber"]
KeyError: 'deviceSerialNumber'

**Comment by alandtse** [comment] 2020-04-08 01:42
@Infi-St, that is a mandatory field it's complaining about. Can you provide the json file from your [notifications page](https://alexa.amazon.com/api/notifications)? There should be an entry where `deviceSerialNumber` is missing.

**Comment by Infi-St** [comment] 2020-04-08 01:47
{
			"alarmTime": 0,
			"automationId": "amzn1.alexa.automation.283f3bde-88ce-4cac-a7a3-40ce02ab3153",
			"createdDate": 1584203388869,
			"id": "amzn1.alexa.automation.283f3bde-88ce-4cac-a7a3-40ce02ab3153_TMWAutomation",
			"lastOccurrenceTimeInMilli": 0,
			"lastUpdatedDate": 0,
			"notificationIndex": "amzn1.alexa.automation.283f3bde-88ce-4cac-a7a3-40ce02ab3153_TMWAutomation",
			"rRuleData": {},
			"recurrenceEligibility": true,
			"recurringPattern": "P1D",
			"remainingTime": 0,
			"reminderAppLabel": "Severe Weather Alert in Lebanon",
			"reminderLabel": "Severe Weather Alert in Lebanon",
			"reminderSubLabel": "base64datahere",
			"status": "ON",
			"tmwNotificationProperties": {
				"deliveryStyle": "STANDARD",
				"pushEnabled": true
			},
			"triggerTime": 0,
			"type": "TMWNotification",
			"version": "1"
		}

**Comment by alandtse** [comment] 2020-04-08 01:51
Thanks. Any idea what `TMWNotification` is? Do you have any special skills configured with Amazon for weather updates?

**Comment by Infi-St** [comment] 2020-04-08 01:54
Not that i know of.. this is the First time i have seen anything like this. I do have the Amazon Weather skill enabled. Disabling the skill does not remove the notification from that page.

**Comment by alandtse** [comment] 2020-04-08 02:00
It probably doesn't change any issued notifications.  Try the new version.

**Comment by alandtse** [comment] 2020-04-08 02:21
Ok I've reproduced it by turning on severe weather alerts and it's working for me. I'll close this out. Thanks!

**Closed** 2020-04-08 02:22 UTC
Labels: bug

**Comment by Infi-St** [comment] 2020-04-08 02:27
Thanks! Starts up for me now too.  But, all my *.next_timer objects are "unavailable", are yours working in HA?

**Comment by alandtse** [comment] 2020-04-08 03:15
Yes. Is their status "on" in the device json? Please open a new issue if they are on.

**Comment by haplm** [comment] 2020-04-09 15:04
@alandtse - I had the same issue, which I have solved by removing timers, removing Alexa MP integration, removing the pickle, restarting, re-adding Alexa MP.

However, after next restart (to timers set), Alexa is again unavailable.

Updated to 108.1, restarted, still unavailable. Is this something that is expected, and will be fixed once fix for this issues gets released, or is it something new?

**Comment by alandtse** [comment] 2020-04-09 15:07
This was already released.

**Comment by haplm** [comment] 2020-04-09 15:09
Ah, interesting. This is what it is throwing now

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 150, in async_send_add_or_update_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 212, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id'
`

**Comment by alandtse** [comment] 2020-04-09 15:16
That's not this component.

**Comment by haplm** [comment] 2020-04-09 15:19
Yes, I know, I have edited the post that it is thrown when something is trying to call the missing Alexa MP notifier.  I have tried to restart it once again, and now it throws the good old 'originalDate' message again:

`2020-04-09 17:16:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 152, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 234, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 921, in ws_handler
    login_obj, no_throttle=True
  File "/config/custom_components/alexa_media/__init__.py", line 469, in update_devices
    await process_notifications(login_obj, raw_notifications)
  File "/config/custom_components/alexa_media/__init__.py", line 607, in process_notifications
    n_date = notification["originalDate"]
KeyError: 'originalDate'
`

**Comment by alandtse** [comment] 2020-04-09 15:57
You need to install the latest version.

**Comment by haplm** [comment] 2020-04-09 16:37
Is there a newer version than 108.1? Because that's what I have installed just an hour ago.

**Comment by gadgetchnnel** [comment] 2020-04-09 16:40
@haplm You need version 2.5.12 of the alexa_media_player component to fix that error. If you use HACS check for updates there, otherwise download it from [here](https://github.com/custom-components/alexa_media_player/releases/tag/v2.5.12)

**Comment by haplm** [comment] 2020-04-09 16:56
Ah, sorry, I have totally forgot that this is one of the HACS integrations. Will do! Thanks!

**Comment by avico78** [comment] 2020-04-17 18:19
On 108.5 
alexa : v2.5.13 
No timer with Alexa , 
getting this error when restarted executed from HA gui:
```
2020-04-17 21:14:33 DEBUG (MainThread) [aioimaplib.aioimaplib] Sending : b'BAGG8 LOGOUT\r\n'
2020-04-17 21:14:33 ERROR (MainThread) [alexapy.alexawebsocket] WebSocket Error: <class 'aiohttp.streams.EofStream'>
2020-04-17 21:14:33 DEBUG (MainThread) [alexapy.alexawebsocket] WebSocket Connection Closed. <Task finished coro=<WebsocketEchoClient.process_messages() done, defined at /usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py:146> result=None>
2020-04-17 21:14:33 DEBUG (MainThread) [custom_components.alexa_media] a*****8@g*******m: Received websocket error #0 <class 'aiohttp.streams.EofStream'>: type <class 'str'>
2020-04-17 21:14:33 DEBUG (MainThread) [custom_components.alexa_media] a*****8@g*******m: Immediate abort on EoFstream
````
sometime HA refused to start -  same error : 
```
ERROR (MainThread) [alexapy.alexawebsocket] WebSocket Error: <class 'aiohttp.streams.EofStream'>
````

only hard rebooting the docker helps.

**Comment by alandtse** [comment] 2020-04-18 19:16
Please start a new issue. That error results in a reversion to polling (#579) because it can't connect to Websocket. It wouldn't impact the timer at all though so it's something else during startup.
