### ISSUE TITLE
pyotp error with latest updates

### ISSUE THREAD

**Issue by cyablo** [custom-components/alexa_media_player#1366] opened 2021-09-17 06:43 UTC
SInce one of ther last updates, Alexa Media Player fails to load:

> Logger: aiohttp.server
> Source: custom_components/alexa_media/__init__.py:16
> Integration: Alexa Media Player (documentation, issues)
> First occurred: 8:37:53 (1 occurrences)
> Last logged: 8:37:53
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
>     resp = await self._request_handler(request)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
>     return await super().post(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
>     result = await method(view, request, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
>     result = await self._flow_mgr.async_init(
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
>     flow, result = await task
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 710, in async_create_flow
>     integration.get_platform("config_flow")
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 524, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 529, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
>     from alexapy import (
>   File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
>     from .alexaapi import AlexaAPI
>   File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 23, in <module>
>     from .alexalogin import AlexaLogin
>   File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 49, in <module>
>     class AlexaLogin:
>   File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 221, in AlexaLogin
>     def set_totp(self, otp_secret: Text) -> Optional[pyotp.TOTP]:
> AttributeError: module 'pyotp' has no attribute 'TOTP'

I'm on core-2021.9.6 and supervisor-2021.09.0. Uninstalling and reinstalling the component didn't help.

**Comment by alandtse** [comment] 2021-09-18 08:46
Reinstall alexapy or pyotp. HA is downgrading pyotp.

**Comment by cyablo** [comment] 2021-09-18 12:32
Is there a way to do this with HassOS?

**Comment by riddler2608** [comment] 2021-09-22 11:07
I'm having the same issues

**Comment by cyablo** [comment] 2021-09-22 11:12
Try upgrading to core-2021.9.7.

**Comment by riddler2608** [comment] 2021-09-22 11:14
I am running 2021.9.7

**Comment by cyablo** [comment] 2021-09-22 11:17
Strange! For me, the error went away after the lastest update.

**Comment by alandtse** [comment] 2021-10-03 23:23
Again, the root cause of this is HA on update installs an old version of pyotp. If you remove and readd the integration, it should detect this and reinstall a newer version. Otherwise you need to do a `pip install pyotp` within your HA environment. The basic steps are the same as installing [alexapy](https://github.com/custom-components/alexa_media_player/wiki/FAQ#modulenotfounderror-no-module-named-alexapy).

I'll close this since there's not much I can do for you beyond these instructions.

**Closed by alandtse** 2021-10-03 23:23 UTC
