### ISSUE TITLE
Installation fails in HA 2023.8.1

### ISSUE THREAD

**Issue by drizuid** [custom-components/alexa_media_player#1998] opened 2023-08-10 13:45 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After manually installing alexa_media_player, with different attempts both from releases and from master, restarting and clicking on the add integration button, the pop up shows and I get to what I think is the end, but install never completes and gives an error.

**To Reproduce**

After installing Alexa Media Player and restarting, go to 'Settings' -> 'Devices and Services'
Click on 'Add Integration' and choose 'Alexa Media Player'
See error.

**Expected behavior**

Integration would get installed.

**Screenshots**
<img width="447" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/40674481/be2a3a01-1488-49a1-81a3-b26352084f04">
![image](https://github.com/custom-components/alexa_media_player/assets/40674481/98134b48-f9a4-4546-b3d6-29ed858c7954)
<img width="303" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/40674481/a33ca4f5-dcf9-419e-bde2-214e16a0d05c">

**System details**

- Home-assistant (version): 2023.8.1
- alexa_media (version from const.py or HA startup): 4.6.5
- alexapy (version from pip show alexapy or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n): y
- Docker container (latest stable) on debian host
- docker version 24.0.5 on amd64

**Logs**
https://pastebin.com/BL01nn6p
Hopefully i scrubbed enough!!

**Additional context**

Mine was working fine, but my login "expired" I was told to renew the login. Oddly enough with the new layout for HA, I couldn't find a button to "login again," so I removed the integration and then tried to re-add it. That is when I encountered the issues. I believe this is an incompatibility with HA core caused by different versions of cryptography, but unfortunately, during my debugging I failed to save that info and don't recall what I was doing to see an issue. This is very similar, but not exactly to https://github.com/custom-components/alexa_media_player/issues/1967 Initially I had planned to add my info there, but with the HA version, HACS, and the OP reporting they couldn't even start the process, it was different enough for me to open my own issue. It is also possibly a match to https://github.com/custom-components/alexa_media_player/issues/1996, but that OP did not fill out the template properly and I didn't want to associate with it :)
I will also note that while I have a reverse proxy and a publicly accessible instance, i was having weird issues with the mid-setup authentication so I worked around this by overriding the URL to access HA during alexa_media_player setup. This issue did not happen during every attempt, but this provided some consistency to limit the scope of my troubleshooting.
Please excuse the irrelevant proxy logging, I forgot to remove that from when I was debugging the proxy login issues I was seeing, prior to just using the local ip:port rather than the public url.

**Comment by alandtse** [comment] 2023-08-15 04:45
Disable IPv6 and install.

**Comment by alandtse** [comment] 2023-08-15 04:46
Dupe of #1788

**Closed by alandtse** 2023-08-15 04:45 UTC

**Comment by drizuid** [comment] 2023-08-15 13:10
Ill do this just to get it working, but to be clear, it's not 2005, we don't disable an entire ip protocol to work around a bug, we fix the bug :D  
Thank you regardless.

**Comment by alandtse** [comment] 2023-08-15 14:39
Please submit a PR when you fix the code. It's open source.
