### ISSUE TITLE
Alexa says Repeat after me [...]

### ISSUE THREAD

**Issue by eifinger** [custom-components/alexa_media_player#462] opened 2019-11-12 19:51 UTC
**Describe the bug**
Since today the notification functionality misbehaves for me in Germany. When using `type: "tts"` alexa says "Sprich mir nach [...]". Which would translate to "Repeat after me [...]"

I figure this is a change to the Alexa API and nothing can be done about it.

I will change all my automations to use `type: announce`.

**To Reproduce**
 In Homeassistant call service `notify.alexa_media` with the data:

```json
{
"message":"test",
"data":{"type":"tts"},
"target": "media_player.kevins_echo_dot_oben"
}
```

**Expected behavior**
Alexa says "test"

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.98.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.3.4
 - alexapy (version from `pip show alexapy` or HA startup): 1.3.2

**Logs**
N/A

**Additional context**
N/A

**Comment by alandtse** [comment] 2019-11-13 04:56
Can you see if you can get the Alexa app to do a TTS anymore? If so, we may need to see the routine to adjust the API call.

**Comment by eifinger** [comment] 2019-11-13 07:02
TTS as part of a routine works fine.

**Comment by alandtse** [comment] 2019-11-13 07:19
Can you please pull the the TTS parameters from a routine per this [entry](https://github.com/custom-components/alexa_media_player/wiki/Sequence-Discovery)?

**Comment by eifinger** [comment] 2019-11-13 08:09
```json
{"@type":"com.amazon.alexa.behaviors.model.Automation","automationId":"amzn1.alexa.automation.b5af6208-3d8a-4fdd-9e10-fa30cde42834","name":null,"triggers":[{"payload":{"customerId":"<DELETED>","utterance":"gute Nacht","locale":"de-DE","marketplaceId":"<DELETED>"},"id":"amzn1.alexa.trigger.68be0cec-1a63-49c0-89bf-c464d4d4a9cf","type":"CustomUtterance","timeLapse":null,"skillId":""}],"sequence":{"@type":"com.amazon.alexa.behaviors.model.Sequence","sequenceId":"amzn1.alexa.sequence.13fae817-5cbd-4ac8-ac77-a560a048d9b3","startNode":{"@type":"com.amazon.alexa.behaviors.model.SerialNode","name":null,"nodesToExecute":[{"@type":"com.amazon.alexa.behaviors.model.ParallelNode","name":null,"nodesToExecute":[{"@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode","type":"Alexa.SmartHome.Batch","skillId":"amzn1.ask.1p.smarthome","operationPayload":{"target":"<DELETED>","customerId":"<DELETED>","operations":[{"type":"turnOn"}]},"name":null},{"@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode","type":"Alexa.Speak","skillId":"amzn1.ask.1p.saysomething","operationPayload":{"deviceType":"<DELETED>","customerId":"<DELETED>","textToSpeak":"gute Nacht. Schlaf schÃ¶n!","locale":"de-DE","deviceSerialNumber":"<DELETED>"},"name":null}]}]}},"owner":null,"clientAlias":null,"condition":null,"status":"ENABLED","creationTimeEpochMillis":1534228975339,"lastUpdatedTimeEpochMillis":1543183306589}
```

**Comment by gadgetchnnel** [comment] 2019-11-18 18:07
This is actually working fine for me, but the issue sounds a bit like an old issue we had in the UK were saying "Simon Says *phrase*" would, about 1 time out of 4, respond with "I heard *phrase*" rather than just repeating the phrase.
When Routines were initially introduced, the Alexa Says option would act the same way with the phrases being prefixed with "I heard". I sent feedback to Amazon at the time and it was fixed within a few days.

If this issue has returned for some languages, but is not a problem in routines, it's possible that routines are sending a slightly different request. The one difference I can see is that it looks like the one from the routine has `"skillId":"amzn1.ask.1p.saysomething"` while I don't think the API is sending.

**Comment by alandtse** [comment] 2019-12-20 08:41
@eifinger There's a merge pending in [alexapy](https://gitlab.com/keatontaylor/alexapy/merge_requests/91) that adds in the `skillId`. Assuming your on the latest version, can you check if it helps?

**Comment by eifinger** [comment] 2019-12-21 14:58
I'm not at home over the vacation days. I will report back as soon as I can

**Comment by alandtse** [comment] 2020-01-16 06:25
I'll close this, but please reopen if you can reproduce it on 2.5.1.

**Closed by alandtse** 2020-01-16 06:25 UTC

**Comment by eifinger** [comment] 2020-01-20 10:45
I can confirm that the issue was resolved with the newest version. Thank you!
