### ISSUE TITLE
A connection error occured: An exception of type KeyError occurred. Arguments: ('activities',)

### ISSUE THREAD

**Issue by kkellner** [custom-components/alexa_media_player#1120] opened 2021-01-23 01:37 UTC
**Describe the bug**
Everything was working well on v3.4.8.  When I upgraded to v3.5.0 the "next_timer" sensors were not updated when I say "alexa set timer for...".   Looking into the log I found 2 warnings and 1 error.  These warnings and error only show up AFTER I say "alexa set timer for...".  Prior to that, there are no warnings or errors in the logs.

Warning 1:
```
Logger: alexapy.helpers
Source: /usr/local/lib/python3.8/site-packages/alexapy/helpers.py:143
First occurred: 6:26:29 PM (2 occurrences)
Last logged: 6:26:30 PM

alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f27f0b10eb0>, 10), {}): A connection error occured: An exception of type KeyError occurred. Arguments: ('activities',)
```

Warning 2:
```
Logger: alexapy.helpers
Source: /usr/local/lib/python3.8/site-packages/alexapy/helpers.py:189
First occurred: 6:26:29 PM (2 occurrences)
Last logged: 6:26:30 PM

alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f27f0b10eb0>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyConnectionError occurred. Arguments: ()
```

Error 1:
```
Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:597
Integration: Alexa Media Player (documentation, issues)
First occurred: 6:26:30 PM (1 occurrences)
Last logged: 6:26:30 PM

Unexpected error fetching alexa_media data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 1197, in get_activities
    (await response.json(content_type=None))["activities"] if response else None
KeyError: 'activities'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 393, in async_update_data
    await update_last_called(login_obj)
  File "/config/custom_components/alexa_media/helpers.py", line 162, in _catch_login_errors
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 597, in update_last_called
    last_called = await AlexaAPI.get_last_device_serial(login_obj)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 1230, in get_last_device_serial
    response = await AlexaAPI.get_activities(login, items)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 151, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError
```

**To Reproduce**
1. Install v3.5.0 of Alexa integration (I'm using core-2021.1.4 of HA)
2. Look at logs -- everything should be clean.
3. Say "Alexa set timer for 1 minute"
4. Look at log file. The above documented warnings and error occur.

**System details**
 - Home-assistant (version): core-2021.1.4
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): v3.5.0
 - alexapy (version from `pip show alexapy` or HA startup): ?
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Comment by alandtse** [comment] 2021-01-23 01:40
Thanks. Dupe of #1117. I'm testing a fix already and should be in the next release.

**Closed by alandtse** 2021-01-23 01:40 UTC
