### ISSUE TITLE
unable to install alexapy package in HA Core 2022.3.0

### ISSUE THREAD

**Issue by drthanwho** [custom-components/alexa_media_player#1523] opened 2022-02-24 00:14 UTC
**Describe the bug**
The integration breaks completely in 2022.3.0 due to `alexapy` package having conflicting dependencies

**To Reproduce**
1. Update to 2022.3.0 

**System details**
 - Home-assistant (version): 2022.3.0b0
 - Hassio (Yes/No): Yes (HAOS)
 - alexa_media  (version from `const.py` or HA startup): unrelated
 - alexapy (version from `pip show alexapy` or HA startup): unrelated/unable to be installed
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: unrelated

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2022-02-24 01:53:14 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package alexapy==1.25.3: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install alexapy because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-02-24 01:53:19 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package alexapy==1.25.3: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install alexapy because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-02-24 01:53:23 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alexapy==1.25.3: warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/amd64/

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install alexapy because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-02-24 01:53:23 ERROR (MainThread) [homeassistant.setup] Setup failed for alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].
```

**Additional context**

might be related to pip which is currently 
```pip 22.0.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)```

**Comment by balloob** [comment] 2022-02-24 00:44
Just wanted to stop by and say that we're also investigating this on our end. We did update pip and I think that we're hitting https://github.com/pypa/pip/issues/10825

**Comment by emericklaw** [comment] 2022-02-24 00:47
````
➜  ~ pip3 --version
pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
````
````
➜  ~ pip install alexapy==1.25.3
Collecting alexapy==1.25.3
  Using cached AlexaPy-1.25.3-py3-none-any.whl (222 kB)
Collecting backoff<2.0,>=1.10
  Using cached backoff-1.11.1-py2.py3-none-any.whl (13 kB)
Collecting simplejson
  Using cached simplejson-3.17.6.tar.gz (83 kB)
Collecting authcaptureproxy<2.0.0,>=1.1.1
  Using cached authcaptureproxy-1.1.1-py3-none-any.whl (32 kB)
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
Collecting aiofiles<1,>=0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Requirement already satisfied: certifi in /usr/lib/python3.9/site-packages (from alexapy==1.25.3) (2020.12.5)
Collecting pyotp<3.0.0,>=2.4.1
  Using cached pyotp-2.6.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from alexapy==1.25.3) (2.26.0)
Collecting yarl
  Using cached yarl-1.7.2.tar.gz (168 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cryptography<36.0.0,>=35.0.0
  Using cached cryptography-35.0.0.tar.gz (559 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-274_zawd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4'
       cwd: None
  Complete output (89 lines):
  Collecting setuptools>=40.6.0
    Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting cffi>=1.12
    Using cached cffi-1.15.0.tar.gz (484 kB)
  Collecting setuptools-rust>=0.11.4
    Using cached setuptools_rust-1.1.2-py3-none-any.whl (21 kB)
  Collecting pycparser
    Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
  Collecting semantic-version<3,>=2.8.2
    Using cached semantic_version-2.9.0-py2.py3-none-any.whl (15 kB)
  Collecting typing-extensions>=3.7.4.3
    Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
  Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
  Installing collected packages: typing-extensions, setuptools, semantic-version, pycparser, wheel, setuptools-rust, cffi
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a8r4o5w5/cffi_c84d00bf08b04afb9971338638221f22/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a8r4o5w5/cffi_c84d00bf08b04afb9971338638221f22/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wvyf55n1/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-274_zawd/overlay --compile --install-headers /tmp/pip-build-env-274_zawd/overlay/include/python3.9/cffi
           cwd: /tmp/pip-install-a8r4o5w5/cffi_c84d00bf08b04afb9971338638221f22/
      Complete output (65 lines):
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.libera.chat.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/cffi
      copying cffi/lock.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/cparser.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/error.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/recompiler.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/__init__.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/api.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/model.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/verifier.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/commontypes.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/_embedding.h -> build/lib.linux-x86_64-3.9/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.9/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.9/c/_cffi_backend.o
      error: command 'gcc' failed: No such file or directory
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a8r4o5w5/cffi_c84d00bf08b04afb9971338638221f22/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a8r4o5w5/cffi_c84d00bf08b04afb9971338638221f22/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wvyf55n1/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-274_zawd/overlay --compile --install-headers /tmp/pip-build-env-274_zawd/overlay/include/python3.9/cffi Check the logs for full command output.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz#sha256=9933f28f70d0517686bd7de36166dda42094eac49415459d9bdf5e7df3e0086d (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-274_zawd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography<36.0.0,>=35.0.0 (from alexapy)
ERROR: No matching distribution found for cryptography<36.0.0,>=35.0.0
➜  ~
````

**Comment by alandtse** [comment] 2022-02-24 05:36
> Just wanted to stop by and say that we're also investigating this on our end. We did update pip and I think that we're hitting [pypa/pip#10825](https://github.com/pypa/pip/issues/10825)

Thanks @balloob , is there a core issue to track since it appears to be a wheels issue? The only [one](https://github.com/home-assistant/core/issues/66858) I see appears to have been closed.

**Comment by balloob** [comment] 2022-02-24 05:49
Actually reading the error again, I think the doctype is a red herring. That's a warning but not the error.

The error is 

```
ERROR: Cannot install alexapy because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

This has to do with the new pip resolver.

**Comment by balloob** [comment] 2022-02-24 05:53
Looking at the alexapy dependencies. They are pinned to versions that are not compatible with HA has installed.

(using `pipdeptree` CLI)

```
> pipdeptree -rp wrapt 

wrapt==1.13.2
  - aiobotocore==2.1.0 [requires: wrapt>=1.10.10]
  - astroid==2.9.2 [requires: wrapt>=1.11,<1.14]
    - pylint==2.12.1 [requires: astroid>=2.9.0,<2.10]
      - pylint-strict-informational==0.1 [requires: pylint]
  - audio-metadata==0.11.1 [requires: wrapt>=1.0,<2.0]
  - Deprecated==1.2.13 [requires: wrapt>=1.10,<2]
    - jwcrypto==1.0 [requires: deprecated]
      - github3.py==1.2.0 [requires: jwcrypto>=0.5.0]
        - hassrelease==1.0 [requires: github3.py==1.2.0]
      - python-jwt==3.3.1 [requires: jwcrypto>=1.0.0]
        - Pyrebase4==4.5.0 [requires: python-jwt>=2.0.1]
          - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
    - openevsewifi==1.1.0 [requires: Deprecated>=1.2.10,<2.0.0]
  - tbm-utils==2.6.0 [requires: wrapt>=1.0,<2.0]
    - audio-metadata==0.11.1 [requires: tbm-utils>=2.3,<3.0]

> pipdeptree -rp packaging

packaging==21.0
  - axis==44 [requires: packaging]
  - google-api-core==1.31.3 [requires: packaging>=14.3]
    - google-cloud-pubsub==2.9.0 [requires: google-api-core>=1.28.0,<3.0.0dev]
      - google-nest-sdm==1.7.1 [requires: google-cloud-pubsub>=2.1.0]
    - google-cloud-texttospeech==0.4.0 [requires: google-api-core>=1.6.0,<2.0.0dev]
  - openwrt-luci-rpc==1.1.8 [requires: packaging>=19.1]
  - pytest==6.2.5 [requires: packaging]
    - pycountry-convert==0.7.2 [requires: pytest>=3.4.0]
      - sucks==0.9.4 [requires: pycountry-convert>=0.5]
    - pytest-aiohttp==0.3.0 [requires: pytest]
    - pytest-cov==2.12.1 [requires: pytest>=4.6]
      - openevsewifi==1.1.0 [requires: pytest-cov>=2.8.1,<3.0.0]
      - pycountry-convert==0.7.2 [requires: pytest-cov>=2.5.1]
        - sucks==0.9.4 [requires: pycountry-convert>=0.5]
    - pytest-forked==1.3.0 [requires: pytest>=3.10]
      - pytest-xdist==2.4.0 [requires: pytest-forked]
    - pytest-freezegun==0.4.2 [requires: pytest>=3.0.0]
    - pytest-mock==3.6.1 [requires: pytest>=5.0]
      - pycountry-convert==0.7.2 [requires: pytest-mock>=1.6.3]
        - sucks==0.9.4 [requires: pycountry-convert>=0.5]
    - pytest-rerunfailures==10.2 [requires: pytest>=5.3]
      - TravisPy==0.3.5 [requires: pytest-rerunfailures]
    - pytest-socket==0.4.1 [requires: pytest>=3.6.3]
    - pytest-sugar==0.9.4 [requires: pytest>=2.9]
    - pytest-test-groups==1.0.3 [requires: pytest>=2.5]
    - pytest-timeout==2.0.1 [requires: pytest>=5.0.0]
    - pytest-xdist==2.4.0 [requires: pytest>=6.0.0]
    - TravisPy==0.3.5 [requires: pytest]
  - pytest-sugar==0.9.4 [requires: packaging>=14.1]
  - pyunifiprotect==3.2.0 [requires: packaging]
  - Sphinx==4.2.0 [requires: packaging]
    - fiblary3==0.1.7 [requires: Sphinx]
```

**Comment by balloob** [comment] 2022-02-24 05:53
This is on my dev container, packages might be out of date.

**Comment by balloob** [comment] 2022-02-24 05:55
Some background information is that `pip` has implemented a new resolver that is very strict. We're still working on finding alternatives that work with the HA codebase but so far have not had much luck. Ideally we would be able to find a way to override resolutions which is a solution that works great in the JavaScript world.

**Comment by tasi333** [comment] 2022-02-24 21:34
Is there any workaround for this until we get a fix?

**Comment by joselito11** [comment] 2022-02-25 05:28
> Is there any workaround for this until we get a fix?

Few have fixed it with `pip install alexapy==1.25.3` In HA container. But is not working in HAOS

**Comment by alandtse** [comment] 2022-02-25 09:35
> Looking at the alexapy dependencies. They are pinned to versions that are not compatible with HA has installed.

Sorry, why do you say `wrapt` and `packaging` are pinned?  The manifest allows both wrapt and packaging to be `>=`.
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/manifest.json#L10

Regardless, it apparently is `attrs` and `httpx`. But I don't know why pip is trying to install versions that conflict with HA even if I've installed the versions HA wants. It looks like pip is ignoring the HA pins. None of my dependencies pin attrs or httpx to any thing other than a min version. This looks like a pip bug since it's ignoring the homeassistant pin.

While the workaround could be custom components could pin to a version from HA, that makes them locked to specific versions of HA unnecessarily.

See details below.

**Force attrs and httpx to HA versions**
```
root ➜ /workspaces $ pip --version
pip 22.0.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
root ➜ /workspaces $ pip install attrs==21.2.0 httpx==0.21.3
Collecting attrs==21.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting httpx==0.21.3
  Using cached httpx-0.21.3-py3-none-any.whl (83 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/site-packages (from httpx==0.21.3) (2021.10.8)
Requirement already satisfied: httpcore<0.15.0,>=0.14.0 in /usr/local/lib/python3.9/site-packages (from httpx==0.21.3) (0.14.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.9/site-packages (from httpx==0.21.3) (1.2.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.9/site-packages (from httpx==0.21.3) (1.5.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.9/site-packages (from httpx==0.21.3) (2.0.12)
Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.0->httpx==0.21.3) (0.12.0)
Requirement already satisfied: anyio==3.* in /usr/local/lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.0->httpx==0.21.3) (3.5.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.9/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.0->httpx==0.21.3) (3.3)
Installing collected packages: attrs, httpx
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Uninstalling attrs-21.4.0:
      Successfully uninstalled attrs-21.4.0
  Attempting uninstall: httpx
    Found existing installation: httpx 0.22.0
    Uninstalling httpx-0.22.0:
      Successfully uninstalled httpx-0.22.0
Successfully installed attrs-21.2.0 httpx-0.21.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Install alexapy, note that HA pins are overriden**
```
root ➜ /workspaces $ pip install alexapy==1.25.3 --ignore-installed
Collecting alexapy==1.25.3
  Using cached AlexaPy-1.25.3-py3-none-any.whl (222 kB)
Collecting pyotp<3.0.0,>=2.4.1
  Using cached pyotp-2.6.0-py2.py3-none-any.whl (11 kB)
Collecting yarl
  Using cached yarl-1.7.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (321 kB)
Collecting simplejson
  Using cached simplejson-3.17.6-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (130 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting aiofiles<1,>=0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting cryptography<36.0.0,>=35.0.0
  Using cached cryptography-35.0.0-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (3.2 MB)
Collecting certifi
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting bs4
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting authcaptureproxy<2.0.0,>=1.1.1
  Using cached authcaptureproxy-1.1.2-py3-none-any.whl (32 kB)
Collecting backoff<2.0,>=1.10
  Using cached backoff-1.11.1-py2.py3-none-any.whl (13 kB)
Collecting beautifulsoup4<5.0,>=4.9
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting aiohttp<4.0,>=3.7
  Using cached aiohttp-3.8.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.2 MB)
Collecting multidict<6.0,>=5.1
  Using cached multidict-5.2.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (129 kB)
Collecting importlib-metadata>=3.4.0
  Using cached importlib_metadata-4.11.1-py3-none-any.whl (17 kB)
Collecting httpx
  Using cached httpx-0.22.0-py3-none-any.whl (84 kB)
Collecting typer<1.0,>=0.3
  Using cached typer-0.4.0-py3-none-any.whl (27 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (447 kB)
Collecting idna>=2.0
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (156 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.1-py3-none-any.whl (37 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting zipp>=0.5
  Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting click<9.0.0,>=7.1.1
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting httpcore<0.15.0,>=0.14.5
  Using cached httpcore-0.14.7-py3-none-any.whl (68 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting anyio==3.*
  Using cached anyio-3.5.0-py3-none-any.whl (79 kB)
Collecting h11<0.13,>=0.11
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Installing collected packages: rfc3986, pyotp, certifi, zipp, urllib3, soupsieve, sniffio, simplejson, pycparser, multidict, idna, h11, frozenlist, click, charset-normalizer, backoff, attrs, async-timeout, aiofiles, yarl, typer, requests, importlib-metadata, cffi, beautifulsoup4, anyio, aiosignal, httpcore, cryptography, bs4, aiohttp, httpx, authcaptureproxy, alexapy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
homeassistant 2022.4.0.dev0 requires attrs==21.2.0, but you have attrs 21.4.0 which is incompatible.
homeassistant 2022.4.0.dev0 requires httpx==0.21.3, but you have httpx 0.22.0 which is incompatible.
Successfully installed aiofiles-0.8.0 aiohttp-3.8.1 aiosignal-1.2.0 alexapy-1.25.4 anyio-3.5.0 async-timeout-4.0.2 attrs-21.4.0 authcaptureproxy-1.1.2 backoff-1.11.1 beautifulsoup4-4.10.0 bs4-0.0.1 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 click-8.0.4 cryptography-35.0.0 frozenlist-1.3.0 h11-0.12.0 httpcore-0.14.7 httpx-0.22.0 idna-3.3 importlib-metadata-4.11.1 multidict-5.2.0 pycparser-2.21 pyotp-2.6.0 requests-2.27.1 rfc3986-1.5.0 simplejson-3.17.6 sniffio-1.2.0 soupsieve-2.3.1 typer-0.4.0 urllib3-1.26.8 yarl-1.7.2 zipp-3.7.0
```

**pipdeptree on alexapy showing non pinning on attrs or https**
```
(alexapy-PRYeSTMI-py3.9) ➜  alexapy git:(23f9ef4) pipdeptree -rp attrs
attrs==21.4.0
  - aiohttp==3.8.1 [requires: attrs>=17.3.0]
    - aresponses==2.1.5 [requires: aiohttp>=3.1.0,==3.*]
    - authcaptureproxy==1.1.2 [requires: aiohttp>=3.7,<4.0]
    - pytest-aiohttp==1.0.4 [requires: aiohttp>=3.8.1]
  - black==19.10b0 [requires: attrs>=18.1.0]
  - pytest==7.0.1 [requires: attrs>=19.2.0]
    - pytest-aiohttp==1.0.4 [requires: pytest>=6.1.0]
    - pytest-asyncio==0.18.1 [requires: pytest>=6.1.0]
      - aresponses==2.1.5 [requires: pytest-asyncio]
      - pytest-aiohttp==1.0.4 [requires: pytest-asyncio>=0.17.2]
    - pytest-cov==3.0.0 [requires: pytest>=4.6]
(alexapy-PRYeSTMI-py3.9) ➜  alexapy git:(23f9ef4) pipdeptree -rp httpx
httpx==0.22.0
  - authcaptureproxy==1.1.2 [requires: httpx]
```

**Comment by dreimer1986** [comment] 2022-02-25 10:10
> > Is there any workaround for this until we get a fix?
> 
> Few have fixed it with `pip install alexapy==1.25.3` In HA container. So I have HA OS in VM. So had to install Portainer addon, open console in homeassistant container and run the pip command. One more time HA restart and alexa is working.

Not even needed. You can use the SSH & Web Terminal Addon for that. "docker exec -it CONTAINERNAME command_to_run" is your friend. But this is no fix, it's a workaround. There is a bug and this is no solution. That's why I decided against the spoon feeding 1-liner copying way. Everything you need can be found in the Docker MANpage and in here.

**Comment by alandtse** [comment] 2022-02-25 10:35
This should be fixed by https://github.com/alandtse/auth_capture_proxy/pull/20

**Closed by alandtse** 2022-02-25 10:35 UTC

**Comment by regevbr** [comment] 2022-02-25 11:20
Can someone confirm it is fixed now?

**Comment by regevbr** [comment] 2022-02-25 11:50
> Can someone confirm it is fixed now?

I can confirm it is fixed in the latest beta version. Thanks @alandtse for the quick fix :-)
