### ISSUE TITLE
! Not Loaded after updating Home Assistant

### ISSUE THREAD

**Issue by PlinyElderATX** [custom-components/alexa_media_player#1462] opened 2021-12-10 20:55 UTC
I'm suddenly getting !Not Loaded in the integrations list after updating home assistant. I did also update HACS and the integration and restarted but no luck. I am also unable to remove the integration so I can't force a re-configure. I have tried a "redownload" through HACS also to no avail.

**To Reproduce**
1. Simply update Home Assistant to: core-2021.12.0b6, supervisor-2021.12.1

**Expected behavior**
Alexa media player to load or at least be removable

**Screenshots**
![image](https://user-images.githubusercontent.com/55222228/145639189-5df52393-56ba-488b-a090-01724d48c2ed.png)

**System details**
 - Home-assistant (version): core-2021.12.0b6, supervisor-2021.12.1
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): 3.10.12
 - alexapy (version from `pip show alexapy` or HA startup): Can't seem to sort how to see this
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). YES

**Logs**
These two errors in the logs are almost certainly pointing at the problem. I'm just not sure how to sort it out since I can't seem to remove the integration

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:16
Integration: Alexa Media Player (documentation, issues)
First occurred: 3:37:41 PM (1 occurrences)
Last logged: 3:37:41 PM

Setup failed for alexa_media: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/__init__.py:16
Integration: Alexa Media Player (documentation, issues)
First occurred: 3:40:54 PM (1 occurrences)
Last logged: 3:40:54 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 71, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 487, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by woempiej** [comment] 2021-12-11 20:57
![afbeelding](https://user-images.githubusercontent.com/62903344/145691344-2d52e9bb-7e98-4b4f-b412-32156fb0782b.png)

Same errors here, after updating to 2021.12.1

**Comment by aljubori** [comment] 2021-12-11 21:13
same her after updating to 2021.12
Not loaded

**Comment by alandtse** [comment] 2021-12-11 21:49
Dupe of #1446

**Closed by alandtse** 2021-12-11 21:49 UTC

**Comment by woempiej** [comment] 2021-12-11 22:06
I fixed it with re-download the integration (3.10.15) in HACS and restart HA

**Comment by tkernaghan** [comment] 2021-12-12 17:46
After you apply the HA update go into HACS and you should see a pending update for Alexa Media Player, update AMP and restart HA. Afterwards AMP should load properly.
