### ISSUE TITLE
No connection to Home Assistant URL

### ISSUE THREAD

**Issue by glockmane** [custom-components/alexa_media_player#1662] opened 2022-07-10 19:58 UTC
![image](https://user-images.githubusercontent.com/2814025/178160092-6cd41222-896b-4f3a-9524-f6176f7c5f26.png)

![image](https://user-images.githubusercontent.com/2814025/178160127-ef27f084-d6e6-400f-991d-55643813fc68.png)

I think I filled everything correctly.. External URL is working fine, just tested.. I'm not using Home Assistant Cloud, instead configured external access via nginx proxy..

**Comment by cierigabriele** [comment] 2022-07-11 11:19
Hi Me Too in Italy

**Comment by jpreiditsch** [comment] 2022-07-11 19:17
I'm also connected via a nginx proxy with the same error.
Unable to connect to Home Assistant url. Please check the External Url under Configuration -> General

amazon.ca

**Comment by micbr84** [comment] 2022-07-12 05:28
Hi, me too since yesterday after the upgrade to 2022.07.02.

**Comment by david-romero** [comment] 2022-07-15 06:35
Same here! 

Home Assistant 2022.7.4

**Comment by TZombiEd** [comment] 2022-07-17 19:22
I'm getting the same error message.  running core-2022-7.5.  Tried using local url but that doesn't appear to be a working option.  I know both external and local urls are good as I use them often.  To complicate things, I'm not getting anything in the logs so having a difficult time trying to figure out what is wrong.

**Comment by alandtse** [comment] 2022-07-18 23:45
Dupe of #1624 if not others. Solutions have been posted if you search.

**Comment by jvb93** [comment] 2022-07-19 04:49
Forgive my naïveté, but this kinda seems unacceptable imo. A fresh install of this plugin straight up does not work out of the box. Instead we're being asked to comb through pages of comments on old issues to find a workaround ourselves? Is it not in the best interests of the maintainers of this repo to think about the usability of their software? I understand this is the nature of FOSS at times, but this seems particular egregious for a component that a LOT of HA users depend on. 

Take my case, as example. I have a fully up-to-date HA instance (2022.7.5) on a raspberry pi. I also have a brand-new echo dot that I'd like to add for TTS purposes. I installed this repo via HACS, and am immediately faced with the same problem as OP, and no logs to speak of. This seems like a problem to me. Granted, an extremely first world problem, and not something I'm going to lose sleep over, but definitely not something to be dismissed as duplicate, IMO. **Recurring problems in the software are a sign of bad software, not user error.**

**Comment by jvb93** [comment] 2022-07-19 19:50
Exactly what I ended up doing @jpreiditsch

**Comment by alandtse** [comment] 2022-07-20 16:13
> Forgive my naïveté, but this kinda seems unacceptable imo. A fresh install of this plugin straight up does not work out of the box. Instead we're being asked to comb through pages of comments on old issues to find a workaround ourselves? Is it not in the best interests of the maintainers of this repo to think about the usability of their software? I understand this is the nature of FOSS at times, but this seems particular egregious for a component that a LOT of HA users depend on.
>Take my case, as example. I have a fully up-to-date HA instance (2022.7.5) on a raspberry pi. I also have a brand-new echo dot that I'd like to add for TTS purposes. I installed this repo via HACS, and am immediately faced with the same problem as OP, and no logs to speak of. This seems like a problem to me. Granted, an extremely first world problem, and not something I'm going to lose sleep over, but definitely not something to be dismissed as duplicate, IMO. Recurring problems in the software are a sign of bad software, not user error.

I'll respond once since I'm assuming you're being naïve instead of entitled. I have responded multiple times about 1) how to work around the problem, 2) the cause of the issue, and 3) how to get me information to solve it. Those instructions also explain how to enable the logs. To date, no users have offered to help with 3 because all they care about is 1. I'm not sure what you expect me to do in this situation. Most people only care about their problem and stop once it's solved. Seeing how I have been supporting this for multiple years without payment, it's fair to say I've demonstrated that I have gone beyond the vast majority of people.  

On the point of asking users to spend time, I think it's a fair trade. I spent a lot of time writing the component, sharing, and maintaining it. Why should I spend time retyping responses when users don't feel like they have to search. The fact the issues is filled with dupes including yours, is because users don't want to spend the time to search for the existing issue and just create a new one demanding help. Frankly, that is not helpful nor are comments like yours encouraging.

Regardless, the issue is primarily user error because the warning only appears if your HA server running the component cannot connect to the url provided. I've never had that issue, but then again, I understand how to setup HA so it can reach itself on the network. I'd take a PR to make it an optional warning, but given the state of the user base, it'll just change the duplicate issue in that users will get past the warning and then bitch that they can't connect at all because the URL is wrong entirely.

> The downgrade then reauth fix is definitely the most intuitive fix. Way better than fixing the underlying issue. 👎

I never said that was a solution. It's a workaround users have found and fits firmly into option 1. Please check your entitlement. The source code is available. Please submit a fix since you know the solution.

**Closed by alandtse** 2022-07-20 16:13 UTC
Labels: duplicate

**Comment by coli24200** [comment] 2022-07-22 08:19
Thank you ! ...I've installed the "dev" version and an empty check box appears , after the login is made in alexa!   ... problem fixed!
