### ISSUE TITLE
[FR] Ability to disable microphone (red circle)

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#969] opened 2020-10-02 07:00 UTC
**Is your feature request related to a problem? Please describe.**
Would be nice to have the ability to enable/disable the microphone so when you are away nobody can use voice commands.

Thank you for considering

Simone

**Describe the solution you'd like**
A switch like there is one for the do not disturb functionality.

**Describe alternatives you've considered**
None

**Comment by alandtse** [comment] 2020-10-02 07:51
Can it be done in the app? Last I checked it's a hardware switch.

**Comment by chemelli74** [comment] 2020-10-02 10:56
If I got it right, there is an interface to do that task:

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-speaker.html

Simone

**Comment by alandtse** [comment] 2020-10-02 19:01
First, we don't use that API. I've told you that before.

Second, that does not describe anything related to the hardware mute. I assume you can't do this in the app still so will close this as not doable.

**Closed by alandtse** 2020-10-02 19:01 UTC

**Comment by chemelli74** [comment] 2020-10-02 19:30
In the app you can go under devices->echo & Alexa-> echo dot xyz-> communications 

There you find "calls and messages" (on/off), "announces" and "drop in"

I think those are the options you are looking for.

About the API, I know this is not used by your great plugin but was just an info that the requested feature is not only hardware switch but can be software controlled.

Thank you for your attention and work.

Simone

**Comment by alandtse** [comment] 2020-10-02 20:16
None of those are the mute you're talking about. Again show me what you want works in the app and we can try to implement it. Until then, I can't because I'm not Amazon.

**Comment by sgofferj** [comment] 2020-10-07 11:31
@chemelli74 The things you are describing aren't the "Red Ring", I'm afraid. You only get the "Red Ring" when your press the mute button on the device. this button is AFAIK directly connected to the microcontroller and the microcontroller will cut the power to the microphone. That is intentionally and by design a hardware-solution which is not accessible to the API.

See:
https://www.eevblog.com/forum/projects/amazon-echo-is-the-mic-disabled-via-analog-circuit/
https://www.eevblog.com/forum/reviews/teardown-amazon-echo-dot-2/

**Comment by chemelli74** [comment] 2020-10-07 12:42
> @chemelli74 The things you are describing aren't the "Red Ring", I'm afraid.

Yeah you are right.

> You only get the "Red Ring" when your press the mute button on the device. This button is AFAIK directly connected to the microcontroller and the microcontroller will cut the power to the microphone. That is intentionally and by design a hardware-solution which is not accessible to the API.

Seems there is an API to do that, but is not in the set used by this component so it's useless.

Simone
