### ISSUE TITLE
Login in / Re-auth - Unknown Error Occurred

### ISSUE THREAD

**Issue by TheOrion666** [custom-components/alexa_media_player#1737] opened 2022-09-27 23:57 UTC
Issue: 

Unable to login to amazon account. Originally setup and working fine, using SMS 2FA. Time was due to re-auth and issue started. Trying to use Built-In 2FA App key method to no avail. 

Error on the UI is "Unknown Error Occurred". I have removed the Alexa Media player integration, rebooted HA, re-installed the integration and tried:

I have enabled debug log as shown in the wiki, and I am not getting much information to troubleshoot. 

Some info:
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0

Alexa Media player installed via HACS. Alexa Media Player version: 4.1.2

`2022-09-27 19:33:21.342 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2022-09-27 19:33:21.343 DEBUG (MainThread) [custom_components.alexa_media.helpers] c****************n@g*******m: Returning uuid {'uuid': '71a2566c8e5f13600efab5xxxxxxxxxxx', 'index': 0}
2022-09-27 19:33:21.351 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for 2************************************************K3A
2022-09-27 19:33:21.351 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 589838`

Configuration.yaml is with the below (for logging):
`logger:
  default: critical
  logs:
    custom_components.alexa_media: debug
    # for API debugging (verbose and intended for service debugging)
    alexapy: debug
    # for proxy debugging
    authcaptureproxy: debug
`

Nothing shows up on the UI (tried clearing cookies) and 2 other browsers:
![image](https://user-images.githubusercontent.com/57693178/192657700-9d745f99-9daf-4bc5-9095-689086d24cf1.png)

I have tried entering the OTP on amazon's website, and it adds the app on their site, but still fails to auth. 

Please help, unsure how to progress.

**Comment by NicolasRigo** [comment] 2022-10-02 16:30
Hi there,

Same error since updated HA to 2022.9.7

The only difference for me is I do not get any response when clicking to SUBMIT. It simply do nothing...
I guess Amazon changed something in its APIs.

Hope it will be fixed by the plug in owner...

**Comment by dxit** [comment] 2022-10-03 22:08
> 

Same here. I submit but it does nothing. All the fields are fulfilled correctly.
In the logs, I see: `No Home Assistant URL found in config or detected; forcing user form`.

**Comment by mitchoklemen** [comment] 2022-10-04 06:36
same here

**Comment by mehdic** [comment] 2022-10-04 09:48
Same problem here, been happenening for the past 3 weeks. I tried everything, uninstalled, reinstalled, but still no popup coming

**Comment by politician** [comment] 2022-10-07 10:18
After seeing @dxit 's comment, I tried setting up the `external_url` and `internal_url` in my HA `configuration.yaml`, rebooted, retried the integration and it worked.

https://www.home-assistant.io/docs/configuration/basic/

**Comment by dxit** [comment] 2022-10-07 11:33
> After seeing @dxit 's comment, I tried setting up the `external_url` and `internal_url` in my HA `configuration.yaml`, rebooted, retried the integration and it worked.
> 
> https://www.home-assistant.io/docs/configuration/basic/

It works for me too. Thank you @politician

**Comment by mitchoklemen** [comment] 2022-10-07 11:54
It works for me too. Thank you @politician

**Comment by TheOrion666** [comment] 2022-10-09 17:14
Leaving this as it may help, not a final solution but I was going through my nginx proxy internally and decided to enter on the login page of this integration the local ip of my HA and it worked.

**Comment by lk3de** [comment] 2022-11-22 22:13
> Leaving this as it may help, not a final solution but I was going through my nginx proxy internally and decided to enter on the login page of this integration the local ip of my HA and it worked.

I can confirm this: I don't have `internal_url`/`external_url` set via configuration.yaml, but instead configured via the UI (Settings -> System -> Network). HA is living behind an nginx proxy as well. When setting up the integration, the field "URL to access Home Assistant" is populated with the external URL by default, which produced the same "Unknown error occured" for me (and no helpful information in the logs, even with debug logging enabled). Replacing the URL with the internal URL worked instantly and without any issue.

**Comment by alandtse** [comment] 2022-12-02 03:48
Fixed in 4.3.2

**Closed by alandtse** 2022-12-02 03:48 UTC
