### ISSUE TITLE
With the Beta from HA 0.110 following have changed

### ISSUE THREAD

**Issue by northpower25** [custom-components/alexa_media_player#720] opened 2020-05-14 19:12 UTC
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
in preparation for HA 0.110 the following errors are shown and make changes to the integration necessary

AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

SwitchDevice is deprecated, modify AlexaMediaSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify DNDSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify ShuffleSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify RepeatSwitch to extend SwitchEntity

MediaPlayerDevice is deprecated, modify AlexaClient to extend MediaPlayerEntity

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment] 2020-05-15 03:08
Thanks. This is a duplicate of #699

**Closed by alandtse** 2020-05-15 03:08 UTC
Labels: duplicate
