### ISSUE TITLE
Configurator Call failed

### ISSUE THREAD

**Issue by ykiv63** [custom-components/alexa_media_player#782] opened 2020-06-15 15:18 UTC
**Describe the bug**
Configurator Alexia Media Player Call failed

**To Reproduce**
1. Go to 'Notify' (new request to Alexia Media Player begin)
2. Click on 'Configure'
3. "Call Failed"

**Expected behavior**
A new request for amazon Login credentials

**Screenshots**

**System details**
 - Home-assistant (version): 0111.2
 - Hassio (Yes): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.8.4
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
Updated Hassio to 111.2
He asks me to confirm Alexa media player
Press confirmation button
Result:
Call failed
Alexa installed by hacs
Up to 111.1 fully functional

**Comment by alandtse** [comment] 2020-06-15 16:58
Dupe of #774

**Closed** 2020-06-15 16:59 UTC
