### ISSUE TITLE
Alexa turning down volume automation doesn't seem to work?

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1508] opened 2022-02-04 13:29 UTC
Something like this seems to not set it to no volume at all:

id: '1643641012752'
alias: Set day volume of speakers when working in office
description: >-
  Set general volume of speakers in office
trigger:
  - platform: time
    at: '09:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: media_player.volume_set
    data:
      volume_level: 0
    target:
      entity_id: media_player.study_room
mode: single

**Comment by alandtse** [comment] 2022-02-08 03:39
Dupe of #1429

**Closed by alandtse** 2022-02-08 03:39 UTC
