### ISSUE TITLE
[Feature Request] Support for multi room groups

### ISSUE THREAD

**Issue by Obicom** [custom-components/alexa_media_player#78] opened 2019-02-18 21:44 UTC
Thank you for your great component 
It would be great if the alexa.py component could support alexa multiroom groups.

**Comment by alandtse** [comment] 2019-02-19 02:16
Could you explain the issue a bit more? What about multiroom groups? They are discovered and can be addressed to the extent the Alexa app allows it. Is there a particular feature you are not seeing?  If you're referring to TTS, that is a known limitation of the Simon Says routine. In the 1.0.0 branch we will also expose the Announce routine that will support multiroom groups.

**Comment by alandtse** [comment] 2019-02-19 02:17
For playing music, you have to use the hack described in #74 by adding "in [name of group]" to the end of the programatic search.  This is also a known Alexa app limitation.

**Comment by alandtse** [comment] 2019-02-23 09:45
@Obicom Please provide additional details on what we're missing for you in WHAs.

**Comment by Obicom** [comment] 2019-02-23 13:25
The alexa groups are listed as a media player e.g. in my case media_player.uberall but I am not able to control thsi group (only on/off). It would be great if we could also start Tunein stream, volume and so on (like the other alexa media players. I know there is a "hack" to control the alexa group from on of the other media_players to put the group name at the end of the Tune in station like "bifFM überall".

**Comment by alandtse** [comment] 2019-02-24 05:37
Ok. Just to confirm, you're able to play/pause/next/back, right?  For anything that isn't working, can you please check to see if you can control this via the Alexa app?  If you can, we may be able to reproduce it here.

If not, we'd have to do a pretty nasty hack to try to catch it in this component. For example, to do the programmatic play (steps 3-4 are the nasty part):

1. Determine the request is for the Everywhere group.
2. Identify a member of the group to funnel the command to.
3. Add the hack statement to the search (language specific)
4. Catch for any weirdness because the different providers may not process things like umlauts properly.  (#74)

I'll mark this as an enhancement for now.

**Comment by keatontaylor** [comment] 2019-03-19 23:34
I'll look into this again, I believe it was working at one point for media playback but not things that used routine specific alexa API endpoints.

**Comment by strangedesign13** [comment] 2019-05-30 01:14
I just installed this component and it's great. But have noticed that when using `announce` with a multiroom audio group that they are not synced. Each speaker in the group makes the announcement, but they are not doing it at simultaneously as it does with say Ring doorbell announcements.

**Comment by Nihvel** [comment] 2019-07-17 11:56
> I just installed this component and it's great. But have noticed that when using `announce` with a multiroom audio group that they are not synced. Each speaker in the group makes the announcement, but they are not doing it at simultaneously as it does with say Ring doorbell announcements.

Same here. Each media_player start on its own causing a annoying delay that echoes around the rooms.

**Comment by alandtse** [comment] 2020-06-06 22:26
I believe we handle playback control as originally requested so will close this.

**Closed by alandtse** 2020-06-06 22:26 UTC
Labels: enhancement, question
