### ISSUE TITLE
2step verification 

### ISSUE THREAD

**Issue by tlmarion** [custom-components/alexa_media_player#664] opened 2020-04-27 16:11 UTC
**Describe the bug**
Trying to log in with Amazon and i receiving a screen that asks to select 2step verification method with an option of numbers. ( there is no description of what those numbers represent) I do not have 2step setup on the amazon account So I am not sure why it is asking for this information, but if i put in a number I get brought back to the integrations sign in screen as if i didnt put any of my credentials in. This is not the first account I have added with Home Assistant and dont remember it being this much of an issue or the 2SV.

**To Reproduce**

**Expected behavior**
To sign into the Amazon/ Alexa account and the intergration to be setup. 

**Screenshots**

**System details**
 - Home-assistant (version): 108.8
 - Hassio (Yes/No):  depreciated I have Home Assistant OS running though
 - alexa_media  (version from `const.py` or HA startup): the latest one. 
 - alexapy (version from `pip show alexapy` or HA startup):

**Additional context**

**Comment by alandtse** [comment] 2020-04-27 22:28
Amazon is verifying your account.
Duplicate of #568. Please provide logs or use a workaround.

**Closed by alandtse** 2020-04-27 22:28 UTC
Labels: duplicate
