### ISSUE TITLE
volume_level attribute not set when media_player.volume_set service is run

### ISSUE THREAD

**Issue by energywave** [custom-components/alexa_media_player#1429] opened 2021-11-22 00:09 UTC
**Describe the bug**
When you set a volume on an Alexa device using the `media_player.volume_set` service the `volume_level `attribute is not adjusted to reflect the change. I suspect you wait for an update from Alexa that sometimes arrives sometimes not. Most of times, if you're not listening to music or have not listened to it in the past period, the update could arrives seveeral **minutes** later.

**To Reproduce**
Use this code in developer tools -> services:
```
service: media_player.volume_set
target:
  entity_id: media_player.mansarda
data:
  volume_level: 0.4
```
then go to developers tools -> state and look at the entity you used in the target entity_id above. This is mine (some minutes later...):
```
source_list:
  - Local Speaker
volume_level: 0.5
is_volume_muted: false
media_content_type: standby
media_position_updated_at: '2021-11-19T20:45:54.014871+00:00'
source: Local Speaker
available: true
last_called: false
last_called_timestamp: 1637504727956
last_called_summary: stop
connected_bluetooth: null
bluetooth_list: []
friendly_name: Alexa mansarda
supported_features: 56253
```

**Expected behavior**
When you call the `volume_set` service update directly the `volume_level` attribute to reflect the change that otherwise will be lost.

**System details**
 - Home-assistant (version): 2021.11.4
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.12
 - alexapy (version from `pip show alexapy` or HA startup): don't know, it's all updated.
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Logs**
This is not needed here.

**Additional context**
I'm using Amazon Echo Dot devices but I don't think it will make any difference.

**Comment by energywave** [comment] 2021-11-22 00:45
I can add some details as we was discussing this issue on the italian Home Assistant group on Facebook. It seems that this happens when Alexa Media Plyer loose connection to Amazon (websocket?). It happens from time to time after several days of no reboot on Home Assistant. When in that situation Alexa entities are not updated with what is going on the devices, example I've checked and I had no update in the last 24h, when one of the Echos was super used to play music from my kids.
Volume level is not updated too when in that condition. At least I've seen that it's updated after several minutes (like there is some long time polling?)
However my request remains valid. It's as easy as set an attribute when you set volume, so we're sure to have a correct volume_level when the websocket is working and when it's not.

Then there is the theme to check and reestablish the websocket, but that's another issue....

**Comment by calas80** [comment] 2021-11-22 00:48
same problem

**Comment by alandtse** [comment] 2021-11-22 05:40
The set_volume only works once a volume has been detected. If you've lost your websocket connection, it's possible the volume has been set previously but future updates won't be reflected by the component. We fixed the latest websocket issue. Reload the component if you lose it. 

There may be a bug in that if we successfully send a set_volume command, we may be able to update the local state. I will consider that as it makes it more complex to cache values locally and not rely on Amazon as the source of truth. With websocket fixed, it shouldn't be an issue.

**Comment by alandtse** [comment] 2021-11-23 10:29
Dupe of #1394 basically if websocket is up.

**Comment by energywave** [comment] 2021-11-23 11:11
I disagree, it's not a dupe of that issue (that I support) as this request is only to update the attribute when the service volume_set is run. I do it with automation using the python script set_state and it works very well but that's a workaround, that should be done by the integration itself, in my point of view.
There are no cons about that. You update the volume_level, if then a websocket event arrives that will overwrite that value. But if the websocket is stuck (and it happens with the latest version too! Already happened...) that will give us some important info about the volume so that we can manage a volume backup and restore...

**Comment by alandtse** [comment] 2021-11-23 11:24
If you want to submit a PR to set a local state that isn't in sync with Amazon, then you can. But if there are bug reports about it not matching, I'd hope you'd address them. 

It seems simple to you but adding a local state separate from Amazon adds complexity to the component which unfortunately I need to maintain. So there is a con for me. My time isn't worthless so I'd appreciate some consideration of that. I literally said already I'm thinking about it.

**Comment by energywave** [comment] 2021-11-23 11:33
Ok, don't be angry, my intent is to help you get a better integration for all of us as I'm working hard with Alexa devices and I'm developing a complex script for notifications that I'll publish on github and on my blog.
I appreciate all the time you're putting in this, I know the 1000 challenges you had with login and Amazon changes so please forgive me if I push my request, my intent is good, trust me.
I'm a developer but unluckily not in python so I'm not able to build a PR. Otherwise I would been happy to help you.
I know you have a complete vision of the thing, I'm getting only a "user" perspective so it seems easy for me but I take note that there are complexity on your side. It seemed simple by me but ok, maybe it's not.
Stated this I'll continue to use set_state python script to achieve my result, no problems.

**Closed** 2022-01-30 02:06 UTC
Labels: no-issue-activity
