### ISSUE TITLE
Next Timer, Next Alarm, Next Reminder sensors not being created

### ISSUE THREAD

**Issue by vadimolen** [custom-components/alexa_media_player#765] opened 2020-06-05 12:50 UTC
**Describe the bug**
The Next Timer, Next Alarm, and Next Reminder sensors are not being created for any of my Alexa devices. media_player devices are created for each and work correctly.

**To Reproduce**
Restart Home Assistant. Notice the lack of sensors.

**Expected behavior**
Each included Echo device should have corresponding Next Timer, Next Alarm, Next Reminder sensors.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.108.4
 - Hassio (Yes/No): NO
 - alexa_media  (version from `const.py` or HA startup):  2.8.3
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.1

**Logs**
See attached.
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/4736195/home-assistant.log)

**Comment by alandtse** [comment] 2020-06-06 07:08
Please make sure you are not [excluding](https://github.com/custom-components/alexa_media_player/wiki/Configuration#configuring-inclusions-or-exclusions-versions--096) the sensors. `include_device` is a white list. `exclude_device` is a black list.

```text
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Garage next Alarm: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Garage next Timer: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Garage next Reminder: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Kitchen next Alarm: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Kitchen next Timer: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Kitchen next Reminder: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Bedroom next Alarm: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Bedroom next Timer: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Bedroom next Reminder: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Living Room next Alarm: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Living Room next Timer: unavailable>
2020-06-05 07:33:03 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*******n@g*******m: Excluding device: <Entity Living Room next Reminder: unavailable>
```

Duplicate of #745

**Closed by alandtse** 2020-06-06 07:08 UTC
Labels: duplicate
