### ISSUE TITLE
Alexa Gaurd: icon color inverted

### ISSUE THREAD

**Issue by starkillerOG** [custom-components/alexa_media_player#556] opened 2020-02-08 10:21 UTC
**Describe the bug**
If you add the Alexa Gaurd alarm panel to a glance card (`alarm_control_panel.alexa_guard`), the icon is yellow when the alarm is off and standard blue when the alarm is armed, this is inverted compared to every other enitity that shows up yellow when 'on' and blue when 'off'.

Note: This was not the case in HomeAssistant 0.104.x, updating to 0.105.2 made the colors invert I think. HomeAssistant 0.105.2 also made changes to the way colors are used in icons.

**Expected behavior**
Armed/on = yellow icon
disarmed/off = blue icon

**Screenshots**
![alexa gaurd - icon color off](https://user-images.githubusercontent.com/14811189/74083451-70549d80-4a64-11ea-9f90-b2b7868874de.PNG)
![alexa gaurd - icon color on](https://user-images.githubusercontent.com/14811189/74083463-98dc9780-4a64-11ea-86a7-ac029684fc76.PNG)

**System details**
 - Home-assistant (version): 0.105.2
 - Hassio: No
 - alexa_media: v2.5.4
 - alexapy: 1.4.2

**Logs**

**Additional context**

**Comment by alandtse** [comment] 2020-02-08 21:06
I don't think this is limited to `alexa_media` as I can reproduce it with other alarms and this component doesn't do anything with the icon.   I'd say you can raise it with HA about the glances card, but if you mention alexa_media they'll refuse to look at it at all.

**Comment by starkillerOG** [comment] 2020-02-09 22:32
@alandtse thanks, just opened an issue in HomeAssistant.

**Comment by alandtse** [comment] 2020-02-10 04:12
I'll close this for now, if it turns out there's something components have to do, then let me know.

If they ask, my simplisafe alarm has the issue on the glances card.

**Closed by alandtse** 2020-02-10 04:12 UTC
