### ISSUE TITLE
I cant login from integration page

### ISSUE THREAD

**Issue by Mohannadshariefhome** [custom-components/alexa_media_player#738] opened 2020-05-22 00:51 UTC
after HA and integration update I cant login and it is not showing any error messages

**Comment by engalzaid** [comment] 2020-05-22 01:20
Same issue !

**Comment by engalzaid** [comment] 2020-05-22 01:56
I try this and work with me
https://github.com/custom-components/alexa_media_player/issues/733#issuecomment-631526947

**Comment by alandtse** [comment] 2020-05-22 06:56
Duplicate of #733

**Closed by alandtse** 2020-05-22 06:56 UTC
Labels: duplicate
