### ISSUE TITLE
Captcha code not appearing 

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#651] opened 2020-04-19 13:00 UTC
**Describe the bug**
Captcha code does not appear on phone OR laptop using chrome/safari:

**Screenshots**
![2A9A749F-0A50-4EA1-8114-90937DB66E28](https://user-images.githubusercontent.com/15043282/79688331-012fcc80-8291-11ea-8c42-fc0217b9bb33.png)

**System details**
 - Home-assistant (version): latest
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): latest 
 - alexapy (version from `pip show alexapy` or HA startup): latest

**Comment by jaco523** [comment] 2020-04-19 14:29
I have the same issue

**Comment by alandtse** [comment] 2020-04-19 19:22
Click confirm to reload.

**Comment by oneseventhree** [comment] 2020-04-19 20:15
> Click confirm to reload.

I have multiple times but no image loads. I’ve never had this problem before

**Comment by alandtse** [comment] 2020-04-19 20:17
Fill out the template. Latest doesn't mean anything to me.

**Comment by oneseventhree** [comment] 2020-04-20 02:19
**Describe the bug**
Captcha code does not appear on phone OR laptop using chrome/safari.

**To Reproduce**
Steps to reproduce the behavior:
1. Restart HomeAsssisant 
2. Notfication appears in UI:
"Configurator
Click button to configure Alexa Media Player - Captcha -"
3. Click 'Configure'
4. Captcha doesn't show up
5. Clicking 'Confirm' doesn't fix the issue


**Expected behavior**
Captcha code used to pop up

**Screenshots**
Chrome screenshot:
<img width="361" alt="Screen Shot 2020-04-20 at 12 01 35 pm" src="https://user-images.githubusercontent.com/15043282/79707214-09265580-82ff-11ea-9aa5-473ad24e7df9.png">


**System details**
 - Home-assistant (version): 0.108.6
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): __version__ = "2.5.13"
 - alexapy (version from `pip show alexapy` or HA startup): Cannot find

**Logs**
I can't send the log because when I try and open it it says:
<img width="423" alt="Screen Shot 2020-04-20 at 12 18 25 pm" src="https://user-images.githubusercontent.com/15043282/79707841-20664280-8301-11ea-9808-13d360cdc913.png">

and I can't put the Captcha in to log into the log file

**Additional context**
N/A

**Comment by oneseventhree** [comment] 2020-04-20 02:19
> Fill out the template. Latest doesn't mean anything to me.

let me know if you need anything else aside from the above post

**Comment by alandtse** [comment] 2020-04-20 02:26
Thanks. The logs isn't the HTML page you are trying to open but your homeassistant logs showing the component's attempt to communicate with Amazon. It will show the url that Amazon is sending you with the image, you can try to manually load it to see if it appears. Every time you hit confirm it will send a wrong answer to Amazon and then Amazon will send a new image. To the extent you can't load the image file, that is likely an issue with your network since other than getting the link to display to HA, the component isn't doing anything with the image.

**Comment by oneseventhree** [comment] 2020-04-20 02:31
> Thanks. The logs isn't the HTML page you are trying to open but your homeassistant logs showing the component's attempt to communicate with Amazon. It will show the url that Amazon is sending you with the image, you can try to manually load it to see if it appears. Every time you hit confirm it will send a wrong answer to Amazon and then Amazon will send a new image. To the extent you can't load the image file, that is likely an issue with your network since other than getting the link to display to HA, the component isn't doing anything with the image.


I just reverted back to v2.5.12 and it works with that:
<img width="381" alt="Screen Shot 2020-04-20 at 12 29 34 pm" src="https://user-images.githubusercontent.com/15043282/79708399-a8991780-8302-11ea-8b5a-263537531a59.png">

I then updated back to v2.5.13 and the image is broken again

What would be different between the two that causes this?

**Comment by alandtse** [comment] 2020-04-20 02:48
[Nothing related](https://github.com/custom-components/alexa_media_player/compare/v2.5.12...v2.5.13) to the captcha.

**Comment by cmille34** [comment] 2020-04-20 19:35
Thanks @oneseventhree for the tip to revert back to 2.5.12.  That worked for me as well, now the captcha works again.

**Comment by javiermartingonzalez** [comment] 2020-04-23 14:30
I'm having problems with verification after capthca.

I'm getting device option and SMS. If a press device, I receive a notification from Amazon saying that it's me. I pressed 'yes' and get a "Signin confirmed" but components is asking for a confirmation code. For SMS option, not receiving the message.

**Comment by wokhen** [comment] 2020-04-24 09:07
Same issue here.
I tried to access captcha from image link but got this in the new window:

```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2020-04-23T07:09:11Z</Expires>
<ServerTime>2020-04-24T08:55:01Z</ServerTime>
<RequestId>75349D..DC7D8DD</RequestId>
<HostId>
HUn7vDThIJq8d4HngtBvyhycHpw87VJZTl8...sWTP0Om7M9A97ngoSVNeqtHB62KS4=
</HostId>
</Error>
```
Thank you
W

**Comment by sagitt** [comment] 2020-04-24 12:20
same problem, and from yesterday i can't login. 
yesterday captcha works, but when i have to insert 0-2 for confirmation code, after no confirmation code. so i can't login.

**Comment by alandtse** [comment] 2020-04-24 21:01
This thread is only for the catpcha issue. Please use the appropriate thread #568 for verification code issues.

**Comment by chilicheech** [comment] 2020-04-27 05:53
This is happening to me too. I'm going to try the downgrade idea.

**Comment by chilicheech** [comment] 2020-04-27 06:01
Yep. Downgrading from 2.5.15 to 2.5.14 made it work again. Something's broken with the captcha in 2.5.15

**Comment by oneseventhree** [comment] 2020-04-27 12:24
> Yep. Downgrading from 2.5.15 to 2.5.14 made it work again. Something's broken with the captcha in 2.5.15

Try upgrading again. I did it and it worked
for me but I had to go down to .14 then up again to .15

**Comment by chilicheech** [comment] 2020-04-27 16:16
That seems to have worked. Thanks @oneseventhree

**Comment by codycodes** [comment] 2020-05-05 18:07
Hey, this issue popped up for me as well on the latest 2.6.1; I'm looking at the advice for downgrading to 2.5.14 and tried it myself. Glad to say it works and is easy/painless to do from HACS! I decided to compare changes between the 2.5.14 and 2.5.15 versions and it appears there could be an issue stemming from localization? [See the comparison here](https://github.com/custom-components/alexa_media_player/compare/v2.5.14...v2.5.15). Since new features and fixes would be nice, I think @alandtse this deserves another look and @oneseventhree this issue should be reopened. A downgrade is not a good long-term solution.

**Comment by oneseventhree** [comment] 2020-05-05 20:59
> Hey, this issue popped up for me as well on the latest 2.6.1; I'm looking at the advice for downgrading to 2.5.14 and tried it myself. Glad to say it works and is easy/painless to do from HACS! I decided to compare changes between the 2.5.14 and 2.5.15 versions and it appears there could be an issue stemming from localization? See the comparison here. Since new features and fixes would be nice, I think @alandtse this deserves another look and @oneseventhree this issue should be reopened. A 
downgrade is not a good long-term solution.

> 

Reopened

**Comment by codycodes** [comment] 2020-05-05 21:02
Hey, sorry for my previous comment. I wasn't aware that downgrading and then re-updating somehow solves the issue. That also worked for me, but I have no idea why. I'm not sure how the issue can be reproduced. So I deleted the previous comment, and is why I wrote stating that staying in a downgraded state wouldn't be a good long-term solution.

I'm not sure if there's a fix besides the downgrade/update process. Thanks for reopening this issue but I don't have any helpful info at this point! I just +1'd the downgrade/upgrade since it worked for me. Sorry for the ping!

**Comment by alandtse** [comment] 2020-05-11 07:34
Closing this out. There was no change in the code between the revisions for the captcha as reported. The fact it works at a different time may be an amazon issue.

**Closed by alandtse** 2020-05-11 07:34 UTC

**Comment by treydock** [comment] 2020-05-22 22:09
Commenting in case anyone else has this issue, one thing I did with v2.8.0 was restart home assistant then immediately do the configuration step once HA was loaded and the captcha was present. When the image was broken I pasted the URL into my browser and noticed part of the response was "Request has expired", so figured the request may have been made when HA was started and not when I was loading the page but maybe that's wrong.

**Comment by alandtse** [comment] 2020-05-22 23:49
@treydock That's actually correct. The request is made right when HA loads so if it takes time to get to the image, it may expire. However, if you submit any answer it will load a new caption because it assumes the first one was wrong.
