### ISSUE TITLE
Alexa Media Player - Verification Method not sending verification code

### ISSUE THREAD

**Issue by Arkadije** [custom-components/alexa_media_player#627] opened 2020-04-03 21:15 UTC
After entering Captcha, it is asking me for the Verification Method. 

![Screenshot_1](https://user-images.githubusercontent.com/4341856/78405017-ea864600-75ff-11ea-851a-3168edb9d37f.png)

Verification Method can be done by:
-  push notification to my phone
-  SMS 
 
![Screenshot_2](https://user-images.githubusercontent.com/4341856/78405026-ebb77300-75ff-11ea-9273-735326ed4e62.png)

Eather of those options does not work. I do not get any push notification when I choose that option and do not receive SMS when I choose that option. 

When I try to enter email, the system does not accept that option. The page is reloaded with the same options as above.

I cannot finish the integration process.

![Screenshot_3](https://user-images.githubusercontent.com/4341856/78405083-0558ba80-7600-11ea-8a04-95edc4c59b11.png)

Please advise

**Comment by gridi88** [comment] 2020-04-03 23:14
same problem for me too.

**Comment by alandtse** [comment] 2020-04-04 02:13
Thanks. Duplicate of #568. Work around and request for logs so we can solve it are in that thread.

**Closed by alandtse** 2020-04-04 02:13 UTC
Labels: duplicate
