### ISSUE TITLE
Unable to login into the component

### ISSUE THREAD

**Issue by ashoktvm** [custom-components/alexa_media_player#585] opened 2020-03-11 02:10 UTC
I was using the component perfectly and suddenly it is asking to configure. But after entering the captcha this is what I was asked to do (screenshot below). But I am unable to select anything. What to do now?

![image](https://user-images.githubusercontent.com/45116583/76375344-91622400-636b-11ea-9570-0bf9698f0fb0.png)

**Comment by ashoktvm** [comment] 2020-03-11 02:26
When I enter sms, it is not sending any sms to verify, Also entering the the push device name is also not working. Not getting any notification message

**Comment by ashoktvm** [comment] 2020-03-11 03:44
this is the only thing I get in debug

2020-03-11 08:24:00 INFO (SyncWorker_2) [pynetgear] Get attached devices 2
2020-03-11 08:24:11 INFO (SyncWorker_1) [pynetgear] Get attached devices 2
2020-03-11 08:24:22 INFO (SyncWorker_18) [pynetgear] Get attached devices 2
2020-03-11 08:24:33 INFO (SyncWorker_14) [pynetgear] Get attached devices 2
2020-03-11 08:24:44 INFO (SyncWorker_11) [pynetgear] Get attached devices 2
2020-03-11 08:24:55 INFO (SyncWorker_12) [pynetgear] Get attached devices 2
2020-03-11 08:25:06 INFO (SyncWorker_9) [pynetgear] Get attached devices 2
2020-03-11 08:25:17 INFO (SyncWorker_15) [pynetgear] Get attached devices 2

2020-03-11 08:25:28 INFO (SyncWorker_13) [pynetgear] Get attached devices 2
2020-03-11 08:25:38 WARNING (MainThread) [homeassistant.components.device_tracker] Updating device list from legacy took longer than the scheduled scan interval 0:00:10
2020-03-11 08:25:49 INFO (SyncWorker_12) [pynetgear] Get attached devices 2
2020-03-11 08:26:00 INFO (SyncWorker_12) [pynetgear] Get attached devices 2
2020-03-11 08:26:11 INFO (SyncWorker_3) [pynetgear] Get attached devices 2
2020-03-11 08:26:22 INFO (SyncWorker_2) [pynetgear] Get attached devices 2

**Comment by alandtse** [comment] 2020-03-12 06:14
I'll need the advanced debugging html for the page showing the multiple options. This is also a dupe of #568. Please see my instructions in that thread to generate the html page for review and report there.

**Closed by alandtse** 2020-03-12 06:14 UTC
