### ISSUE TITLE
Latest update of HA breaks alexapy 1.25.3 due to dependency conflicts. Please update to version 1.26.0

### ISSUE THREAD

**Issue by Akisame-AI** [custom-components/alexa_media_player#1627] opened 2022-06-05 18:48 UTC
I updated my HA instance and noticed that my Alexa notifications stopped worked. I checked the logs and turned out that alexapy 1.25.3 was having some dependency issues and could not be started.
I tried a couple of reboots without success.
Checking alexapy's commits since februari shows no conflicts with the current code and it should be fine to update.
I fixed it by installing alexapy==1.26.0 and changing the version in the manifest.json. 
It is running fine again.

1. update HA to core-2022.6.2
2. reboot
3. A notification will pop up saying that notify.alexa_media failed to start

alexapy 1.25.3 is having dependency conflicts resulting in alexa_media failing to start.
(specifically it is the cryptography dependency. version 1.25.x NEEDS cryptography version 35. Other programs NEED cryptography version >36 thus alexapy is unable to install. Version 1.26.0 loosened the cryptography requirement in commit: @b1e61786 to cryptography = >35.0 thus fixing the issue.)

**System details**
## System Health

version | core-2022.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4862
Installed Version | 1.22.0
Stage | running
Available Repositories | 1117
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 237.7 GB
disk_used | 21.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.12.2), Duck DNS (1.15.0), Samba share (9.6.1), SSH & Web Terminal (10.1.1), File editor (5.3.3), Dnsmasq (1.4.4), Studio Code Server (4.2.0), ESPHome (2022.3.1), Home Panel (2.3.3), Check Home Assistant configuration (3.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 31, 2022 at 6:11 PM
-- | --
current_recorder_run | June 5, 2022 at 8:30 PM
estimated_db_size | 3708.88 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

Simply updating to alexapy 1.26.0 fixes the dependency issues and allows for alexapy to be installed.

**Comment by alandtse** [comment] 2022-06-06 05:55
Thanks. The dependency hasn't been an issue since AMP 3.11.3, release April 28, 2022.
https://github.com/custom-components/alexa_media_player/commit/beedc062eb67114762ce2b322e68748f6e896ee6.

Anyone running an earlier version needs to update to 3.11.3 or newer if they want to use HA 2022.6.

**Comment by alandtse** [comment] 2022-06-06 05:56
Dupe of #1579

**Closed by alandtse** 2022-06-06 05:55 UTC
