### ISSUE TITLE
HA update from 11.5 to 12.8 failed due to alexa media player error

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1480] opened 2022-01-06 09:38 UTC
**Describe the bug**
The update failed.

**To Reproduce**
1. Updated HA OS - successful
2. Update to latest alexa version .15 via HACS
3. Then restarted HA - refused due to the reported error
4. See error logs

So in fact, updating amp works but then HA cannot restart.

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 2021.11.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.12
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
````
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/__init__.py:16
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:49:49 (3 occurrences)
Last logged: 09:55:58

[281472370983696] function() argument 'code' must be code, not str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 586, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 218, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
````

**Additional context**
Due to this bug, the notification could not be loaded as well
Rolled back to 2021.11.5 and everything is ok so far

**Comment by damianjflanagan** [comment] 2022-01-07 05:37
I'm having the exact same issue, I have to delete the integration in hacs then force restart HA (pulling the power plug) before I can do anything with it.

**Comment by damianjflanagan** [comment] 2022-01-07 05:44
It only seems to happen when updating from an older version, if you do a clean install of HACS it works (tried this a few times to confirm).
(but now I cant login again)

**Comment by alandtse** [comment] 2022-01-08 03:04
Dupe of #1467, please search closed issues.

**Closed by alandtse** 2022-01-08 03:04 UTC

**Comment by Pirol62** [comment] 2022-01-08 08:09
But what to do, if HA refuses to restart due to exactly this error we want to repair? Did I di something wrong upfront?

**Comment by alandtse** [comment] 2022-01-08 08:21
Just delete the alexa_media directory from custom_components and reinstall with HACS.

**Comment by Pirol62** [comment] 2022-01-26 09:03
Sorry but I deleted the folder, reloaded amp but HA will not restart due to the error posted above.
