### ISSUE TITLE
Alexa Reauthentication Login page shows blank window

### ISSUE THREAD

**Issue by Bart56** [custom-components/alexa_media_player#944] opened 2020-09-25 00:14 UTC
**Describe the bug**
After getting notified that Alexa Media Reauthentication Required
Reauthenticate on the Integrations page, I go to the integrations page and click 'configure'. A few days ago, I got a full popup asking for email, password, 2FA code (I have 2FA enabled on Amazon). No captcha appeared. After clicking on submit, a small blank popup appears with only an 'X' on the right which closes the popup. All attempts since have given me the blank popup including updating to latest version 3.0 and hard (power off/on) many times. I've enabled logging and the html files that appear in the config directory appear to be complete.
I'm attaching the log file

**To Reproduce**
1. Go to 'integrations.'
2. Click on 'configure. for the Alexa integration'
3. blank box appears

![after_config](https://user-images.githubusercontent.com/46532079/94212248-a5055000-fea1-11ea-8feb-cc90de39eeb3.jpg)

**Expected behavior**
A popup with text to request email, password, 2fa, captcha if necessary.

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
Hassio: Home Assistant Core  0.107.7, Supervisor 245, Operating system
Raspbian GNU/Linux 10 (buster) Docker version 19.03.8
 - alexa_media  (__version__ = "3.0.0"):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 
YES - I did this a little over 2 weeks ago and it worked fine. When Amazon needed reauthentication 4 days ago, this happened and I no longer have access to alexa devices.

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/5279816/home-assistant.log)

**Additional context**
Reporter from #941 mentioned:
 An error message is displayed in the browser after adding the integration.

![image](https://user-images.githubusercontent.com/7328224/93856828-e6d3a200-fcb9-11ea-9d31-99cefb2586c7.png)

**Comment by alandtse** [comment] 2020-09-25 04:03
Duplicate of #941. Your logs also don't show any strange pages.  Try doing a hard [refresh](https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie). It may also be your HA version since it's a UI issue.

**Comment by alandtse** [comment] 2020-09-25 04:03
Actually, I like your report better than the other reporter's. I'll move his here.

**Comment by Bart56** [comment] 2020-09-25 16:07
Interesting. Thinking it might be a cache page, I tried it in Firefox (different browser on another computer with the same result. I used the F12 dev tool in chrome to see the following:
_**updating-element.ts:661 Uncaught (in promise) e {message: "Expected "\\#", "\\\\", "\\u", "\\{", "\\}", "{", …\n\r], end of input or whitespace but "\\" found.", expected: Array(9), found: "\", location: {…}, name: "SyntaxError", …}expected: Array(9)0: {type: "literal", value: "\#", description: ""\\#""}1: {type: "literal", value: "\\", description: ""\\\\""}2: {type: "literal", value: "\u", description: ""\\u""}3: {type: "literal", value: "\{", description: ""\\{""}4: {type: "literal", value: "\}", description: ""\\}""}5: {type: "literal", value: "{", description: ""{""}6: {type: "class", value: "[^{}\\\0-\x1F\x7f \t\n\r]", description: "[^{}\\\0-\x1F\x7f \t\n\r]"}7: {type: "end", description: "end of input"}8: {type: "other", description: "whitespace"}length: 9__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Objectfound: "\"location: end: {offset: 33, line: 1, column: 34}start: {offset: 32, line: 1, column: 33}__proto__: Objectmessage: "Expected "\\#", "\\\\", "\\u", "\\{", "\\}", "{", [^{}\\\0-\x1F\x7f \t\n\r], end of input or whitespace but "\\" found."name: "SyntaxError"stack: "SyntaxError: Expected "\\#", "\\\\", "\\u", "\\{", "\\}", "{", [^{}\\\0-\x1F\x7f \t\n\r], end of input or whitespace but "\\" found.↵    at Ae (https://**.duckdns.org/frontend_latest/app.62bea903.js:888:19124)↵    at Function.parse (https://**.duckdns.org/frontend_latest/app.62bea903.js:888:24957)↵    at new y (https://**.duckdns.org/frontend_latest/app.62bea903.js:743:14835)↵    at https://**.duckdns.org/frontend_latest/app.62bea903.js:743:18005↵    at w (https://**.duckdns.org/frontend_latest/app.62bea903.js:743:18243)↵    at Object.renderShowFormStepDescription (https://**.duckdns.org/frontend_latest/chunk.5d925a9e0687e9c47d80.js:790:171)↵    at HTMLElement.value (https://**.duckdns.org/frontend_latest/chunk.20c30223f0f7815699c8.js:1810:27)↵    at HTMLElement.update (https://**.duckdns.org/frontend_latest/app.62bea903.js:2:19032)↵    at HTMLElement.performUpdate (https://**.duckdns.org/frontend_latest/app.62bea903.js:2:14835)↵    at HTMLElement._enqueueUpdate (https://**.duckdns.org/frontend_latest/app.62bea903.js:2:14465)"__proto__: Errorconstructor: ƒ e(t,n,r,i)__proto__: Object
_enqueueUpdate @ updating-element.ts:661
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
A @ updating-element.ts:438
V @ lit-element.ts:61
i @ step-flow-form.ts:27
_clone @ template-instance.ts:99
__commitTemplateResult @ parts.ts:276
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:277
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
a @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ dialog-data-entry-flow.ts:113
async function (async)
value @ dialog-data-entry-flow.ts:105
E @ make-dialog-manager.ts:44
async function (async)
E @ make-dialog-manager.ts:43
(anonymous) @ make-dialog-manager.ts:55
r @ fire_event.ts:76
o @ show-dialog-data-entry-flow.ts:91
l @ show-dialog-config-flow.ts:23
value @ ha-config-entries-dashboard.ts:270
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463**_

This looks like something is wrong with the html strings passed to the popup dialog. So I'm not sure what's going on (note: **.duckdns is correct, I just changed the hostname to two asterisks)

**Comment by alandtse** [comment] 2020-09-25 18:56
What language are you using? Do you see that language in the alexa_media/translations directory?

**Comment by Bart56** [comment] 2020-09-25 21:59
I'm in the US so it's set for English language. The en.json file in the translations directory does not contain the above text.
The en.json looks like this (not sure this helps but here it is):
{
  "config": {
    "abort": {
      "forgot_password": "The Forgot Password page was detected. This normally is the result of too may failed logins. Amazon may require action before a relogin can be attempted.",
      "login_failed": "Alexa Media Player failed to login.",
      "reauth_successful": "Alexa Media Player successfully reauthenticated."
    },
    "error": {
      "connection_error": "Error connecting; check network and retry",
      "identifier_exists": "Email for Alexa URL already registered",
      "invalid_credentials": "Invalid credentials",
      "unknown_error": "Unknown error, please report log info"
    },
    "step": {
      "action_required": {
        "description": "**{email} - alexa.{url}**  \\nAmazon will send a push notification per the below message. Please completely respond before continuing.  \\n{message}",
        "title": "Alexa Media Player - Action Required"
      },
      "authselect": {
        "data": {
          "authselectoption": "OTP method"
        },
        "description": "**{email} - alexa.{url}**  \\n{message}",
        "title": "Alexa Media Player - One Time Password"
      },
      "captcha": {
        "data": {
          "captcha": "Captcha",
          "password": "Password",
          "securitycode": "2FA Code (recommended to avoid login issues)"
        },
        "description": "**{email} - alexa.{url}**  \\n>{message}  \\n{captcha_image}",
        "title": "Alexa Media Player - Captcha"
      },
      "claimspicker": {
        "data": {
          "authselectoption": "Verification method"
        },
        "description": "**{email} - alexa.{url}**  \\nPlease select verification method by number. (e.g., `0` or `1`)  \\n{message}",
        "title": "Alexa Media Player - Verification Method"
      },
      "twofactor": {
        "data": {
          "securitycode": "2FA Code"
        },
        "description": "**{email} - alexa.{url}**  \\n>Enter the One Time Password (OTP).  \\n{message}",
        "title": "Alexa Media Player - Two Factor Authentication"
      },
      "user": {
        "data": {
          "debug": "Advanced debugging",
          "email": "Email Address",
          "exclude_devices": "Excluded device (comma separated)",
          "include_devices": "Included device (comma separated)",
          "password": "Password",
          "scan_interval": "Seconds between scans",
          "securitycode": "2FA Code (recommended to avoid login issues)",
          "url": "Amazon region domain (e.g., amazon.co.uk)"
        },
        "description": "Please enter your information.  \\n**WARNING: Amazon incorrectly reports 'Enter a valid email or mobile number' when 2FA Code is required.**  \\n>{message}",
        "title": "Alexa Media Player - Configuration"
      }
    },
    "title": "Alexa Media Player"
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "queue_delay": "Seconds to wait to queue commands together"
        }
      }
    }
  }
}

**Comment by alandtse** [comment] 2020-09-25 23:26
I think it may be a HA thing. Can you update to a later version? Alternatively you can try an earlier version of the component to see if it resolves it. We did make some changes to the json data recently.

**Comment by alandtse** [comment] 2020-09-25 23:27
Oh wait, there shouldn't be `\\` in the json. Can you see what happens if you replace them with just `\`

**Comment by Bart56** [comment] 2020-09-25 23:34
Yes - I was using 2.11.0 until this happened. Then I tried 2.11.2 and the
problem continued. It's worth a shot since The very first reauth request
looked ok, but it's been the little empty dialog since.  I had tried HA
core 108.1 some time ago but it acted a little strange so I dropped back to
107 which has been stable for me with 2.11.0 for 6 months, then stayed ok
once I got the 2FA set on Amazon. THen this happened 4 or 5 days ago.
I'll first try 2.11.0 again with a cold start then see which core I want to
try.
Thanks. I'll get back to you.

**Comment by Bart56** [comment] 2020-09-26 00:13
Ok. I went back to 2.11.0. First time I tried to configure the integration I got the original dialog box as it should be (I think) as this shows:
![1st-good](https://user-images.githubusercontent.com/46532079/94324865-d47f8f80-ff69-11ea-9204-46b7a3e9887b.jpg)

So I enter the 2FA from my auth app and it comes back with the small empty dialog box again.  I can not get past this until I tried something. Since the _pycache_ directory is created when HA comes up, I deleted that directory and restarted HA and sure enough I get the original dialog as above. The post.html appears to be good:

![1st-good-post](https://user-images.githubusercontent.com/46532079/94325070-ac446080-ff6a-11ea-87a7-4e0201a44671.jpg)

Since I can't get past the little blank dialog, I again restart HA and delete the _pycache_ directory and when it comes up, I get the same correct 1st good dialog to authenthicate again, but the resulting post.html is missing the captcha as in:
![2nd-bad-post](https://user-images.githubusercontent.com/46532079/94325220-5a500a80-ff6b-11ea-90a2-285c6d0ac213.jpg)

Of course, I can't see any of this thru HA. I have to execute the html files to pop up in my browser which is on a windows machine. 
LMK if I can add anything.
B

**Comment by alandtse** [comment] 2020-09-26 00:34
Ok, check the json file I mentioned. I think something happened when we pulled the translations in the build.

**Comment by Bart56** [comment] 2020-09-26 01:16
> Oh wait, there shouldn't be `\\` in the [json](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/.translations/en.json). Can you see what happens if you replace them with just `\`

So wait...
You're saying that lines like this:

  "description": "**{email} - alexa.{url}**\\n{message}",
                "title": "Alexa Media Player - One Time Password"

should not have the double \\n and should only have \n(message)

I find it odd that both the translations and .translations folders both have the same text and that nothing was changed when this first happened. . There are quite a few double //'s but I will try it tomorrow if you think there is something to it. (I checked the spanish json file and it too had the double slashes.)

**Comment by Bart56** [comment] 2020-09-26 10:31
Ok, I edited just the en.json file and changed all the double \\ to single.
I restarted HA and while restarting, I deleted _pycache_ and VOILA! The
correct dialog boxes showed including the captcha, and the authenticated
login seems to have gone through correctly. This was on 2.11.0 again. I
have no idea how it worked the first time but the end message started with
"Aborted" then login successful or authentication successful - or something
like that.

But it works! All my devices are back. The only outstanding question is why
are there two translation directories since at least 2.11.0?

I'll post this double slash \\n fix on the forum.

Thanks for your help.

**Comment by alandtse** [comment] 2020-09-26 20:01
HA switched the location from .translations to translations. We have both for backwards compatibility.

**Comment by denzelm5** [comment] 2020-09-26 21:07
Hi,

Im still having the issue with getting stuck at this page . I click submit and nothing happens.
![ha](https://user-images.githubusercontent.com/57428868/94350280-074e8400-004d-11eb-8b18-76e9f185e329.JPG)

**Comment by Bart56** [comment] 2020-09-26 21:30
. Intereis that I renamed the 'translations' dir to something else and edited the en.json file in the .translations dir.

Looking at the image denzelm5 sent, he may be hitting the '\\n' issue in the same file. Try editing the en.json file to change '\\n' to '\n' in all lines (there are 5 or 6 in there.)

**Comment by alandtse** [comment] 2020-09-26 21:32
No, the issue @denzelm5 has is 2FA is not enabled. It is mandatory. Also this is offtopic so I'll be marking the comments appropriately.

**Closed** 2020-09-27 00:05 UTC
Labels: bug
