### ISSUE TITLE
`homeassistant.components.alarm_control_panel` slowing reboot substantially 

### ISSUE THREAD

**Issue by Kanga-Who** [custom-components/alexa_media_player#368] opened 2019-09-19 02:26 UTC
`2019-09-19 01:30:42 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.`

Is there a way to disable this to prevent to lag time in HA starting? Currently, when I reboot it takes 2 close to 2 mins for HA to restart - normally takes 20 secs (Core i5 Dell machine).

Hass.io 0.98.5
Alexa Media 2.1.2 via HACS

**Comment by alandtse** [comment] 2019-09-19 02:41
Dupe of #357. Please take a look.

**Closed** 2019-09-19 02:41 UTC

**Comment by Kanga-Who** [comment] 2019-09-19 03:09
Thanks @alandtse 

I did do a search for the specific error message before posting, nothing came back. Thanks for the link to the other thread.
