### ISSUE TITLE
Ability to turn on/off scheduled alarm

### ISSUE THREAD

**Issue by Molodax** [custom-components/alexa_media_player#736] opened 2020-05-21 09:38 UTC
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
There is a problem with Alexa alarm that scheduled weekdays alarm will ring respectively of national holidays, while homeassistant is able to identify those days.

**Describe the solution you'd like**
It would be nice to be able to control the scheduled Alexa alarm from homeassistant such as on/off alarm.

**Describe alternatives you've considered**
It would be even better to be able to schedule the Alexa alarm from the component.

**Additional context**

**Comment by alandtse** [comment] 2020-05-22 09:31
Dupe of #437

**Closed by alandtse** 2020-05-22 09:31 UTC
Labels: duplicate
