### ISSUE TITLE
Amazon Authentication

### ISSUE THREAD

**Issue by nz365guy** [custom-components/alexa_media_player#646] opened 2020-04-15 09:54 UTC
**Describe the bug**
After entering email, password and captcha it asks me to verify with SMS or push to one of my ios devices.  I entered my phone number in the filed provided and it then displays a popup with a line that has required and submit.  No code came through and I can not get past this point.

**To Reproduce**
1. Go to 'Set up a new integration'
2. Click on 'Alexa Media Player'
3. Scroll down to 'Fill out email address and password for Amazon and complete captcha, then chose either sms of a push to ios devise, enter mobile number for SMS'
4. No code is sent

**Expected behavior**
Should have received a code to complete Amazon authentication.

**Screenshots**
https://www.dropbox.com/s/s63y0wu21mdq3hq/2020-04-15_21-49-43.png?dl=0 
**System details**
 - Home-assistant (version): 
System | HassOS 3.12
-- | --

 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment] 2020-04-16 19:52
Dupe of #568 . Workarounds and request for info there.

**Closed by alandtse** 2020-04-16 19:52 UTC
