### ISSUE TITLE
Error: Too Many Requests

### ISSUE THREAD

**Issue by JoeTN** [custom-components/alexa_media_player#612] opened 2020-03-27 19:42 UTC
I'm getting the "Too Many Requests"-error when using the following script. The idea is to first raise the volume, issue a TTS and then lower the volume again.

Error: "alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests"
Hass Core version: 0.106.5

Script: https://pastebin.com/esNzvdjL

Are there any way to overcome this issue ?

Best regards
Joe

**Comment by hoddi78** [comment] 2020-03-27 23:13
I had this as well on alexa_media_player 2.5.8 when calling more than once to Alexa in one script or automation. I rolled back to 2.5.4 and no issues running those automation now.

**Comment by alandtse** [comment] 2020-03-28 00:46
Please fill out the template.

**Comment by JoeTN** [comment] 2020-03-28 09:55
**Describe the bug**
I'm getting the "Too Many Requests"-error when using this script https://pastebin.com/esNzvdjL. The idea is to first raise the volume, issue a TTS and then lower the volume again.

**To Reproduce**
Run the script above, or something similar.

**Expected behavior**
I expected no "Too Many Requests"-errors.

**System details**
Home-assistant (version): Core-edition, 0.106.5
Hassio (Yes/No): No
alexapy after an update. This looks like a HA bug). No
alexa_media (version from const.py or HA startup): 2.5.8
alexapy (version from pip show alexapy or HA startup): 1.5.2

**Logs**

> 2020-03-27 20:56:07 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall script.doorbell_alexa_say (c:6eb772ef606e429b870cc11511691246)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1238, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 207, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 288, in async_turn_on
    raise err
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 283, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 198, in async_send_message
    await asyncio.gather(*tasks)
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 1015, in async_send_announcement
    message, customer_id=self._customer_id, **kwargs
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 519, in send_announcement
    skillId="amzn1.ask.1p.routines.messaging",
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 296, in send_sequence
    await self.run_behavior(node_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 247, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 118, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 111, in _request
    raise AlexapyTooManyRequestsError(response.reason)
alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests

**Comment by alandtse** [comment] 2020-03-28 11:01
Please enable alexapy debug logs. It should be queuing the multiple requests so it only issues a single command.

**Comment by JoeTN** [comment] 2020-03-28 11:24
How do I enable the debug logs?

**Comment by alandtse** [comment] 2020-03-28 19:42
The template has a link to the FAQ which says how to do it.

**Comment by jrnhrmn** [comment] 2020-03-30 18:27
I can confirm tho a one second delay between commands seems to fix this. Used to work before but I am fine with that. I use it in Node Red and had the same issue.

**Comment by laca75tn** [comment] 2020-03-30 21:28
I can also confirm that if you add a delay of 1 second between commands it solves the problem.

**Comment by SeanPM5** [comment] 2020-04-02 16:43
I had this issue too, for me it seemed to be caused by having the `media_player.volume_set` service right before a TTS.

This was my automation that was giving the "too many requests" error in log and failing (since v2.5.7 I believe - before that it worked fine). Once I commented out the volume_set part it continues to works fine like before. 

```
    action:

      # - service: media_player.volume_set
      #   entity_id: media_player.echo_3g
      #   data:
      #     volume_level: '1.0'

      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: 
            - media_player.echo_3g
            - media_player.kitchen_echo_dot
          message: "Hallway door opened."
```

**Comment by jrnhrmn** [comment] 2020-04-02 16:51
> I had this issue too, for me it seemed to be caused by having the `media_player.volume_set` service right before a TTS.
> 
> This was my automation that was giving the "too many requests" error in log and failing (since v2.5.7 I believe - before that it worked fine). Once I commented out the volume_set part it continues to works fine like before.
> 
> ```
>     action:
> 
>       # - service: media_player.volume_set
>       #   entity_id: media_player.echo_3g
>       #   data:
>       #     volume_level: '1.0'
> 
>       - service: notify.alexa_media
>         data:
>           data:
>             type: tts
>           target: 
>             - media_player.echo_3g
>             - media_player.kitchen_echo_dot
>           message: "Hallway door opened."
> ```

Same here

**Comment by laca75tn** [comment] 2020-04-02 17:03
If you add a 1 second delay after setting the volume (between service calls) then it will work 
    On Thursday, April 2, 2020, 12:44:14 PM EDT, Sean Mooney <notifications@github.com> wrote:  
 
 


I had this issue too, for me it seemed to be caused by having the media_player.volume_set service right before a TTS.

This was my automation that was giving the "too many requests" error in log and failing (since v2.5.7 I believe - before that it worked fine). Once I commented out the volume_set part it continues to works fine like before.
    action:

      # - service: media_player.volume_set
      #   entity_id: media_player.echo_3g
      #   data:
      #     volume_level: '1.0'

      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: 
            - media_player.echo_3g
            - media_player.kitchen_echo_dot
          message: "Hallway door opened."

**Comment by laca75tn** [comment] 2020-04-02 17:04
Add a one second delay between service calls and then it will work.  
    On Thursday, April 2, 2020, 12:52:07 PM EDT, jrnhrmn <notifications@github.com> wrote:  
 
 



I had this issue too, for me it seemed to be caused by having the media_player.volume_set service right before a TTS.

This was my automation that was giving the "too many requests" error in log and failing (since v2.5.7 I believe - before that it worked fine). Once I commented out the volume_set part it continues to works fine like before.
    action:

      # - service: media_player.volume_set
      #   entity_id: media_player.echo_3g
      #   data:
      #     volume_level: '1.0'

      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: 
            - media_player.echo_3g
            - media_player.kitchen_echo_dot
          message: "Hallway door opened."


Same here

**Comment by DKAutomater** [comment] 2020-04-06 12:49
How will the delay of 1 second look like in the automation?

**Comment by laca75tn** [comment] 2020-04-06 12:57
- service: media_player.volume_set    data:       entity_id: media_player.dot_master      volume_level: 0.5    - delay: '00:00:02'    - service: media_player.play_media    entity_id: media_player.dot_master    data:      media_content_id: 'Sounds of nature white noise sound effects' #Gentle Birds and Forest Stream for Relaxation Meditation' #Bee-Eater: Calls in Cave      media_content_type: 'AMAZON_MUSIC'

I hope this helps.
Thanks

    On Monday, April 6, 2020, 08:49:29 AM EDT, DKAutomater <notifications@github.com> wrote:  
 
 


How will the delay of 1 second look like in the automation?

**Comment by aureliosaraiva** [comment] 2020-04-23 22:50
I too was received this error, I put a delay of 0.5s

**Comment by jrnhrmn** [comment] 2020-05-02 08:01
Looks like it's a feature now https://github.com/custom-components/alexa_media_player/commit/1e8881cfebf561dc4954d11f9a4003977936d380

**Comment by alandtse** [comment] 2020-05-02 08:45
Please note the [queue delay option](https://github.com/custom-components/alexa_media_player/wiki/Configuration#queue-delay-versions--260) is a different solution then adding delays to commands in scripts. You can try tweaking both.

**Comment by alandtse** [comment] 2020-05-15 03:34
I'll close this issue since we have multiple ways to resolve it.

**Closed by alandtse** 2020-05-15 03:34 UTC
