### ISSUE TITLE
Have to reauthenticate after restart

### ISSUE THREAD

**Issue by heffneil** [custom-components/alexa_media_player#1632] opened 2022-06-08 01:21 UTC
Every time I restart HA it is asking me to re-authenticate.  

**To Reproduce**
Stop HA and go to integrations and you will see the integration tile that says attention required.

**System details**
 - Home-assistant (version): 2022.6.2
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled]Y
 - 
*Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py:706
First occurred: 2:09:31 PM (1 occurrences)
Last logged: 2:09:31 PM

No access token found; falling back to credential login instead of oauth

**Comment by alandtse** [comment] 2022-06-08 06:02
Yes, that's by design in 4.0.x if you don't have an oauth login. Remove and readd or downgrade.

**Comment by alandtse** [comment] 2022-06-08 06:03
Dupe of #1622

**Closed by alandtse** 2022-06-08 06:03 UTC

**Comment by heffneil** [comment] 2022-06-08 11:50
ok - Im pretty sure I am using Oauth but what do I know.

**Comment by heffneil** [comment] 2022-06-08 11:55
I removed the references to alexa_media and the username and password in my configuration.yaml and after a restart, it appears as if I am still logged in properly FYI.  Some other people recommended this in similar discussions. Thanks!
