### ISSUE TITLE
"Open Website" for Configuration Generates Secure Connection Failed

### ISSUE THREAD

**Issue by usedjeans818** [custom-components/alexa_media_player#1167] opened 2021-02-06 08:27 UTC
**Describe the bug**
When first configuring the Integration, I can complete the configuration page, but after confirming that the OTP is entered on the 2FV page for Amazon, the Open Website page that pops-up, generates a Secure Connection Failed error.

**To Reproduce**
1. Add the integration to Home Assistant
2. Enter all relevant information (using Built-in 2FA App Key Mode, Login Proxy, and OAUTH)
3. Enter the OTP code into the Amazon Two-Step Verification page
4. Confirm that the code has been entered and hit the Submit button in Home Assistant
(The Amazon 2FA page registers that a new 2FA device was successfully added.)
5. The webpage that pops-up generates a Secure Connection Failed error in the web browser
6. The URL that is generated seems to be requesting a TCP port (this TCP port changes each time I retry configuring the Integration):
```
https://homeassistant.****.net:58369//?config_flow_id=a90ffa14b6524d589b96eb7fdc66e0b2&callback_url=https://homeassistant.****.net:3185//auth/alexamedia/callback?flow_id=a90ffa14b6524d589b96eb7fdc66e0b2
```
(The https://homeassistant.****.net:3185 URL/port is publicly accessible and has a valid SSL certificate installed.)

**Expected behavior**
I've done this a couple of months ago on another Home Assistant device, and I expect the configuration to complete and then display the available devices (Echo Dots).

**Screenshots**
![configuration](https://user-images.githubusercontent.com/74646319/107112855-a3647500-680f-11eb-9573-1ccb0066d720.jpg)

![open_website](https://user-images.githubusercontent.com/74646319/107112864-abbcb000-680f-11eb-8d69-9d5dd64f1a7e.jpg)

**System details**
 - Home-assistant (version): core-2021.2.1
 - Hassio (Yes/No): Yes: Home Assistant OS 5.10
 - alexa_media  (version from `const.py` or HA startup): Newest version from HACS repository as of Feb. 6, 2021
 - alexapy (version from `pip show alexapy` or HA startup): Newest version from HACS repository as of Feb. 6, 2021
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I somehow suspect there is an issue with the URL that is generated after the configuration page.  The URL
```
https://homeassistant.****.net:58369//?config_flow_id=a90ffa14b6524d589b96eb7fdc66e0b2&callback_url=https://homeassistant.****.net:3185//auth/alexamedia/callback?flow_id=a90ffa14b6524d589b96eb7fdc66e0b2
```
is pointing to a TCP port of 58369, which is not publicly available.  However, if I open that port on my router to point to the Home Assistant private IP, it still does not work.  I've tried pointing that external port on the router to 192.168.1.XX:58369 as well as 192.168.1.XX:8123.  That port changes each time I try adding the Integration.  I've tried this on two different browsers (Firefox and Chrome) and have run into the same results. As mentioned above, the https://homeassistant.****.net:3185 URL/port is publicly accessible and has a valid SSL certificate installed.

**Comment by alandtse** [comment] 2021-02-06 08:50
Please use an internal url. Don't open your firewall to the port because it's randomly generated. Dupe of #1156. 

Of course if you're insistent that you need an external URL, I'll see if I can spend some time debugging it but it won't be for a while as I need to strip out the underlying proxy in the next version and use a new library I created to solve other oauth issues HA is having.

**Comment by usedjeans818** [comment] 2021-02-06 08:52
I just saw [https://github.com/custom-components/alexa_media_player/issues/1156](url), which mentions using a local IP.  I had also tried that and received an error.

![local_ip](https://user-images.githubusercontent.com/74646319/107113715-8f237680-6815-11eb-9818-8ce5292c189d.jpg)

**Comment by alandtse** [comment] 2021-02-06 08:53
I'll leave it open for now.  One thought is the SSL cert won't work as it's starting a new server without any ssl_context. It's not borrowing the HA one.

The error you just posted is because it is trying to connect to the server. If it's a https cert mismatch you get that error. Can you do an internal http address?

**Comment by usedjeans818** [comment] 2021-02-06 08:57
I switched the URL to http://192.168.1.XX:8123 and received the exact same error as with https.  Issue #1156 mentioned it has an issue with https
>When using the internal URL, the component seems to fail because the certificate isn't valid for the internal hostname.

**Comment by alandtse** [comment] 2021-02-06 09:02
We're overlapping in replies. But you're saying that for the internal http url it gets and error when it tries to open the page? You can open HA at that http address? It literally is doing a get request to whatever HA url it provides and if it can reach it it'll let you go to the next stage where it'll open a random port on that server. Can you access the proxy url on the HA machine itself?

Again https will fail because it's not using the same cert as HA and in most cases the cert won't have the internal IP regardless.

**Comment by usedjeans818** [comment] 2021-02-06 09:04
Opening the URL http://192.168.1.XX:8123/ in my browser doesn't work.  It will only open via https://192.168.1.XX:8123/.

**Comment by usedjeans818** [comment] 2021-02-06 09:08
In case you need it, the relevant configuration.yaml entries are:
```
homeassistant:
  external_url: "https://homeassistant.xxxx.net3185"

http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```
I'm not certain how I can make it respond to http on port 8123 along with https.

**Comment by alandtse** [comment] 2021-02-06 09:13
Ok I need to know when the failure is happening. Is it happening during the check when it gives you the "Unable to connect error"? Or is it failing when it gives you the proxy url?

Also, the way you do an `internal_url` is [here](https://www.home-assistant.io/docs/configuration/basic/). 

So here's what's probably happening.

- https won't work period for the proxy url for the reasons above.
- http is failing because it cannot access your HA instance when it does the test ("Unable to connect").

So solutions are:

- enable http so the test won't fail
- disable login proxy so you don't use the proxy at all.
- wait till I get https support in the proxy (a few days).

**Comment by usedjeans818** [comment] 2021-02-06 09:30
Sorry, when I cleaned the hostname after pasting the text, I misadvertently deleted the colon.  It's there in the yaml file...

However, I did try
```
homeassistant:
  external_url: "https://homeassistant.xxxx.net:3185"
  internal_url: "http://homeassistant.local:8123"

http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```
And I was still not able to access HA on http://homeassistant.local:8123.  I also tried ```internal_url: "http://192.168.1.XX:8123"``` and http://192.168.1.XX:8123 did not work either.

I guess I'll just wait until you can get https support in the proxy working.  I'll keep an eye out on this issue.

**Comment by usedjeans818** [comment] 2021-02-06 10:35
As an FYI, I found this [discussion](https://community.home-assistant.io/t/0-110-is-internal-url-useless-when-https-enabled/198209/37).  According to that, if ```ssl_``` is defined, http:// will not work.

**Comment by honky-bear** [comment] 2021-02-06 11:52
I've been having similar issues and spent several hours trying to resolve.
Here is an explanation and what I've done that gets around this issue (but I've then got a further issue!).

This component needs the Internal URL configured in the dialog box.  If you have SSL configured, as you have above, it will not work.  This is because the component checks the URL in the SSL certificate against the URL it is using to access.  They will be different.  Because your SSL certificate will likely have your External URL in it.  And you cannot include your Internal URL because Certificate Authorities won't allow that.

So, if you want to use SSL, you need to install the NGINX reverse proxy.  You can do this from the Add-on store in HAAS.  Th only config I changed from default was my domain name.

What you then need to do, is disable SSL in your configuration.yaml.  You should now be access HomeAssistant using HTTP internally on http://homeassistant.local:8123.  This hits home assistant directly.

With NGINX up and running, you will probably also need to change your Firewall port forwarding rule.  Prior to these changes you will have mapped port 443 to port 8123 on your home assistant.  You now need to just map port 443 to port 443 on your home assistant.  Your external URL should now work.

Last problem I had, is that my home assistant box couldn't resolve "homeassistant.local".  So for the internal URL in the Alexa dialog box, I just put http://homeassistant:8123.

I now get to the next screen.  Can enter my username and password.  Get past that ok.  But the next screen says that I need to change my password and that I need to send an OTP, but when I click the button get an Amazon error page.  

Hopefully you'll be luckier!

**Comment by usedjeans818** [comment] 2021-02-06 23:45
@alandtse, I followed @honky-bear's instructions (thank you, @honky-bear!) and adding the integration finally completed past the Amazon / Alexa logon page.  However, it never asked me to confirm the Echo devices that I wanted to include.  Also, it doesn't show any devices or entities on the Integrations page:

![Screenshot_2021-02-06 Configuration - Home Assistant](https://user-images.githubusercontent.com/74646319/107132174-9d16dd00-6891-11eb-83eb-0ba2c7b3213f.png)

Did I do something wrong?  When I typed in the name of the Echo devices, I used:
```
hallway,kitchen,living room,master bedroom
```
Quick note, I am setting this up for my parents, but I am currently at my own home.  Does the Home Assistant Raspberry Pi need to be on the local subnet for this to work?  Or, should it work remotely as well?

**Comment by alandtse** [comment] 2021-02-06 23:48
> Did I do something wrong? When I typed in the name of the Echo devices, I used:
> 
> ```
> hallway,kitchen,living room,master bedroom
> ```
> 
> Quick note, I am setting this up for my parents, but I am currently at my own home. Does the Home Assistant Raspberry Pi need to be on the local subnet for this to work? Or, should it work remotely as well?

Are you sure those devices exist? Try without include_devices to see what is on the account. Also, make sure the domain matches the account. You'll get a warning in your logs if it doesn't. The devices are fetched from Amazon so it doesn't care where the component is.

**Comment by usedjeans818** [comment] 2021-02-06 23:58
Yes, please see the URL I used to discover the names:

![url](https://user-images.githubusercontent.com/74646319/107132397-81143b00-6893-11eb-8166-7af9807f9426.jpg)

And the names listed on that page:

![echo_devices](https://user-images.githubusercontent.com/74646319/107132400-8c676680-6893-11eb-8fc9-91074a3ee02b.jpg)

I don't actually have any configurations in configuration.yaml.  Should I add this?
```
alexa_media:
  accounts:
  - email: xxxx@gmail.com
    password: xxxxxxxx
    url: amazon.com
    include_devices:
      - hallway
      - kitchen
      - "living room"
      - "master bedroom"
```
And then restart Home Assistant?

Does capitalization/case matter?

**Comment by alandtse** [comment] 2021-02-07 00:18
Don't use configuration.yaml. Just don't use include_devices. It's an allow list.

**Comment by usedjeans818** [comment] 2021-02-07 00:30
It's weird, after I added the configuration above, the devices showed up in Lovelace, but still did not show on the Integrations page.  After your response, I commented out the configuration, restarted Home Assistant, and the devices are still in Lovelace and the devices/entities are now on the Integrations page.  I'll monitor it, but it looks like the integration is working (I successfully pushed a couple of announcements to the Echo devices).

Thanks for your assistance and quick responses @alandtse!

**Comment by GIJ0E** [comment] 2021-02-07 03:31
> But the next screen says that I need to change my password and that I need to send an OTP, but when I click the button get an Amazon error page.

I had the same problem today. It was trying to get me to send an OTP to either my email or text but it would give me an amazon error page.
After a bit of googling it I finally found a page that helped.
I had to do the OTP outside of home assistant. Then when I went back to add the alexa integration, it worked without the OTP.

Here's the link I found, when I clicked on "Your Orders" on that page, it asked me to complete the OTP and I had to change my password.

[https://www.amazon.com/gp/help/customer/display.html?nodeId=GXHYX22CS752PLE3](url)

Hopefully that works for someone else.

**Closed** 2021-02-07 07:13 UTC
Labels: duplicate
