### ISSUE TITLE
Connection Error -[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by memphi2** [custom-components/alexa_media_player#1793] opened 2022-12-07 20:08 UTC
**Describe the bug**
I had installed the Alexa Media Player yesterday. Everything was working fine. Today after a reboot I noticed that there was a login problem with the integration. So I removed it and tried to reinstall. After the integration page I get the following error:

Connection Error! Please try refreshing. If this persists, please report this error to here:

[Errno -2] Name does not resolve

**To Reproduce**
1. Go to 'The Integrations Page'
2. Click on 'Submit.'
3. See error

**Expected behavior**
OTP code request

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8568398/206283538-61f28643-b920-492c-ad4a-662c1c9c0b89.png)

**System details**
 - Home-assistant (version): 2022.11.5 
 - alexa_media  (version from `const.py` or HA startup): 4.3.2
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  y

**Logs**

**Additional context**
can be closed, problem no longer occurs today

**Comment by alandtse** [comment] 2022-12-10 07:29
The error indicates your DNS wasn't resolving. Glad it self-resolved but this is a network issue.

**Closed by alandtse** 2022-12-10 07:29 UTC

**Comment by Muehli-dev** [comment] 2023-01-31 10:13
Allthough the issue is closed i've wanted to add something to resolve the issue, maybe someone will find it usefull.

I was struggling to add the integration to my HA for about two hours now due to the mentioned error.

I've stumbled accross this thread that helped me to resolve the issue:
https://community.home-assistant.io/t/suddenly-hass-cannot-connect-to-internet-ressources-dns-issue/23931

Just add the Google DNS to your HA DNS via Terminal:

ha dns options --servers dns://8.8.8.8
ha dns restart
