### ISSUE TITLE
Can't run initial setup due to secondary captcha missing

### ISSUE THREAD

**Issue by duhow** [custom-components/alexa_media_player#629] opened 2020-04-06 16:41 UTC
**Describe the bug**
After installing component from HACS, can't finish integration setup.
Been blocked with this error since Home Assistant version 0.106 .

**To Reproduce**
1. Add integration Alexa Media Player
2. Setup for region **amazon.es**
3. Fill captcha
4. Select choice **sms**.
5. A new input window appears with no message, no SMS is received.

**Expected behavior**
Expected to finish setup and have Echo / Alexa media player.

**Screenshots**

**System details**
 - Home-assistant (version): 0.107.7
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.5.11
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

- **Cause for this issue:** Amazon requested for a **secondary** captcha, just after selecting the verification choice (sms/push), tested with manual login with Chrome browser No-JS. Then I could finish the setup in Home Assistant. This assistant was only asking for a **single** captcha.

**Comment by duhow** [comment] 2020-04-06 19:01
Just saw, this seems to duplicate #568 #585

**Comment by alandtse** [comment] 2020-04-07 00:24
Yes, dupe of #568 , work-arounds are in there. Need logs/html pages to do more. 

Thanks for finding the secondary captcha.  I specifically would need to see the html for the secondary captcha you found along with the alexapy logs on how it's getting you to that point. Please update the other thread with that info. While the Chrome browser No-JS html may help, it may not exactly match what the component is seeing. If you can't reproduce it, I'll take the Chrome browser html and see what can be done.

**Closed by alandtse** 2020-04-07 00:24 UTC
Labels: duplicate
