### ISSUE TITLE
Timers not showing correct state until reloading of the integration

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1972] opened 2023-06-26 08:58 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

When I set a timer it no longer changes the state in HA. I have to manually reload the integration. Then when the timer is finished the state used to go back to 'unknow' but now it just shows the timestamp.

This has only happened in the last few updates of HA but I am not sure if its related or not to updating.

**To Reproduce**

1. Restart HA to see if any errors are there - none are shown
3. Start timer on any Alexa device
4. Timer does not change state and shows 'unknown' due to restart:
<img width="527" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/15043282/85149aed-b45b-4121-a789-3aaf650643b1">

5. Wait a few minutes - still no state change
6. Reload integration
7. Timer now shows up:
<img width="563" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/15043282/370fd4fb-95f8-4a8a-9422-556a9ecbb10e">

8. After timer is complete:
<img width="585" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/15043282/55fb3e0a-3423-456d-a068-da60c8d29cf5">

9. 'Unknown' does not come back until restart.

**Expected behavior**

1. Start timer 
2. State updates
3. After timer finishes the state turns to 'unknown'

**Screenshots**

**System details**

- Home-assistant (version): 2023.6.3
- alexa_media (version from `const.py` or HA startup): 4.6.4
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) y. :

**Logs**
Nothing shows up in logs:
<img width="1377" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/15043282/8a9aa945-af0a-422b-83d9-6b76b9580b76">

**Additional context**

**Comment by MrFr33man123** [comment] 2023-06-26 11:40
same as #1971 merge?

**Comment by francescolf** [comment] 2023-06-26 13:02
What's your Amazon region?

**Comment by emufan** [comment] 2023-06-26 13:22
I have this as well. It is completely not updating anymore without reload of the integration. Neither on create, nor on change or delete of the timer.

The last weeks it was somehow unreliable already, but now it stopped updating completely.

**Comment by francescolf** [comment] 2023-06-26 13:32
I'm working on a fix and I suspect it might be domain-related. Could you also tell me what domain you are using?

**Comment by dpgh947** [comment] 2023-06-26 14:34
Same here (I'm in UK). Alexa timers in HA a bit flakey over the past couple of days, not updating at all today despite reloads, reboots etc. Other Alexa communication to HA seems ok.

**Comment by emufan** [comment] 2023-06-26 15:52
> Could you also tell me what domain you are using?

What is the domain in this context. For sure I will provide information needed.

**Comment by emufan** [comment] 2023-06-26 16:12
Ah: amazon.de is it.

**Comment by alandtse** [comment] 2023-06-26 17:20
Dupe of #1971

**Closed by alandtse** 2023-06-26 17:20 UTC
Labels: duplicate

**Comment by oneseventhree** [comment] 2023-06-26 21:39
> What's your Amazon region?

amazon.com.au :)
