### ISSUE TITLE
Integration config does nothing

### ISSUE THREAD

**Issue by ivrlx** [custom-components/alexa_media_player#1744] opened 2022-10-04 11:18 UTC
**Describe the bug**
Trying to configure the integration, when everything is filled up and click submit nothing happens. It should give me a 6 digit code to add built in 2FA but it doesn't.

I've tried using amazon.es and amazon.com as well and is failing anyway.

**To Reproduce**
Just try to config

**Screenshots**
![image](https://user-images.githubusercontent.com/97689935/193804262-895b46a1-d0c1-4d87-8b61-46029ef76307.png)

**System details**
 - Home-assistant (version): 2022.9.7
 - alexa_media: 4.1.2
 - alexapy: 1.26.3
 - Amazon [2FA is enabled] yes

**Comment by tmorse305** [comment] 2022-10-06 15:00
I'm having the same problem.  The only error I see in the log is:
2022-10-06 10:48:42.554 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session

**Comment by dxit** [comment] 2022-10-06 20:21
It looks like a duplicate of #1737

**Closed** 2022-10-09 04:17 UTC
Labels: duplicate
