### ISSUE TITLE
Reauthentication - "All connection attempts failed"

### ISSUE THREAD

**Issue by mcza88** [custom-components/alexa_media_player#1634] opened 2022-06-09 16:49 UTC
After the update due to the dependency error (OS > 2022.6.0)the integration requires re-authentication.
During the re-auth process, after the Amazon Login Page, the error appears (see screenshot).

I can add the app on Amazon, confirm the OTP code, but right after the login it fails.

![alexa_error](https://user-images.githubusercontent.com/65406799/172901098-795e182d-b762-4b74-90fa-b67da51b455f.png)

**HA info**
Version: core-2022.6.4
Installation type: Home Assistant OS
Supervisor:
Host OS: Home Assistant OS 8.1
Update channel: stable
Supervisor Version: supervisor-2022.05.3
Agent version: 1.2.1
Docker version: 20.10.14

**Alexa_Media_Player info**
v.4.0.2

logs coming from 

```
logger:
  default: critical
  logs:
    custom_components.alexa_media: debug  
    alexapy: debug
```

```
2022-06-09 19:03:15 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2022-06-09 19:03:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] ****@**************: Returning uuid {'uuid': 'a793bceb737917c2b7a613ed73ed8765', 'index': 0}
2022-06-09 19:03:15 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for H************************************************RWQ
2022-06-09 19:03:15 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP ******
2022-06-09 19:03:15 DEBUG (MainThread) [alexapy.alexalogin] Login created for ****@*********** - amazon.com
2022-06-09 19:03:16 DEBUG (MainThread) [alexapy.alexalogin] Attempting oauth login to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:323961616661313136376332313735373261633963373265306232383239656623413249564c5635564d32573831&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=en_US
2022-06-09 19:03:16 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 582272
2022-06-09 19:03:16 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 582272
2022-06-09 19:03:16 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 582272
2022-06-09 19:03:16 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Generating OTP from *******
2022-06-09 19:03:30 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Starting proxy for ****@************** - amazon.com
2022-06-09 19:03:35 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found flow_id; adding 192.168.188.254 to known_ips for 300 seconds
2022-06-09 19:03:35 DEBUG (MainThread) [alexapy.alexaproxy] Filled <input autocapitalize="off" autocorrect="off" id="ap_email" maxlength="128" name="email" placeholder="Email or phone number" tabindex="1" type="email" value="****@**************"/>
2022-06-09 19:03:35 DEBUG (MainThread) [alexapy.alexaproxy] Filled <input aria-label="Amazon password" id="ap_password" maxlength="1024" name="password" placeholder="Amazon password" tabindex="2" type="password" value="REDACTED 22 CHARS"/>
2022-06-09 19:03:43 WARNING (MainThread) [custom_components.alexa_media.config_flow] Detected Connection error: All connection attempts failed
```

Please let me know if I can provide you some other info.

Thank You

**Comment by alandtse** [comment] 2022-06-10 06:39
Thanks and regardless of refreshes it doesn't ever change? The reported error is saying it can't connect to Amazon.

**Comment by mcza88** [comment] 2022-06-10 07:18
> Thanks and regardless of refreshes it doesn't ever change? The reported error is saying it can't connect to Amazon.

yes, exactly,  it never changes, regardless the refresh of the page, the browser in use and also trying to change the Amazon destination (.com, .it, etc).

Are you sure that the problem is the connection to Amazon? the URL that fail is

_https://[myHApublicAddress]/auth/alexamedia/proxy/ap/signin_

Thanks

**Comment by alandtse** [comment] 2022-06-10 07:38
Yes. At this point any errors from the proxy are when it's trying to get information from amazon.com.

Do you see any portion of the official Amazon login before this error? What is happening is it will proxy the official amazon login to you so you can sign in and it can intercept your tokens to save your login for later. Prior reports would say it would break after the username and passwords were accepted. 

The `https://[myHApublicAddress]/auth/alexamedia/proxy/ap/signin` address is what your browser should be trying to access because we use the HA url to set up the proxy on your HA instance. If you can see the error message, you are already past the HA authentication. You can get more info about that if you also add logs for `authcaptureproxy`.

**Comment by mcza88** [comment] 2022-06-10 07:55
> Yes. At this point any errors from the proxy are when it's trying to get information from amazon.com.

> Do you see any portion of the official Amazon login before this error? What is happening is it will proxy the official amazon login to you so you can sign in and it can intercept your tokens to save your login for later. Prior reports would say it would break after the username and passwords were accepted.

Yes, I can see the Amazon login page and after submitting the credentials the error comes.
![alexa_login](https://user-images.githubusercontent.com/65406799/173016073-e909382b-852b-4b76-969b-8ccffc62f3a5.png)

 
> The `https://[myHApublicAddress]/auth/alexamedia/proxy/ap/signin` address is what your browser should be trying to access because we use the HA url to set up the proxy on your HA instance. If you can see the error message, you are already past the HA authentication. You can get more info about that if you also add logs for `authcaptureproxy`.

Ok, I'll try to add that debug. 
Just wondering why I'm getting an  invalid authentication from my router.

**Comment by alandtse** [comment] 2022-06-10 08:52
If you try an internal IP for the HA url, does it change anything? I don' think it's related since you can see the page, but who knows.

**Comment by mcza88** [comment] 2022-06-10 08:58
I was trying to understand the auth path and I saw that in the network trace there is an error:

```
URL: https://[myHApublicIP]/ap/uedata?ld&v=0.221671.0&id=[******************]|fls-na-amazon-com|adblk_no|csm-feature-touch enabled:false&viz=visible:4&pty=AuthenticationPortal&spty=MobileSignInApplication&pti=undefined&tid=**********=1&ui=2
Stato: 404
Sorgente: Service Worker
```

looking at the proxy variables I see

```
        var ue_id = '***************',
            ue_url = '/ap/uedata',
            ue_navtiming = 1,
            ue_mid = '*****************',
            ue_sid = '1***************',
            **ue_sn = 'www.amazon.com',**
            **ue_furl = 'fls-na.amazon.com',**
            **ue_surl = 'https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.prod',**
            ue_int = 0,
            ue_fcsn = 1,
            ue_urt = 3,
            ue_rpl_ns = 'cel-rpl',
            ue_ddq = 1,
            ue_fpf = '**//fls-na.amazon.com**/1/batch/1/OP/******************$uedata=s:',
            ue_sbuimp = 1,
            ue_ibft = 0,
            ue_fnt = 0,
```

Is it ok to have amazon **.com** even if I'm authenticating the app with amazon **.it** ?

**Comment by alandtse** [comment] 2022-06-10 09:08
Yes. The way the oauth login works is that you get initial tokens from amazon.com and then trade them in for your specific domain, amazon.it.

So to explain a bit more, the authcaptureproxy is looking for a certain [website condition](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaproxy.py#L64-68) (the urls "/ap/maplanding" or "/spa/index.html") to indicate success before it will save the tokens. If for some reason the success test fails, all bets are off since it will continue to proxy your connection to Amazon and it's not designed to go any farther then the initial login pages.  If you enable the authcaptureproxy log, take a look at what it's trying to do after your last successful submission.

**Comment by alandtse** [comment] 2022-06-10 09:25
Hmmm. Perhaps your router is blocking something resulting in a timeout. Odd. But regardless, I'm glad it worked for you.

I'll go ahed and close this out since you're good. If you ever feel like testing why the internal works and external doesn't, take a look at the logs and see if you can see where the external breaks in comparison. That may be able to help me figure out what went wrong. But no biggie if you either don't want to or the logs are too complicated for you.

**Closed by alandtse** 2022-06-10 09:25 UTC

**Comment by mcza88** [comment] 2022-06-10 11:39
I'm back with some logs.

Here you can find
[alexa_external.log](https://github.com/custom-components/alexa_media_player/files/8878291/alexa_external.log)
[alexa_internal.log](https://github.com/custom-components/alexa_media_player/files/8878400/alexa_internal.log)


I masked and/or randomly changed all sensitive data (accounts, hashes, ids, tokens) so don't rely on this info.

From a first view, and from what I can undstrand, I found some differences:

1. During external registration the component adds the internal IP of my router to known_ips, while in the internal it adds the IP of my PC.

`2022-06-10 11:58:23 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found flow_id; adding 192.168.188.254 to known_ips for 300 seconds`

`2022-06-10 11:50:09 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found flow_id; adding 192.168.188.33 to known_ips for 300 seconds`

2. During external registration there is a GET with HTTP for the external URL and HTTPS as variable, then authcaptureproxy detects it and switches to HTTPS

```
2022-06-10 11:58:23 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Received get: http://[EXTERNAL_HA_URL]/auth/alexamedia/proxy?config_flow_id=95c1342423a8fbb93&callback_url=https://[EXTERNAL_HA_URL]/auth/alexamedia/callback?flow_id%3D95c124244f0a8fbb93 for https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:346334234234863633734333166653063623623413249564c5635564d32573831&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=it_IT
2022-06-10 11:58:23 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Detected http while should be https; switching to https
```

3. Lastly the external registration shows a 'Connection Close' Final header, while the internal at the same stage gets an 'Accept'

`2022-06-10 11:58:23 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Final headers {'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15', 'Accept-Language': 'it-it', 'Referer': 'https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:3463321345643666464653238623863633734333166653063623623413249564c5635564d32573831&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=it_IT'}`

`2022-06-10 11:50:09 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Final headers {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15', 'Accept-Language': 'it-it', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive'}`
 

Please let me know if you need some additional test.

**Comment by mcza88** [comment] 2022-06-10 12:42
Hi again! 

I'm having some issue also with internal URL now.

I can reach the Amazon login page, submit the credentials and also submit the OTP, but right after I'm facing a strange behavior: the browser returns a '401: unauthorized' while the integration says "Alexa Media Player has been successfully authenticated" (see screenshot of the two web pages side by side)
![new_error](https://user-images.githubusercontent.com/65406799/173066385-2de27331-fc19-439f-86f8-949b507f85b7.png)

I faced the issue while trying to configure for the last time the integration, after the test that I made for log collection.
During the tests I did some registration without any problems using the internal URL

**Comment by alandtse** [comment] 2022-06-10 17:19
Oh thanks for doing that. Let me digest this.

The 401 can happen because I have a very aggressive algorithm that blocks access to the http view 5 minutes after the last successful access and also immediately after success. This is because I can't disable the proxy without restarting HA. In theory it shouldn't impact the login in the second case which is what I think you saw.

**Comment by alandtse** [comment] 2022-06-18 04:07
Thanks. I finally had a chance to look at this. The issue is there's an attempt to post the results back to the Proxy. This results in an infinite loop as the proxy will keep trying to post to itself. You will note that any "Attempting `get/post`" should hit the amazon server and never the HA server.  

It's been a while since I worked on authcaptureproxy but if I do make changes, would you be able to help me test it? It may happen over a couple of weeks since I'm not focusing on this project as much.

**Comment by alandtse** [comment] 2022-06-18 07:24
If you're comfortable testing, I believe the issue could be resolved using this version of authcaptureproxy.

This will install a copy into your `/config` directory which allows you to delete it to go back to your system copy.
```bash
pip3 install --target /config --no-dependencies git+https://github.com/alandtse/auth_capture_proxy.git@http_upgrade
```

Alternatively, you can make the manual edits to the [auth_capture_proxy.py](https://github.com/alandtse/auth_capture_proxy/commit/2b672fa3a9c86ecf4dd64d7fc7d66a8a7fa1d5ff#diff-f712316debfe4075a6fd6dbc6580598ccc2fc5d55730b8395334f7fafb9e4388) file.
