### ISSUE TITLE
Unable to re-try to solve captcha

### ISSUE THREAD

**Issue by kmycek** [custom-components/alexa_media_player#890] opened 2020-08-27 15:25 UTC
**Describe the bug**
Due to bug #888, I am now unable to try to solve the captcha. Now I receive "Please hit confirm to begin login attempt. Forgot password page detected; Amazon has detected too many failed logins. Please check to see if Amazon requires any further action. You may have to wait before retrying.", with a CONFIRM button. It's been over 12 hours now, and I still can't dismiss this warning (even though I am able to successfully log out and back into Amazon). My account is not locked out, there is nothing in the HA logs (other than this same error msg above).

**To Reproduce**
Fail captcha 5-6 times. 

**Expected behavior**
After a reasonable time period, or a successful relogin to Amazon, I should be given the captcha to solve again. I am not.

**Screenshots**

**System details**
 - Home-assistant (version): 0.114.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.10.4
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by guilhermelirio** [comment] 2020-08-28 01:11
I managed to solve the problem:

1) Enter the site and activate 2FA via SMS.
2) Go to HA under Configurations> Integrations and click in + button.
3) Select Alexa Media Player, and enter your login and password.
4) Solve the captcha, and then ask for the 2FA code.
5) Enter the code and the configuration will finish

**Comment by alandtse** [comment] 2020-08-28 03:06
Dupe of #807

**Comment by ramdisk00** [comment] 2020-08-28 09:56
> I managed to solve the problem:
> 
> 1. Enter the site and activate 2FA via SMS.
> 2. Go to HA under Configurations> Integrations and click in + button.
> 3. Select Alexa Media Player, and enter your login and password.
> 4. Solve the captcha, and then ask for the 2FA code.
> 5. Enter the code and the configuration will finish

can you please explane what site your are talking about in item #1 
I have the same issue as mention above and would love to solve it, thanks

**Comment by alandtse** [comment] 2020-08-28 10:14
Please provide logs.

**Comment by guilhermelirio** [comment] 2020-08-28 11:06
> can you please explain what site your are talking about in item #1
> I have the same issue as mention above and would love to solve it, thanks

Sorry. Amazon website (https://www.amazon.com).

**Comment by exKAjFASH** [comment] 2020-08-28 12:49
+1 Solved using @guilhermelirio  steps

**Comment by alandtse** [comment] 2020-08-29 06:34
2.10.5 includes a fix to allow you to restart the login process after seeing the forgot password screen. All other comments are off-topic.

**Closed by alandtse** 2020-08-29 06:34 UTC

**Comment by coom** [comment] 2021-01-04 16:24
> 2.10.5 includes a fix to allow you to restart the login process after seeing the forgot password screen. All other comments are off-topic.

Hi

I have the same issue and when I loggin there is no option to restart the login process..
