### ISSUE TITLE
Integration looks for input after logging in

### ISSUE THREAD

**Issue by Arsenal10108** [custom-components/alexa_media_player#887] opened 2020-08-26 22:26 UTC
Trying to log in for the first time. It displays the window with the username/password and captcha. I enter the captcha and hit next. It asks me what I want to do for 2fa auth. Only one that works is the push notification to my Android. I yes it was me trying to log in but then Alexa media player come to a window where it's looking for input? Almost like a OTP or something but I don't know what to enter there.

**Comment by asifma** [comment] 2020-08-27 00:56
Same problem here. Captcha is not working...

**Comment by armandomuassab** [comment] 2020-08-27 02:56
same problem here....send sms with link to cellphone, click that...but in home assistant dont finalize

**Comment by alandtse** [comment] 2020-08-27 03:38
Dupe of #807

**Closed by alandtse** 2020-08-27 03:38 UTC
Labels: duplicate
