### ISSUE TITLE
Unable to pass captcha: 3.4.4

### ISSUE THREAD

**Issue by mcc05** [custom-components/alexa_media_player#1075] opened 2021-01-01 13:08 UTC
**Describe the bug**
on 3.4.4 i am no longer able to authenticate to amazon.
deleted the integration and started from scratch. entered email, password and submit capcha challenge comes back (normally I would get a 2fa txt request) enter different capcha challenges multiple times and eventually fails and states, forgotten password detected.
domain is amazon.co.uk

**System details**
 - Home-assistant (version): 2020-12-1
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): yes
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by tthk** [comment] 2021-01-01 13:13
Same here to amazon.com, 2FA enabled.

**Comment by salvasacie** [comment] 2021-01-01 13:29
Same here to amazon.es

**Comment by MrDuck78** [comment] 2021-01-01 13:51
Hi, same here too for amazon.fr .

**Comment by Robjgt** [comment] 2021-01-01 14:12
same amazon.uk

**Comment by Jan1503** [comment] 2021-01-01 14:15
you may guess it...amazon.de fails, too.

**Comment by gforment** [comment] 2021-01-01 14:47
also amazon.it

**Comment by blamaz** [comment] 2021-01-01 15:00
same here amazon.ca

**Comment by poudenes** [comment] 2021-01-01 15:17
Same issue alexa.amazon.co.uk

**Comment by Giac0mo385** [comment] 2021-01-01 15:51
anche amazon.it

**Comment by jn3va** [comment] 2021-01-01 16:19
Same here.  2FA established fine - got the confirm code from the integration and Amazon added it as an app, but the next page with the Captcha just cycles.  I tried leaving the captcha blank, using a captcha from my phone app, etc but just repeats the Captcha and eventfully fails with the too many failed attempts notice.  When we retry this do we need to add as an authenticator app again?

**Comment by rico0260** [comment] 2021-01-01 16:49
Same problem for me, after a simple restoration in version 3.4.2, all work again correctly (the last corrections therefore do not seem effective).

**Comment by poudenes** [comment] 2021-01-01 17:18
> Same problem for me, after a simple restoration in version 3.4.2, all work again correctly (the last corrections therefore do not seem effective).

This revert option didn't work for me.. have to wait for a fix

**Comment by poudenes** [comment] 2021-01-01 17:27
Try revert back to older version now i get this error all the time:

`Amazon will send a push notification per the below message. Please completely respond before continuing. `

Never seen a notification, can login at the website, receive 2way token. What to do???

**Comment by paoloantinori** [comment] 2021-01-01 17:32
I'm facing the same issue as @poudenes on amazon.it, after reverting to `3.4.2`

**Comment by poudenes** [comment] 2021-01-01 17:46
> I'm facing the same issue as @poudenes on amazon.it, after reverting to `3.4.2`

I removed the intergration, removed it from HACS. Reboot HA.
Add in HACS, reboot HA, add intergration and still the message pop up....

**Comment by rico0260** [comment] 2021-01-01 17:53
Small clarification, after going back to 3.4.2, I stopped the system and then restarted it (because I had a problem which had nothing to do with and which was the no restart of the zwave network).

**Comment by beamsplitter** [comment] 2021-01-01 18:54
Same issue here

**Comment by poudenes** [comment] 2021-01-01 19:01
i only mentioned it... This must be opened... not closed!

**Comment by nandox1** [comment] 2021-01-01 19:37
Here to, Amazon.it can't login, downgraded to 3.4.2 but gives me a popup tha amazon will send a notification...but stuck...

**Comment by Duke-Box** [comment] 2021-01-01 20:13
Same here. Amazon.co.uk
Broken integration.
But not using 2FA
Issue is the same though - Captcha causing authentication issues and eventually aborts with error.
But can login to Amazon ok with existing password so error message is rubbish.
Reverted back to 3.4.1 - all ok!

**Comment by yadavvineet** [comment] 2021-01-01 20:29
can confirm same is not working for amazon.in as well

**Comment by jpreiditsch** [comment] 2021-01-01 20:34
Stopped working with Amazon.ca

**Comment by yadavvineet** [comment] 2021-01-01 20:41
this issue is linked to #1066 and both of them are marked as duplicate and closed. 
Is anybody looking, i am getting a feeling that both are closed and is misses out

**Comment by Duke-Box** [comment] 2021-01-01 20:45
Also this issue which I have noted has been closed as well!
New login access will reset password on amazon !!
#1053
But it describes exactly the problem I have been having as well.
I even contacted Amazon help and was told one of my devices was failing to login properly and hence my account being reset.
I think these 2 issues are linked as attempting to fix authentication problems (in my opinion there was none) has caused problems.

**Comment by mcc05** [comment] 2021-01-01 20:45
its showing as open to me??

**Comment by yadavvineet** [comment] 2021-01-01 20:46
> its showing as open to me??

might be some glitch. i see it open as well now

**Comment by yadavvineet** [comment] 2021-01-01 20:55
> Same here. Amazon.co.uk
> Broken integration.
> But not using 2FA
> Issue is the same though - Captcha causing authentication issues and eventually aborts with error.
> But can login to Amazon ok with existing password so error message is rubbish.
> Reverted back to 3.4.1 - all ok!

Can confirm, reverted back to 3.4.1 worked like charm

**Comment by paoloantinori** [comment] 2021-01-01 21:16
Yup, took me a couple of restarts but `3.4.1` still works on `amazon.it`

**Comment by alandtse** [comment] 2021-01-01 21:16
Revert to 3.4.1 if you have issues as that has the older login system. Also, the me toos doesn't help without someone providing logs.

**Comment by mcc05** [comment] 2021-01-01 21:20
@alandtse ,apologies I am away from my installation at present otherwise I would have provided.

**Comment by jjanderson** [comment] 2021-01-01 21:25
I would have thought that the initial logs would have been the same pretty much in all the “mee too’s” who have experienced the same experience. The number of “mee too’s” obviously pointing to the fact that this is actually a bug and not just 1 guy, who in your eyes, may be pebcak... sorry, i was about to “mee too” but then saw your post and without current access to the logs am not going to, but the rollback solution looks lime a fix, so thanks for posting that fix and for the awesome component... 👍

**Comment by alandtse** [comment] 2021-01-01 21:40
@jjanderson If there were initial logs than yes, I would use them but I don't see any logs.
Actually I don't need logs as I can reproduce it. Your options for now are:

1. Revert to 3.4.1.
2. Use the built in 2FA authenticator as it appears to bypass the captcha.

**Comment by nandox1** [comment] 2021-01-01 21:42
Update, as other I reverted back to 3.4.1 and all work again, inserting
name, password and 2FA authentication.

Il giorno ven 1 gen 2021 alle 22:40 Alan Tse <notifications@github.com> ha
scritto:

**Comment by sagitt** [comment] 2021-01-01 22:00
same here

**Comment by Giac0mo385** [comment] 2021-01-01 22:12
idem 3.4.1 is ok

**Comment by jn3va** [comment] 2021-01-01 22:18
I'm just getting started with this and this is my first install.  Can anyone post a link to instructions on how to rollback or access the 3.4.1 version?    For the logs do we just paste it in the comments or is there a way to attach a file?

**Comment by yadavvineet** [comment] 2021-01-01 22:29
click on install or reinstall as the case may be in hacs. a popup will come. Change the version from 3.4.4 to 3.4.1 
restart home assistant, other steps to configure remain same

**Comment by datascope11** [comment] 2021-01-01 22:43
Same issue. Started after updating the component in HACS. Drove me nuts. Rolled back to 3.4.1 and all is good. Love that the captcha in 3.4.4 is easier to read, but it doesn't work.

**Comment by rcojr** [comment] 2021-01-01 22:58
Same here o amazon.com.br, reverted back to 3.4.1 and got it working again

**Comment by scacace** [comment] 2021-01-02 02:58
Same issue and loop on US  amazon.com.  Downgrading as others suggest as resolution for now.

**Comment by Trev-W** [comment] 2021-01-02 03:53
3.4.4 produces this error `Logger: homeassistant.setup
Source: setup.py:138
First occurred: 11:47:16 (1 occurrences)
Last logged: 11:47:16

Setup failed for alexa_media: Integration not found.`

will revert back to 3.4.1

**Comment by poudenes** [comment] 2021-01-02 07:14
Revert back to 3.4.1 and whole proces went ok. Running again.

**Comment by albertomitrani** [comment] 2021-01-02 08:12
No way to login to amazon.it

**Comment by herveaurel** [comment] 2021-01-02 08:13
I have to be 3.4.1 and I no longer have versions up to 3.4.4, normal?  And everything is offline anyway!  :(

**Comment by alandtse** [comment] 2021-01-02 09:19
I took 3.4.2-.4 down until I have it fixed.

**Closed** 2021-01-02 09:37 UTC
Labels: alexapy, bug

**Comment by mcc05** [comment] 2021-01-02 13:57
Thank you!!!

**Comment by albertomitrani** [comment] 2021-01-02 16:00
Thank You!

**Comment by rcojr** [comment] 2021-01-02 19:45
I have updated to 3.4.5 and can confirm it's working now! Thanks!

**Comment by scacace** [comment] 2021-01-02 23:39
My automations for reporting sensors, using the example scripts and most notably the last active alexa device are no longer working.  Still trouble shooting.. but even with the last alexa manually set via developer tools, no replys.. When the brightness settings are marginally off, I would at least get a unknown verbal by alexa.  I can see the Alexa Dummy Light  switching but not switching off and no message.  Two different verbal reports are not verbally reporting.  Any one doing similar and still functioning under 3.4.5

**Comment by alandtse** [comment] 2021-01-03 01:15
@scacace you are off topic. Please open an issue.
