### ISSUE TITLE
HA upgrade causes Notification without dismiss and without Captcha image (error)

### ISSUE THREAD

**Issue by scacace** [custom-components/alexa_media_player#781] opened 2020-06-14 15:01 UTC
**Describe the bug**
Notice this in HA .111 and .110 upgrades.  Notification generated without dismiss.   Attempts to satisfy, generates an error in the Captcha image.  Does not matter browser, or HA App.   Only able to resolve is to delete the implementation and adding it again from Configuration / Integrations.

**To Reproduce**
After HA upgrade notification is generated.

**Expected behavior**
Progress to Notification completion with Captcha image

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment] 2020-06-14 18:00
Duplicate of #774

**Closed by alandtse** 2020-06-14 18:00 UTC
