### ISSUE TITLE
"ValueError: Config entry has already been setup!"

### ISSUE THREAD

**Issue by smhgit** [custom-components/alexa_media_player#533] opened 2020-01-19 14:09 UTC
Installed: v2.5.2

```
Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup

    hass, self

  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 301, in async_setup_entry

    return await hass.data[DOMAIN].async_setup_entry(entry)

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry

    raise ValueError("Config entry has already been setup!")

ValueError: Config entry has already been setup!

2020-01-19 15:58:18 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx.xxx@gmail.com - amazon.com for alarm_control_panel
```

**Comment by alandtse** [comment] 2020-01-19 19:56
Thanks. It's a dupe of #451

**Closed by alandtse** 2020-01-19 19:56 UTC
Labels: duplicate
