### ISSUE TITLE
Unable to connect to Home Assistant url. Please check the External Url under Configuration -> General

### ISSUE THREAD

**Issue by greasypete** [custom-components/alexa_media_player#1624] opened 2022-06-03 11:04 UTC
Since HA 2022.6.0 my integration is not working anymore. I am using also duckdns.org  and it was running for month.

I tried to uninstall the integration and delete also in HACS and did all the reboots in between. 

When I try to reauthorize the integration using like "https://myha.duckdns.org:61443" the error always showing "Unable to connect to Home Assistant url. Please check the External Url under Configuration -> General" , but its the same (also checked spaces etc).

Any further ideas or what I can do to check what's might be missing or wrong?

Cheers Pete

**Comment by 21Development** [comment] 2022-06-03 14:17
+1 
Everything was working on 2022.5.5, I upgraded to 2022.6 and Alexa Media Player asked for reauthentication, after several reboots of everything, nothing worked. Tried restoring partial backup to 2022.5.5 and still didn't work. Updated to 2022.6.1 and then deleted the integration, now just get the "Unable to connect to Home Assistant url..." message when attempting to add the integration. 

I can connect to the external url and login with the Alexa creds okay from my mobile. I too am using duckdns & NGINX Proxy if it makes a difference.

Here's the error log:
```
2022-06-03 15:06:43 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2022-06-03 15:06:43 DEBUG (MainThread) [custom_components.alexa_media.helpers] **********@************: Returning uuid {'uuid': 'b943b432774024fb2fredacted', 'index': 0}
2022-06-03 15:06:43 DEBUG (MainThread) [alexapy.alexalogin] Login created for redacted@googlemail.com - amazon.co.uk
2022-06-03 15:08:54 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Unable to connect to provided Home Assistant url: https://redacted.duckdns.org
```

**Comment by Petro31** [comment] 2022-06-03 22:19
Ditto.

**Comment by Petro31** [comment] 2022-06-03 22:52
I have gone back to 3.11.3.  I too was unable to log in with 3.11.3.  However, I noticed I had remnants of the deprecated yaml configuration.  I removed them and the reauth page forced me to enter a new 2factor 6 digit number and it's working again.

This issue seems to be related to reauthenticating.  Instead of bringing up the 2 factor screen, it brings up the full reauthentication page.  Secondly, it does not seem to honor the internal 2factor settings (or they were removed).  I can't tell because all the reauth information in storage is hashed.

Regardless, this issue is present in 4.0.1 and not in 3.11.3.

**Comment by alandtse** [comment] 2022-06-04 04:18
Dupe of #1616, #1326, etc.




> This issue seems to be related to reauthenticating. Instead of bringing up the 2 factor screen, it brings up the full reauthentication page. Secondly, it does not seem to honor the internal 2factor settings (or they were removed). I can't tell because all the reauth information in storage is hashed.

The not loading of the old key may be a true bug we'll look into fixing. The old prompt is not coming back and you'll need to use the old version if you want to have it.

**Closed by alandtse** 2022-06-04 04:18 UTC

**Comment by 21Development** [comment] 2022-06-04 10:08
@alandtse The wiki currently says:

“Follow Amazon's [instructions](https://www.amazon.com/gp/help/customer/display.html?nodeId=202073820). We strongly recommend that you use an **authenticator app** so you can generate your own OTP codes without relying on Amazon sending them to you.”

Based on this I never thought using Googles Authentication app is considered ‘legacy’ as it’s mentioned in the wiki, so assumed it should work in v4.x - but if the ‘old prompt’ is not coming back - are you saying using the Google Authenticator App is no longer supported and we need to switch to the ‘built-in 2FA’ ? (I’m just wondering if this is where the confusion is as the docs and change logs are not clear on this point.)

**Comment by Petro31** [comment] 2022-06-04 10:14
> @alandtse The wiki currently says:
> 
> “Follow Amazon's [instructions](https://www.amazon.com/gp/help/customer/display.html?nodeId=202073820). We strongly recommend that you use an **authenticator app** so you can generate your own OTP codes without relying on Amazon sending them to you.”
> 
> Based on this I never thought using Googles Authentication app is considered ‘legacy’ as it’s mentioned in the wiki, so assumed it should work in v4.x - but if the ‘old prompt’ is not coming back - are you saying using the Google Authenticator App is no longer supported and we need to switch to the ‘built-in 2FA’ ? (I’m just wondering if this is where the confusion is as the docs and change logs are not clear on this point.)

Where do you see "Googles Authentication app is considered 'legacy'"? in the wiki?

**Comment by Petro31** [comment] 2022-06-04 10:17
I guess the by proxy method is the new login method.  Interesting.  That seems buried, I'll give it a try tomorrow.

**Comment by 21Development** [comment] 2022-06-04 10:24
> Where do you see "Googles Authentication app is considered 'legacy'"? in the wiki?

I associated “Google Authentication app” = “use an authenticator app” (in wiki) which was a valid method, however if the old prompt where you enter the code no longer appears, this method no longer works and v4.0.0 release says “legacy login and options removed”

**Comment by alandtse** [comment] 2022-06-04 16:53
> > Where do you see "Googles Authentication app is considered 'legacy'"? in the wiki?
> 
> I associated “Google Authentication app” = “use an authenticator app” (in wiki) which was a valid method, however if the old prompt where you enter the code no longer appears, this method no longer works and v4.0.0 release says “legacy login and options removed”

This is incorrect. I use Google authenticator. You will be prompted still if an OTP is needed.

**Comment by 21Development** [comment] 2022-06-04 17:04
> This is incorrect. I use Google authenticator. You will be prompted still if an OTP is needed.

Okay, then the issue appears to be the 2nd page (which prompts for the Google code) no longer shows up, which is resulting in not being able to connect and we are displayed the “unable to connect to home assistant” error message. 

I believe this issue still exists on 4.x and people are posting the bug under various headings, I can’t see a open issue for this, should I create one?

**Comment by alandtse** [comment] 2022-06-04 17:24
> @alandtse Okay, then the issue appears to be the 2nd page (which prompts for the Google code) no longer shows up, which is resulting in not being able to connect and we are displayed the “unable to connect to home assistant” error message.

First, please stop pinging me. I'm already responding on the thread. Second, the unable to connect to home assistant is a separate issue that has been resolved and explained multiple times. Please search closed issues or even look at the dupes I already identified.

> I believe the authentication issue still exists on 4.x and people are posting the bug under various headings, I can’t see a open issue for not being prompted for code, should I create one?

That isn't a bug. You just haven't reached a stage where Amazon has asked for it. You may have a point about people not seeing open issues. The problem is people don't search the closed issues where the resolution has been posted multiple times. There is no technical solution for that that I'm aware of.

**Comment by 21Development** [comment] 2022-06-04 18:53
> First, please stop pinging me. I'm already responding on the thread. Second, the unable to connect to home assistant is a separate issue that has been resolved and explained multiple times. Please search closed issues or even look at the dupes I already identified.

Appologies, I'm not a coder and need to learn GitHub ettiquette better! - I've read, followed and tried everything mentioned in #1616 #1617 #1618 #1620 #1622 #1624 and read #1326.

> That isn't a bug. You just haven't reached a stage where Amazon has asked for it

Either I (and others) are missundertanding something or there is a bug somewhere ;-) - I now have v3.11.3 working again, under HA 2022.6.1 but no matter what I've tried so far, have never been prompted for the code from Google Authenticator when installing AMP v4.x and always get a "Unable to connect to home assistant url" message. Therefore for me, v4.x is broken and no amount of deleting AMP (including from YAML), adding 2nd authenticator app on Amazon and using built-in 2FA. rebooting of everything at every stage and re-installing AMP has worked.

Things I haven't yet tried, that I saw mentioned in the above closed issues are:

- Using my external IP address instead of xxx.duckdns.org (didn't try as it's not a viable solution)
- Renewing SSL certificate as mentioned in #1326 (as it works okay in 3.11.x and I've not see any warnings in Chrome)
- Searching for / removing anything outside of custom_components/alexa_media
- Trying to get it to work without using Google Authenticator and just using built-in 2FA

I'm happy to try more things and help where I can, for now, I've left 3.11.3 running until I can properly understand how things are supposed to be setup when using Google Authentication - at this point, the wiki to me is confusing (and I come from a tech background) as it's not clear what I am supposed to change (if anything) or what you are considering 'legacy' when moving from 3.x to 4.x authentication.

Maybe it's something Amazon's side so working for some and not others.... I'll try 4.x again in a few days and see if I can work out what's going wrong and/or I'm missunderstanding.

**Comment by greasypete** [comment] 2022-06-05 11:18
I also move successfully back to 3.11.3 as what ever I was trying also red the mentioned comments from the other ones. Since 2022.6.0 and 4.x it stopped working for me. 
![Screenshot 2022-06-05 at 13 15 52](https://user-images.githubusercontent.com/50394918/172047965-3d394237-6a80-4b14-9e77-43f4f6c609f1.png)

also last two option not showing in 4.x for me, i got these from another mentioned issue. not sure if this is something that might be the problem.

Or is someone aware of any aws region dependencies? I am using amazon.de .. I will also retry soon when some changes coming along ....

Thx Pete

**Comment by seether84** [comment] 2022-06-05 13:30
@greasypete 

Hey. What  a coincidence I wanted to setup alexa mediaplayer today (for the first time) and got the error massage too.
In my case it was a strange thing what I have overlooked so many times I installed this integration, removed it, changed ports etc.

Maybe it's the same for you.

It was the URL in the configuration of alesxa mediaplayer integration (UI) what I haven't noticed. I have a very cryptic domain for my home assistant so it was not obvious.

Check the URL that was automatically filled in. This wasn't actually my domain. I don't know why this was happening.
Copy your correct URL from your browsers address field.

It was this simple for me so solve this (after really long time I missed that).
besides - I also have amazon.de as my region.

**Comment by 21Development** [comment] 2022-06-05 15:29
Just an update from me. After successfully installing 3.11.3, then leaving overnight ~20hrs, without changing anything else, I’ve just upgraded to 4.0.2, rebooted and AMP is now showing up correctly, without any prompt to re-authencate.

So, just to confirm my process.
1. Deleted AMP 4.0.2 from HACS
2. Removed any references in configuration.yaml
3. Restarted HA (2022.6.1)
4. Pasted same entries back into configuration.yaml & restart HA again
5. Installed AMP 3.11.3 via HACS with successful authentication using Google Authentication App
6. Left HA running 20hrs
7. Upgraded AMP to 4.0.2 via HACS
8. Restarted HA and was not prompted for any further setup or authentication

It seems like installing 3.11.3 again yesterday created whatever authentication token that was needed, for AMP 4.0.2 to work correctly OR something changed at Amazon!?

**Comment by alandtse** [comment] 2022-06-05 18:40
> also last two option not showing in 4.x for me, i got these from another mentioned issue. not sure if this is something that might be the problem.

These were removed in 4.x as users who deselected them ended up in weird states I didn't want to support anymore.

**Comment by greasypete** [comment] 2022-06-06 09:07
> @greasypete
> 
> Hey. What a coincidence I wanted to setup alexa mediaplayer today (for the first time) and got the error massage too. In my case it was a strange thing what I have overlooked so many times I installed this integration, removed it, changed ports etc.
> 
> Maybe it's the same for you.
> 
> It was the URL in the configuration of alesxa mediaplayer integration (UI) what I haven't noticed. I have a very cryptic domain for my home assistant so it was not obvious.
> 
> Check the URL that was automatically filled in. This wasn't actually my domain. I don't know why this was happening. Copy your correct URL from your browsers address field.
> 
> It was this simple for me so solve this (after really long time I missed that). besides - I also have amazon.de as my region.

@seether84
Thx you, but this i already tried without success, might be the somehow the :port is making any trouble


i also compared old and new files in /config alexa_meda<email>...post.html and ....get.html beside some guids i could find any major differences ... is 4.x also trying to create or overwriting these files?  

So lets see, what I might missed, which causing this problem on my end. will keep testing also with new 4.x, might will set up  a new test HA on another PI. Will let u guys know, in case i found the solution.

Cheers Pete
