### ISSUE TITLE
Unknown error: alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found

### ISSUE THREAD

**Issue by DavidBoike** [custom-components/alexa_media_player#1146] opened 2021-01-25 16:43 UTC
**Describe the bug**
On update of Home Assistant, HACS, and alexa_media_player, Alexa Media infrastructure is not created. The `notify.alexa_media` service does not exist, and media player entities are not available. The services mentioned in `/config/custom_components/alexa_media/services.yaml` (namely `update_last_called`, `clear_history`, and `force_logout` also do not exist.

The logs contain a warning:

> Error creating TOTP; ****** likely invalid
> Logger: alexapy.alexalogin
> Source: /usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py:238

And an error:

> Error setting up entry Alexa for alexa_media
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 235, in set_totp
>     self.get_totp_token()
>   File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 254, in get_totp_token
>     token: Text = self._totp.now()
>   File "/usr/local/lib/python3.8/site-packages/pyotp/totp.py", line 44, in now
>     return self.generate_otp(self.timecode(datetime.datetime.now()))
>   File "/usr/local/lib/python3.8/site-packages/pyotp/otp.py", line 33, in generate_otp
>     hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
>   File "/usr/local/lib/python3.8/site-packages/pyotp/otp.py", line 50, in byte_secret
>     return base64.b32decode(self.secret, casefold=True)
>   File "/usr/local/lib/python3.8/base64.py", line 231, in b32decode
>     raise binascii.Error('Non-base32 digit found') from None
> binascii.Error: Non-base32 digit found
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/alexa_media/__init__.py", line 285, in async_setup_entry
>     AlexaLogin(
>   File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 119, in __init__
>     self.set_totp(otp_secret.replace(" ", ""))
>   File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 241, in set_totp
>     raise AlexapyPyotpInvalidKey(ex) from ex
> alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found

Based on my reading of the source, this happens outside the try/catch block that would trigger the persistent notification that I need to reauthenticate to Amazon, and no such notification is displayed in the Supervisor node.

Based on [this FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ#alexa-suddenly-stopped-working-it-was-working-for-a-few-months) I went searching for the "pickle" file but could find no such file in `config/` using the File Editor or Samba Share plugins.

**I find it quite likely that a new procedure for clearing the existing authentication data could resolve my issue. I would have tried the `force_logout` service but it's not available in Developer Tools either.**

In HACS > Integrations, the Alexa Media Player actions menu also does not provide the option to reauthenticate.

**To Reproduce**
1. Update to Home Assistant 2021.1.5
2. Update to HACS 1.10.1
3. Update to Alexa Media Player 3.6.2.
4. Restart Home Assistant.

**Expected behavior**
Media players and services should be available.

**Screenshots**
Can't think of any that would be useful.

**System details**
 - Home-assistant (version): 2021.1.5
 - Hassio (Yes/No): Yes - Home Assistant OS 5.10
 - alexa_media  (version from `const.py` or HA startup):3.6.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.22.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2021-01-25 10:17:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-25 10:17:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-25 10:17:47 DEBUG (MainThread) [custom_components.alexa_media] Nothing to import from configuration.yaml, loading from Integrations
2021-01-25 10:17:48 INFO (MainThread) [custom_components.alexa_media]
-------------------------------------------------------------------
alexa_media
Version: 3.6.2
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------
2021-01-25 10:17:48 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.22.2
2021-01-25 10:17:48 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*********e@g*******m: Returning uuid {'uuid': '**************************', 'index': 0}
2021-01-25 10:17:48 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for ******
2021-01-25 10:17:48 WARNING (MainThread) [alexapy.alexalogin] Error creating TOTP; ****** likely invalid
2021-01-25 10:17:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alexa for alexa_media
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 235, in set_totp
self.get_totp_token()
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 254, in get_totp_token
token: Text = self._totp.now()
File "/usr/local/lib/python3.8/site-packages/pyotp/totp.py", line 44, in now
return self.generate_otp(self.timecode(datetime.datetime.now()))
File "/usr/local/lib/python3.8/site-packages/pyotp/otp.py", line 33, in generate_otp
hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
File "/usr/local/lib/python3.8/site-packages/pyotp/otp.py", line 50, in byte_secret
return base64.b32decode(self.secret, casefold=True)
File "/usr/local/lib/python3.8/base64.py", line 231, in b32decode
raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/alexa_media/__init__.py", line 285, in async_setup_entry
AlexaLogin(
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 119, in __init__
self.set_totp(otp_secret.replace(" ", ""))
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 241, in set_totp
raise AlexapyPyotpInvalidKey(ex) from ex
alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found
```

**Additional context**
Running on Raspberry Pi 4.

**Comment by alandtse** [comment] 2021-01-25 18:36
Dupe of #1028. Remove and readd the integration.

**Comment by DavidBoike** [comment] 2021-01-25 19:17
Removed the integration and restarted HA. Then re-added the integration and restarted HA again. Same problem.

I had also previously tried downgrading back to v3.5.1 - also no effect.

**Comment by alandtse** [comment] 2021-01-25 19:46
Did you put the otp in the wrong field?

**Comment by alandtse** [comment] 2021-01-25 19:49
Please read the link I already provided.

**Comment by DavidBoike** [comment] 2021-01-25 20:00
I really can't be sure, since there's no way to go inspect those settings. Is there a way to clear the settings and start over? Removing and reinstalling the integration don't seem to do that.

I upgraded after the first HA security bulletin and upgraded to v3.5.0. At that point the normal reauthenticate workflow happened. I elected at that time to contnue with the "put in the 2FA code" method rather than the method where HA could generate the 2FA codes for me. That worked then, though I suppose I could have put something in an incorrect field. As I said, there's no way for me to force that window to appear so I can check, since Reauthenticate is not currently an option:

![image](https://user-images.githubusercontent.com/427110/105758884-65b14380-5f15-11eb-8216-4d12489d89e0.png)

That's why I said that removing the login information and starting over on that might be the quickest solution. Since it seems the part in the wiki about the pickle file is out of date, I'd be happy to update that section once this is figured out.

**Comment by alandtse** [comment] 2021-01-25 20:03
If you remove and readd the integration it will remove all the data that is causing the issue for you.

**Comment by alandtse** [comment] 2021-01-25 20:04
You have to do it in the integrations page, not HACS.

**Comment by DavidBoike** [comment] 2021-01-25 20:14
Aha, that may have helped. Before I saw that, however, I found the hidden `.storage` folder via SSH, and found the pickle file within it. Moved that aside and was able to reconfigure the integration using the [self-generating 2FA method here](https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app). Very excited about this! Thank you!

**Comment by alandtse** [comment] 2021-01-25 20:22
I'm going to keep this open as there should have been a proper error message. Apparently it isn't displaying on this config page.

If there's any thing on the wiki that can be improved. Please do.

**Closed** 2021-01-26 04:11 UTC
Labels: duplicate
