### ISSUE TITLE
information is not updating

### ISSUE THREAD

**Issue by herveaurel** [custom-components/alexa_media_player#2011] opened 2023-09-03 20:42 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

For several weeks, the integration has not updated the information, for example: the state of music, alarms, other sensors, switches, etc...
The only method I've found is to reload the integration manually, every now and then, but I don't have the right information between reloads.

I asked other users, and they have the same problem.

Because of this, the integration is not reliable for automations regarding music, alarms etc...

I don't see anything in the logs.

**To Reproduce**

1. Play music on an echo
2. set an alarm
3. consult home assistant
4. see that no information is up to date

**Expected behavior**

I hope that, like several weeks ago, all the information comes back into Home Assistant immediately

**Screenshots**

none

**System details**

- Home-assistant (version): 2023.8.4
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes is enable

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
I didn't see any logs

**Additional context**

none

**Comment by M3d1c5** [comment] 2023-09-04 08:12
I have been experiencing this problem since 31.8. I have an automation that becomes active as soon as the volume of an Echo Dot is changed. This automation no longer works.

```
alias: Echo Gäste-WC Lautstärke
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.echo_gaste_wc
    attribute: volume_level
    for:
      hours: 0
      minutes: 3
      seconds: 0
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.1
    target:
      entity_id: media_player.echo_gaste_wc
mode: single
```

**Comment by HeroCity99** [comment] 2023-09-04 15:52
I started experiencing this recently as of 4-5 dats ago. the volume change on the Echo or triggering the entity update from HA used to fix this issue for couple of hours. But lately all my Echo entities are not updating and I have 6 Alexa devices.

**Comment by johndoe0815** [comment] 2023-09-05 17:18
Same for me. I cannot say when exactly it started, but not that long ago, couple of days I think. All Alexa devices (Echo Dots and Fire TV Cube) do not anymore show that/what is currently being played. With manually reloading the integration or e.g. pressing the power switch of the device in HA I sometimes then get the current information being displayed, but practically it does not work anymore (after using it for a long time without any issues). In HA everything looks normal and I can't recall to have changed something that could be the root cause of this.

**Comment by alandtse** [comment] 2023-09-05 19:55
Dupe of #1953. Please follow that.

**Closed** 2023-09-05 19:55 UTC
Labels: duplicate
