### ISSUE TITLE
ValueError: Config entry has already been setup!

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#1057] opened 2020-12-24 22:21 UTC
Alexa Media Player: 3.4.1
HA:  2020.12.7

I receive those errors many times. What can this be?

```
2020-12-24 22:58:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry info@mydomain.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 345, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

2020-12-24 23:08:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry info@mydomain.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 345, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

2020-12-24 23:18:31 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry info@mydomain.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 345, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by alandtse** [comment] 2020-12-27 21:06
Dupe of #866. Also please fill out the template if you want assistance.

**Closed by alandtse** 2020-12-27 21:06 UTC
