### ISSUE TITLE
Integration 2 step verification trouble

### ISSUE THREAD

**Issue by jerfer7** [custom-components/alexa_media_player#614] opened 2020-03-28 17:06 UTC
After installing with HACS and attempting integrate it shows a list of devises/ama to send verification code. I tuo sms or push and the message never comes to finish the integration. What am I doing wrong?

**Comment by Silvenga** [comment] 2020-03-28 17:19
Same issue - I pass the captcha, get a list of OTP methods, I select `email`, no emails are received. 

Logging in via Chrome using incognito mode immediately sends a OTP (which doesn't work with alexa_media_player).

**Comment by alandtse** [comment] 2020-03-28 19:42
Thanks.  This is a duplicate of #568 which lists workarounds.  We are still trying to get logs and other info to actually solve the problem, so please provide them there if you don't do the workaround.

**Closed by alandtse** 2020-03-28 19:42 UTC

**Comment by jerfer7** [comment] 2020-03-29 14:53
Than

> Thanks. This is a duplicate of #568 which lists workarounds. We are still trying to get logs and other info to actually solve the problem, so please provide them there if you don't do the workaround.

Thank you
