### ISSUE TITLE
Configuration crashes with "follow_redirects"

### ISSUE THREAD

**Issue by rt87** [custom-components/alexa_media_player#1445] opened 2021-11-30 13:34 UTC
**Describe the bug**
When trying to initially configure the media player, it crashes when trying to open the amazon login page. In the browser, I see a 500 internal server error.

**To Reproduce**
add media player integration

**Expected behavior**
Expected to be forwarded to amazon for initial login.

**Screenshots**
The log shows the following message/stacktrace (s. also logs section):
![grafik](https://user-images.githubusercontent.com/30858878/144053479-916ae9b6-504b-45c3-b6ce-d38b0225c519.png)

**System details**
 - Home-assistant (version): 2021.11.5
 - Hassio (Yes/No): No (Docker Container)
 - alexa_media  (version from `const.py` or HA startup): 3.10.12
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: enabled

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
below the log from when using the debugging settings

2021-11-30 14:21:51 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2021-11-30 14:21:51 DEBUG (MainThread) [custom_components.alexa_media.helpers] <MY_MASKED_EMAIL>: Returning uuid {'uuid': 'MY_UID', 'index': 0}
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for <MY_MASKED_OTP_SECRET>
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP <MY_OTP>
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Login created for <MY_EMAIL> - amazon.de
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Attempting oauth login to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:<MY_DEVICE_ID>&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=de_DE
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP <MY_OTP>
2021-11-30 14:21:51 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Refreshed 2 modifiers: ['prepend_relative_urls', 'change_host_to_proxy']
2021-11-30 14:21:51 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Refreshed 1 tests: ['test_amazon_url']
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP <MY_OTP>
2021-11-30 14:21:51 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Refreshed 3 modifiers: ['autofill', 'prepend_relative_urls', 'change_host_to_proxy']
2021-11-30 14:21:51 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP <MY_OTP>
2021-11-30 14:21:51 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Generating OTP from <MY_OTP>
2021-11-30 14:22:01 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Not registered, regenerating
2021-11-30 14:22:01 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP <MY_OTP>
2021-11-30 14:22:01 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Generating OTP from <MY_OTP>
2021-11-30 14:22:07 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Starting proxy for  <MY_MASKED_EMAIL> - amazon.de
2021-11-30 14:22:08 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found flow_id; adding <MY_END_DEVICE_IP> to known_ips for 300 seconds
2021-11-30 14:22:08 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Received get: <MY_SERVER_ADDRESS_AND_PORT>/auth/alexamedia/proxy?config_flow_id=<SOME_ID>&callback_url=<MY_SERVER_ADDRESS_AND_PORT>/auth/alexamedia/callback?flow_id%<SOME_ID>for https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:<MY_DEVICE_ID>&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=de_DE
2021-11-30 14:22:08 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Starting auth capture proxy for https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:<MY_DEVICE_ID>&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=de_DE
2021-11-30 14:22:08 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Final headers {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8', 'Accept-Language': 'de,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'DNT': '1', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1'}
2021-11-30 14:22:08 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Attempting get to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:<MY_DEVICE_ID>&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=de_DE
headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8', 'Accept-Language': 'de,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'DNT': '1', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1'} 
cookies: <CookieJar[]>

**Additional context**
Note: Apparently there are some amazon.com links, despite me specifying the .de domain.
Note: I regenerated the OTP token once because I wasn't quick enough, however, if I use the first token, the outcome is unchanged.

**Comment by iMicknl** [comment] 2021-12-02 17:34
I face the same issue with `amazon.nl` as domain.

**Comment by kevindesgagnes** [comment] 2021-12-03 03:32
I face the same issue with amazon.com as domain.

**Comment by linus-ha** [comment] 2021-12-03 18:07
Same issue here with `amazon.de`
- built-in 2FA-Key was **provided**
- "Use Login Proxy method (2FA not required)" is **enabled**
- "Enable oauth-token app method" is **enabled**

After the setup form, I was redirected and landed on an Error 500 page. The URL in my browser after redirection was:
`https://homeassistant.XXX/auth/alexamedia/proxy?config_flow_id=XXX&callback_url=https://homeassistant.XXX/auth/alexamedia/callback?flow_id%3DXXX`
the ID was the same for `flow_id` and `config_flow_id`

HA logs
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:1116
Integration: Alexa Media Player (documentation, issues)
First occurred: 2. Dezember 2021, 19:01:58 (13 occurrences)
Last logged: 18:58:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/alexa_media/config_flow.py", line 1116, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
    resp = await getattr(self.session, method)(
TypeError: get() got an unexpected keyword argument 'follow_redirects'
```

**Comment by linus-ha** [comment] 2021-12-03 18:12
Duplicate of #1440

**Comment by alandtse** [comment] 2021-12-03 22:54
Thanks. Please follow the original issue.

**Closed by alandtse** 2021-12-03 22:54 UTC
