### ISSUE TITLE
Error communicating with API: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by genebean** [custom-components/alexa_media_player#1198] opened 2021-02-26 20:59 UTC
**Describe the bug**
I am getting this in my logs and things have stopped working. This is still true after calling the logout service and logging back in:

```
2021-02-26 15:56:44 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service notify/alexa_media
2021-02-26 15:56:48 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f6b282880>,), {}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
('the JSON object must be str, bytes or bytearray, not NoneType',)
2021-02-26 15:56:48 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: the JSON object must be str, bytes or bytearray, not NoneType
2021-02-26 15:56:48 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f6b282880>,), {}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
('the JSON object must be str, bytes or bytearray, not NoneType',)
```

**Comment by genebean** [comment] 2021-02-26 21:28
Now I am really confused... after speaking to the Echo Show on my desk HA immediately started working instead of saying the devices were unavailable. Having said that, it still appears that that their states are not refreshing. I have changed what's playing both by speaking to the device and by sending "custom commands" from a HA automation and neither has changed what is shown in Lovelace
![image](https://user-images.githubusercontent.com/966789/109357077-9dcadf80-784f-11eb-89e0-7a53cfaa6a27.png)

**Comment by alandtse** [comment] 2021-02-27 03:15
Duplicate of #1196

**Closed by alandtse** 2021-02-27 03:15 UTC
Labels: duplicate
