### ISSUE TITLE
The status of the devices is not updated to reflect playing state

### ISSUE THREAD

**Issue by funkschrauber** [custom-components/alexa_media_player#397] opened 2019-09-29 10:38 UTC
The status of the devices is not updated. If a device is available again, it will not be displayed, even if a device is no longer available.

EDIT: Please fill out if you'd like me to understand.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment] 2019-09-30 03:28
Please provide more details. I don't know what the issue is.

**Comment by alandtse** [comment] 2019-09-30 07:36
For example, how do you know a device is available again? Are you unplugging it?  I also need to know what version you're on. Websocket should detect devices coming online.  There's a reason we have a reporting template to avoid these initial questions.  Please answer them.

**Comment by funkschrauber** [comment] 2019-09-30 08:36
I have an Echo Dot that runs on battery and can be turned off. When I turn this echo on, the status in HA does not change to standby or anything like that. He remains unavailable.

System details
Home-assistant (version): 0.99.3
Hassio (Yes/No): YES
alexa_media (version from const.py or HA startup): 2.3.0
alexapy (version from pip show alexapy or HA startup): 0.10.1

Further information will follow.

**Comment by alandtse** [comment] 2019-10-01 00:47
Thanks. Please provide logs for both alexa_media and alexapy. Check the Wiki FAQ for instructions. 

The first thing to check is that you see websocket traffic when you adjust the volume on a device or if play something. If you don't see that, you're in polling mode which means a device only becomes available if you interact with it through the component. It's possible that the logic may be broken for devices that are unavailable as opposed to standby.

**Comment by Dielee** [comment] 2019-10-04 06:48
Hello guys, same probleme here, again. Looks like #369 is back. 

HA: 0.99.3
Alexyapy: 1.3.1
Alexa_media: 2.3.0
Logs: https://cloud.linusdietz.eu/index.php/s/EgzKgJ8skDpkRJl

**Comment by alandtse** [comment] 2019-10-04 07:50
@Dielee Thanks for the logs. Does the websocket just stop updating even if you're changing the volume/playing media?  Do any of the commands still work?

**Comment by Dielee** [comment] 2019-10-04 07:59
Volume changes seems to be working. But play,pause not.

**Comment by alandtse** [comment] 2019-10-04 08:20
Sorry can you be more specific when you say working. You mean they show up in the websocket logs? Or do you mean the commands cause a change in the Alexa device but are not in the websocket logs?

**Comment by Dielee** [comment] 2019-10-04 08:36
They cause a change in the alexa device and in home assistant also. So this works as expected.

**Comment by funkschrauber** [comment] 2019-10-04 11:39
To this topic:
The functions that I perform as an automation are media_player.media_pause and media_player.volume_set.
media_player.volume_set works.
media_player.media_pause does not work for me at the moment.
It worked a few days ago.
Notify.alexa did not work this morning.
After a reboot, I had to authorize myself again.
After that, notify.alexa worked again, but not media_player.media_pause or media_player.media_stop.

**Comment by funkschrauber** [comment] 2019-10-04 11:58
[log.log](https://github.com/custom-components/alexa_media_player/files/3690393/log.log)

Here is a log file, where an automation media_player.media_pause on buro was executed. Did not work.

**Comment by alandtse** [comment] 2019-10-07 06:48
Looks like there may be a bug in the underlying aiohttp websockets implementation where it [doesn't detect disconnects](https://github.com/aio-libs/aiohttp/issues/2368). I'll need to investigate further.

**Comment by Dielee** [comment] 2019-10-07 06:51
For me, this works again... I don't know whats going on there.

**Comment by Dielee** [comment] 2019-10-08 07:28
Bug seems to be back... Only works for a few hours.

**Comment by funkschrauber** [comment] 2019-10-09 09:47
Problem is still not resolved.

**Comment by Dielee** [comment] 2019-10-10 10:52
Any updates for this ? Component isn't working for a week :(

**Comment by alandtse** [comment] 2019-10-10 16:46
Have you tried moving the pickle and relogging in?

**Comment by Dielee** [comment] 2019-10-10 17:23
Sure, removed pickle and whole integration.. Updates only volume status.

**Comment by alandtse** [comment] 2019-10-11 06:38
Closing and working in the new thread.

**Comment by alandtse** [comment] 2019-10-11 06:46
Actually, I'll reopen this. @Dielee I think you're a different issue than @funkschrauber is reporting in the new issue which is related to battery powered devices. @Dielee I'll debug status change errors here. Play/pause is in the other thread #421.

**Comment by alandtse** [comment] 2019-10-11 06:54
@Dielee can you please generate new logs where you only use your voice or the Alexa App to play or pause music? As part of the test, please also change the volume so I can see the websocket changes.  I want to avoid using the component to issue the commands since that's in the other thread now.

I'm trying to see the websocket info. You should be seeing things like `PUSH_AUDIO_PLAYER_STATE`, `PUSH_VOLUME_CHANGE`, etc.

**Comment by alandtse** [comment] 2019-10-11 07:24
Ok, per [the report in the other thread](https://github.com/custom-components/alexa_media_player/issues/421#issuecomment-540941717) it looks like Amazon may have removed the `PUSH_AUDIO_PLAYER_STATE` from the websocket data potentially in Germany? The `PUSH_MEDIA_QUEUE_CHANGE` change state is around so may partially help.

@Dielee are you able to do a AMAZON_MUSIC test with your voice too? I want to isolate it away from TUNE_IN too.

**Comment by alandtse** [comment] 2019-10-11 08:58
There is another websocket command we weren't processing that looks related to tune_in state.
```
2019-10-11 10:16:54 DEBUG (MainThread) [alexapy.alexawebsocket] msg: WSMessage(type=<WSMsgType.BINARY: 2>, data=b'MSG 0x00000362 0x09aef47c f 0x00000001 0xee00e2dc 0x0000023d GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:XXXXX:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:XXXX {"payload":"{\"destinationUserId\":\"XXX\",\"mediaReferenceId\":\"b8898935-304f-4c5a-b459-56eae5e176f5:1\",\"dopplerId\":{\"deviceSerialNumber\":\"XXX\",\"deviceType\":\"A3S5BH2HU6VAYF\"}}","command":"PUSH_MEDIA_CHANGE"}FABE', extra='')
```

**Comment by alandtse** [comment] 2019-10-12 07:09
The fix is a partial fix because it's trying to replicate functionality that appears to be gone in Germany now. There will be audio change requests we will not catch instantly because there's no trigger to catch with websockets.

**Comment by alandtse** [comment] 2019-10-13 07:50
Please try 2.3.3 and reopen if issue still exists.

**Closed by alandtse** 2019-10-13 07:50 UTC
Labels: bug

**Comment by Dielee** [comment] 2019-10-13 11:04
Works for me, too. Thank you very much @alandtse!

**Comment by northpower25** [comment] 2019-10-13 15:46
It works now  @alandtse thanks for the quick solution of this problem 👍🏻
