### ISSUE TITLE
Fire and Event when a timer goes off

### ISSUE THREAD

**Issue by fjmiller** [custom-components/alexa_media_player#868] opened 2020-08-16 22:19 UTC
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for 
Currently the functionality is to have an entity called next_timer which shows the time the next timer will go off.  While this can be used to calculate when a timer actually does go off it gets awfully confusing and lots of steps in the automation to get it accurate for all devices, multiple timer, changes etc.  If we could get an event that fired to make Home Assistant aware a timer fired, include the device it is from and any names from the user it would make automations much more simple.

**Is your feature request related to a problem? Please describe.**
This is a feature request.

**Describe the solution you'd like**
I would like an event or entity that can trigger an automation when a timer goes off on any alexa device and include the device identifier and any custom names.  Currently we can determine when a timer goes off through IFTTT integration.

**Describe alternatives you've considered**
Using IFTT and a detailed flow to try and trigger events on timers.  Still not 100% in the case of multiple timers on a single device and the user changing durations.

**Additional context**

**Comment by alandtse** [comment] 2020-08-19 01:31
There's no event for us to track to fire this event and we can't tell if an alarm has been cancelled or not (they look the same). You'll have to use a template. Please check the forums or wiki for examples.

**Comment by alandtse** [comment] 2020-08-19 03:26
Also dupe of #686

**Closed by alandtse** 2020-08-19 03:26 UTC
Labels: duplicate
