### ISSUE TITLE
Unknown error, please report with logs

### ISSUE THREAD

**Issue by Francisk0** [custom-components/alexa_media_player#571] opened 2020-02-27 15:05 UTC
Hi,
When I try to add in the integration of HA have this error, and don´t go to captcha verification.
If change amazon.es for amazon.com, works, and can integrate in HA, but only is avaiable the "don´t disturb function" in my echos.
I don´t know how to see debug info, because HA register only says:
2020-02-27 14:20:12 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error

I try with version 2.55 and 2.54

**Comment by alandtse** [comment] 2020-02-28 08:06
Dupe of #568; please see requests for log info there.

**Closed by alandtse** 2020-02-28 08:06 UTC
Labels: duplicate

**Comment by Francisk0** [comment] 2020-02-29 06:57
I try with my data in configuration.yaml and using integration, but doesn´t work
Now have a log:
2020-02-29 06:49:26 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2020-02-29 06:49:33 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 
2020-02-29 06:49:33 DEBUG (MainThread) [custom_components.alexa_media.config_flow] show_form user None {'base': 'unknown_error'} None
2020-02-29 06:50:48 DEBUG (MainThread) [custom_components.alexa_media.config_flow] show_form user None None OrderedDict([('email', <class 'str'>), ('password', <class 'str'>), ('url', <class 'str'>), ('debug', <class 'bool'>), ('include_devices', <class 'str'>), ('exclude_devices', <class 'str'>), ('scan_interval', <class 'int'>)])
2020-02-29 06:51:07 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Using existing login
2020-02-29 06:51:16 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 
2020-02-29 06:51:16 DEBUG (MainThread) [custom_components.alexa_media.config_flow] show_form user None {'base': 'unknown_error'} None
