### ISSUE TITLE
TTS doesn't work on Alexa

### ISSUE THREAD

**Issue by AntoWkill** [custom-components/alexa_media_player#398] opened 2019-09-29 13:02 UTC
**Describe the bug**

I successfull added my alexa with this component in home-assistant.
When i try to use tts service alexa say:
"Sorry, the text to speech can only be call by the notify media service, please se notify wiki for details"

**Comment by funkschrauber** [comment] 2019-09-29 13:55
Use notify.alexa_media instead media_player. Then it work.

**Comment by AntoWkill** [comment] 2019-09-29 14:58
> Use notify.alexa_media instead media_player. Then it work.

There is no entity notify.alexa_media

**Comment by AntoWkill** [comment] 2019-09-29 15:12
there is no way to work from here?

<img width="357" alt="Schermata 2019-09-29 alle 17 11 50" src="https://user-images.githubusercontent.com/21131925/65834545-49c76e80-e2dc-11e9-9c2f-dce0685c1265.png">

**Comment by funkschrauber** [comment] 2019-09-29 16:46
No. You can do it through automation, for example.

  alias: Garagedoor open
  trigger:
  - entity_id: binary_sensor.garagedoor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      data:
        method: all
        type: announce
      message: Garagedoor open
      title: Alarm
    service: notify.alexa_media_youralexa

**Comment by alandtse** [comment] 2019-09-30 07:33
Thanks @funkschrauber for answering. Dupe of #232. I believe [Mini Media Player](https://community.home-assistant.io/t/lovelace-mini-media-player/68459) supports alexa_media.

**Closed by alandtse** 2019-09-30 07:33 UTC
