### ISSUE TITLE
error adding

### ISSUE THREAD

**Issue by cyberfly79** [custom-components/alexa_media_player#941] opened 2020-09-21 09:28 UTC
Hi,
I have an echo dot 2.
Home assistant core in docker (0.109.6).
I installed the component from HACS.

When I try to add integration, no content appears in the popup window.

I have enabled 2FA, I am using Google Authenticator.

![image](https://user-images.githubusercontent.com/7328224/93751442-651e3e80-fbfd-11ea-9fa5-bf6269edc235.png)

What should I do differently?

Thanks!

**Comment by cyberfly79** [comment] 2020-09-21 18:40
Error in browser console

![image](https://user-images.githubusercontent.com/7328224/93807316-bdc7f880-fc4a-11ea-9500-45b0097f8d2d.png)

**Comment by alandtse** [comment] 2020-09-22 04:44
Please fill out the bug template.

**Comment by cyberfly79** [comment] 2020-09-22 07:57
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
When you add integration, there is no content in the pop-up window that appears.

**Screenshots**

![image](https://user-images.githubusercontent.com/7328224/93856855-efc47380-fcb9-11ea-8ab2-1ca21be6ef7c.png)


**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): no
 - alexa_media  (version from `const.py` or HA startup): 3.0.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.14.1
 - Amazon [2FA is enabled]: yes 

**Logs**
There are no new records in the log.

**Additional context**
An error message is displayed in the browser after adding the integration.

![image](https://user-images.githubusercontent.com/7328224/93856828-e6d3a200-fcb9-11ea-9d31-99cefb2586c7.png)

**Comment by alandtse** [comment] 2020-09-22 08:39
You can try a hard refresh of your browser cache. If that doesn't work, you may have to update HA.

**Comment by alandtse** [comment] 2020-09-25 04:04
Duplicate of #944, please see there for further details.

**Closed by alandtse** 2020-09-25 04:04 UTC
