### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by Tonylolo** [custom-components/alexa_media_player#1202] opened 2021-03-08 11:44 UTC
Hi

Is it possible to have value of temperature sensor from amazon device? Dot and dot plus.

Instead of a weather station, for interior of house it's a good alternative!

Thank you for development.

**Comment by alandtse** [comment] 2021-03-11 05:31
Yes, dupe of #197 . Likely not to do it though since it would require polling the sensor.

**Comment by GTunney** [comment] 2021-04-26 16:25
I've just updated my alexa media player, I have 2 4th gen echos, the temperature sensor is showing for one but the other one isn't.

Any suggestions as to why it's only added the entity for one device?

**Closed** 2021-04-27 02:00 UTC
Labels: alexapy, duplicate, enhancement

**Comment by Tonylolo** [comment] 2021-04-27 05:04
> I've just updated my alexa media player, I have 2 4th gen echos, the temperature sensor is showing for one but the other one isn't.
> 
> 
> 
> Any suggestions as to why it's only added the entity for one device?

Hi

How do you have this in HA ?
