### ISSUE TITLE
2FA login request every few hours

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#864] opened 2020-08-10 08:42 UTC
**Describe the bug**
Unfortunately since a couple of days, I get a request for 2FA login every few hours.

**To Reproduce**
1. Login with 2FA
2. Wait a few hours

**Expected behavior**
Login with 2FA should be persistent (don't ask again code on this device)

**Screenshots**

![image](https://user-images.githubusercontent.com/57354320/89765048-dabec700-daf5-11ea-9c5e-ed7961eef3ad.png)

![image](https://user-images.githubusercontent.com/57354320/89765005-c67aca00-daf5-11ea-9968-d22530fc565b.png)

![image](https://user-images.githubusercontent.com/57354320/89765027-d1cdf580-daf5-11ea-99ee-e06be99c2eec.png)

**System details**
 - Home-assistant (version): 0.113.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.10.1
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by patdemko** [comment] 2020-08-10 20:32
I'm seeing this a lot too.  Then today, it's accepting my login & 2FA code and all seems fine.  However, when the next alexa media call action tries to run, I immediately see a notification to re-entry the captcha and 2FA code again and the notification message does not play through the echo devices.

**Comment by waltermo** [comment] 2020-08-11 00:44
exact same behavior here on 0.113.2  - Raspbian/supervised 

```
Log Details (ERROR)
Logger: alexapy.helpers
Source: custom_components/alexa_media/media_player.py:562
First occurred: 8:38:01 PM (1 occurrences)
Last logged: 8:38:01 PM

alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0xae2011f0>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Session is closed',)
```

**Comment by alandtse** [comment] 2020-08-11 03:51
Dupe of #863 . Please see potential workarounds.

**Closed by alandtse** 2020-08-11 03:51 UTC
Labels: amazonissue, duplicate

**Comment by alandtse** [comment] 2020-08-11 04:24
@patdemko Your'e actually reporting a different issue that we may have to look into. If the issue is after a relogin subsequent interactions does not work, that may be a bug we can fix. Please open a new issue.

**Comment by chemelli74** [comment] 2020-08-11 09:19
> Dupe of #863 . Please see potential workarounds.

I was under the impression that my issue is different, because I have no error at all reported in the log.
Log level is "warning".

Simone

**Comment by patdemko** [comment] 2020-08-11 13:34
> @patdemko Your'e actually reporting a different issue that we may have to look into. If the issue is after a relogin subsequent interactions does not work, that may be a bug we can fix. Please open a new issue.

All of a sudden, it started working today without me doing anything different.  If the issue comes back, I'll open a new issue.  thx

**Comment by alandtse** [comment] 2020-08-12 03:17
@chemelli74 It depends on when the error is detected. But the root cause looks to be the same where Amazon decides to expire the cookie. My hope is someone figures out a nice scan_interval setting where it stops doing it.
