### ISSUE TITLE
Routines containing a Skill action won't play correctly unless configured for specific device

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/alexa_media_player#572] opened 2020-02-28 10:02 UTC
**Describe the bug**

Alexa routines now have a Skill action which allows a skill to be opened as part of the routine. When these are triggered from the app they work whether they are configured to pay from a specific device or the device you speak to. When triggered using **media_player.play_media** they only work if configured for a specific device.

**To Reproduce**
1. Create a routine with an Alexa Says action and a Skill action (see first screenshot)
2. Set the **From** option to "The device you speak to"
3. Use **media_player.play_media** to play this routine on a device
4. The speech action will work (from the device you, but the skill won't open
5. Change **From** action to a specific device
6. Use **media_player.play_media** again
7. Both actions will work, although they will always be from the device configured in the skill.

**Expected behavior**

Routine should execute fully, including the Skill action, if the routine is configured to play from the device you speak to.

**Screenshots**

Not Working Routine
![Screenshot_20200228_091829_com amazon dee app](https://user-images.githubusercontent.com/2099542/75532083-267c2900-5a0c-11ea-90e9-a6ecd4d30e2c.jpg)

Working Routine
![Screenshot_20200228_091820_com amazon dee app](https://user-images.githubusercontent.com/2099542/75532156-2aa84680-5a0c-11ea-9cc3-6341b4499726.jpg)

**System details**
 - Home-assistant (version): 0.100.6
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.5.5
 - alexapy (version from `pip show alexapy` or HA startup): 1.5.0

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```text
2020-02-28 09:37:45 DEBUG (MainThread) [alexapy.alexaapi] Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Speak\", \"skillId\": \"amzn1.ask.1p.saysomething\", \"operationPayload\": {\"customerId\": \"************\", \"deviceType\": \"A3S5BH2HU6VAYF\", \"deviceSerialNumber\": \"G***************N\", \"textToSpeak\": \"hello\", \"locale\": \"en-GB\"}, \"name\": null}, {\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Operation.SkillConnections.Launch\", \"skillId\": \"amzn1.ask.skill.6b8619f2-e717-45ca-adf8-426da10a2357\", \"operationPayload\": {\"locale\": \"en-GB\", \"customerId\": \"*************\", \"targetDevice\": {\"deviceType\": \"ALEXA_CURRENT_DEVICE_TYPE\", \"deviceSerialNumber\": \"ALEXA_CURRENT_DSN\"}, \"connectionRequest\": {\"uri\": \"connection://AMAZON.Launch/amzn1.ask.skill.6b8619f2-e717-45ca-adf8-426da10a2357\", \"input\": {}}}, \"name\": null}]}}", "status": "ENABLED"}

```
**Additional context**

Judging from the debug log, the issue is that the **deviceType** is being passed as "ALEXA_CURRENT_DEVICE_TYPE" and the **deviceSerialNumber** as "ALEXA_CURRENT_DSN" rather than the correct device type and serial number of the device in the **media_player.play_media** call.

**Comment by gadgetchnnel** [comment] 2020-02-28 17:08
Some further information, which may help with fixing this:

The **operationPayload** for a music action looks like:

```
{"customerId":"************",
"deviceType":"ALEXA_CURRENT_DEVICE_TYPE",
"deviceSerialNumber":"ALEXA_CURRENT_DSN",
"musicProviderId":"AMAZON_MUSIC",
"searchPhrase":"*search phrase*",
"sanitizedSearchPhrase":"*search phrase*",
"locale":"en-GB"},
"name":null}]}}
```
while that for a skill action looks like:

```
{"locale":"en-GB",
"customerId":"************",
"targetDevice":{"deviceType":"ALEXA_CURRENT_DEVICE_TYPE",
"deviceSerialNumber":"ALEXA_CURRENT_DSN"},
"connectionRequest":{"uri":"connection://AMAZON.Launch/*skill id*",
"input":{}}},
"name":null}]}}
```

The difference appears to be that the device type and serial number are nested under **targetDevice** (which isn't the case for a music action) and is presumably preventing ALEXA_CURRENT_DEVICE_TYPE and ALEXA_CURRENT_DSN from being replaced with the correct values (it looks like alexapy may only replace them if they are directly under **operationPayload**).

**Comment by alandtse** [comment] 2020-02-29 05:42
Thanks you're right about the cause.

**Comment by alandtse** [comment] 2020-03-01 06:44
Ok should be fixed by https://gitlab.com/keatontaylor/alexapy/-/merge_requests/106 if you want to test manually making the change.

**Closed** 2020-03-01 07:26 UTC
Labels: bug
