### ISSUE TITLE
ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: Session is closed

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#679] opened 2020-05-03 12:01 UTC
**Describe the bug**
When reboot HA this error shows up in the log..

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
HA: 0.109.2
Add-On: 2.6.0

**Logs**
```
2020-05-03 13:58:32 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: Session is closed
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 293, in async_update_data
    ) = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 717, in get_devices
    "get", login, "/api/devices-v2/device", query=None
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 167, in _static_request
    ssl=login._ssl,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 310, in async_update_data
    await login_obj.login_with_cookie()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 200, in login_with_cookie
    await self.login(cookies=self._cookies)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 369, in login
    if cookies and await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 273, in test_loggedin
    self._prefix + self._url + "/api/bootstrap", cookies=cookies, ssl=self._ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```

**Additional context**

**Comment by alandtse** [comment] 2020-05-03 17:43
This happens when HA is being shutdown and closes the session. Dupe of #663

**Closed by alandtse** 2020-05-03 17:43 UTC
Labels: duplicate
