### ISSUE TITLE
HA 0.111.4 - An exception of type CancelledError occurred

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#797] opened 2020-06-21 21:23 UTC
**Describe the bug**
Error logged and plugin not working

**To Reproduce**
1. Restart HA
2. Check log

**Expected behavior**
No error and plugin working as usual

**System details**
 - Home-assistant (version): 0.111.4
 - Hassio (Yes/No):  No
 - alexa_media  (version from `const.py` or HA startup): v2.8.6
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_notifications((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2020-06-21 23:18:53 WARNING (MainThread) [alexapy.helpers] alexaapi.get_authentication((<alexapy.alexalogin.AlexaLogin object at 0x7f68e2676150>,), {}): Timeout error occured accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
```

**Comment by alandtse** [comment] 2020-06-21 23:13
Duplicate of #764

**Closed by alandtse** 2020-06-21 23:13 UTC
Labels: duplicate
