### ISSUE TITLE
Home Assistant SwitchDevice is deprecated now shows in log

### ISSUE THREAD

**Issue by mnaz** [custom-components/alexa_media_player#737] opened 2020-05-21 13:23 UTC
**Describe the bug**
An update to SwitchDevice now causes a warning in logs. See https://github.com/home-assistant/core/pull/34673
alexa_media_player should replace all instances of SwitchDevice with the new SwitchEntity definition. See https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/switch.py#L13 and https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/switch.py#L129

**To Reproduce**
1. Go to Developer -> Logs
2. Search for "SwitchDevice is deprecated"

**Expected behavior**
No warning messages...

**Screenshots**
shown in logs only as warning

**System details**
 - Home Assistant 0.110.0
 - Alexa Media Player: v2.8.0 from HACA 

**Logs**
Log Details (WARNING)
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:73
Integration: Switch (documentation, issues)
First occurred: 7:24:11 AM (4 occurrences)
Last logged: 7:24:11 AM

SwitchDevice is deprecated, modify AlexaMediaSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify DNDSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify ShuffleSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify RepeatSwitch to extend SwitchEntity

**Additional context**

**Comment by mnaz** [comment] 2020-05-21 13:38
These HA changes also caused warnings in log.

Source: components/media_player/__init__.py:333
MediaPlayerDevice is deprecated, modify AlexaClient to extend MediaPlayerEntity

components/alarm_control_panel/__init__.py:96
AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

**Comment by energywave** [comment] 2020-05-21 14:20
Duplicate of #699

**Comment by mnaz** [comment] 2020-05-21 14:34
Thank you.
I appreciate the help, I missed the prior item.

**Comment by naseemr** [comment] 2020-05-21 23:16
Is there a solution for this?

**Comment by alandtse** [comment] 2020-05-22 06:57
Please refer to #699

**Closed by alandtse** 2020-05-22 06:57 UTC
Labels: duplicate
