### ISSUE TITLE
Reauthentication required weekly

### ISSUE THREAD

**Issue by audioflyer** [custom-components/alexa_media_player#1005] opened 2020-11-14 13:49 UTC
Amazon requires reauthentication on a regular basis (maybe weekly?), even after using 2FA. This means that the integration stops working all the time. Is this a known issue, and is there a way to fix this?

**ADMIN EDIT: Please fill out this [survey](https://forms.gle/uuYwpDRmKwnQpdH2A) so we can figure out what's going on.**

**Comment by Stewie3112** [comment] 2020-11-14 22:02
Same here, trying to find a solution. Not a big problem for me, but I installed HA also at a friend's house and he's not able to reauth every time, so I always have to do it manually for him

**Comment by alandtse** [comment] 2020-11-15 20:09
The use of 2FA is required to get into Amazon. After that, whether Amazon asks you to reauth is controlled by Amazon. You're welcome to play with the code or settings to see if that reduces the frequency of reauths but I'm not aware of any free analytics libraries I could use to get a statistical understanding. Everything else will be anecdotes.

With the US domain I reauth every 2-3 months with default settings. I only have a couple of announce scripts (but again the exact count of API calls is unknown because we don't have analytics for that.

**Comment by audioflyer** [comment] 2020-11-15 21:16
So do you think the frequency of reauthentication might be related to the number of calls? I have a few TTS calls per day.

**Comment by alandtse** [comment] 2020-11-15 23:19
I have no idea. Again, I am not Amazon.

**Comment by Stewie3112** [comment] 2020-11-15 23:21
I'm using the IT domain and the requests are really a few. I only use it to play a playlist in Amazon music  with an automation triggered at most once a day

**Comment by Stewie3112** [comment] 2020-11-15 23:26
Stupid question: most of times it's not a real reauth, as I don't have to fill user/pwd as they're already saved and I haven't got to fill any captcha. Do you think would be possible to expose a service or to automatically retry to authenticate when logged out?

**Comment by alandtse** [comment] 2020-11-15 23:57
Again, you can edit the code if you want that. I'm trying not to get users banned.

**Comment by MRobi1** [comment] 2020-11-18 22:20
You're lucky it's weekly, I usually have to re-authorize twice a week lately. And it's been quite a process. 
After inputting the correct username/password, I enter the captcha, receive the OTP via text and click submit and it brings me back to the first page asking for username/password again. I go through the process twice more, receive a "too many login attempts" warning, reboot HA and do it a 4th timeand it will work. If I reboot before the "too many login attempts" warning it won't work.

Since earlier today, I get the required re-authorization. I click on the integration and can't even get to the options for captcha, I simply get a "authorization failed" and it's as-if the integration is gone from HA completely.

**Comment by milwright** [comment] 2020-11-20 18:05
I have had to re-authenticate a few times but its always worked great afterwards.
Three days ago, i had to re-authenticate again, only this time, hitting submit in hass after approving the login notification does nothing as if the link is broken. Restarting, removing and reinstalling the integration does nothing, ive tried installing older versions but nothing works. Im Hoping for a fix

**Comment by KibosJ** [comment] 2020-11-22 08:08
I previously just had to re-enter my 2FA code and it starts working again, but it's now locking me out of my account and I have to change my Amazon password every few weeks.

I really don't want to remove this as quite a few of my automations rely on it ☹️

**Comment by dweston** [comment] 2020-11-22 08:54
I'm using the alexa.amazon.com.au site and re-authorisation is being required every couple of weeks. But when I attempt to use the UI within the add-on itself to complete the process I keep being advised the password is invalid. That is simply not the case as I can open an adjacent browser window and login directly into the site no issues.

On my most recent attempt to re-authorise it appears I attempted to submit once too often and was then warned I'd been locked out for a period. However now I can't seem to work out how to re-open the authorisation screen - short of deleting the add-on and reinstalling and configuring it.

**Comment by alandtse** [comment] 2020-11-22 09:14
It's safe to delete and readd. And if you can log in to the site directly, just use the cookie import.

Also, [survey](https://forms.gle/uuYwpDRmKwnQpdH2A) so I can get data on reauth requests. Please fill out.

**Comment by dweston** [comment] 2020-11-22 09:27
Thx Alan,

I’m filling the form out now.

I used the cookie import method the last time this happened and finally got things to work again though it was quite involved.

Please note I normally only use the API for TTS purposes maybe 5 times daily associated with Automations. However on occasion I’ve found that I’ve got a heck of a lot of utility out of using the developer tools to make AMAZON_MUSIC play calls. Its often easier to type in what I want played as opposed to trying to work out how to speak the title and performer in a manner Alexa understands. When I’m in that mode I find I often make quite a number of calls - maybe up to 15-20 in a session.

Is it conceivable that a session at this higher rate of API call could trigger Amazon to issue a re-authorisation requirement?

Ciao
Dion Weston
Greenwich, NSW Australia

**Comment by alandtse** [comment] 2020-11-22 15:19
@dweston I'm just guessing what Amazon is looking for so that's why I'm trying to get the data now. The data may show a relationship with the number of calls, or it may be something completely random. I also just added a question about the number of Alexa devices as maybe it's multiplied by that too.

**Comment by Mincka** [comment] 2020-11-25 05:45
Survey filled (4 calls per day to start and stop playing radio; 2FA reauth every week approximately).

In my case, after reauthenticating for 3 consecutive weeks, the 2FA request stops working. The component is stuck in a state where it believes to be properly configured.

I must use a browser to either enter a captcha or even worse, being forced to reset my password by Amazon (happened once)...

**Comment by yoleska-dev** [comment] 2020-12-07 09:38
Following as I have this problem too and it's making me look for other solutions, but I really like this implementation.  Let me know if you need further information.  My AWS Account does have 2FA enabled on it, but I don't have to do that every time it asks, I just have to login with username and password.  It would be nice if I could configure this in HA Secrets and have it just pass that to the web form that the dialog is asking me to go to.  https://localhost:3456.  Seems like it would be a simple code change to pass the credentials and be done with the constant disconnects.

**Comment by sudo-robot-destroy** [comment] 2020-12-08 19:55
I've noticed that almost every time I need to reathenticate, if I go into the HACS menu through the sidebar and go to integrations I see that HACS and Alexa Media has an update available. 

I say almost every time because I can remember at least one time it wasn't the case. It happens so consistently I just assumed it was a known thing that when an update is pushed you need to reauthenticate, but a facebook post lead me here and I see now the cause isn't known. 

There is a chance that it's just a quencidence and the only time I see that HACS and Alexa Media have updates available is when a reauthenticatation is required, I never  had a reason to check other times. I'll try to keep a closer eye on it to see if that's happening.

**Comment by martin3000** [comment] 2020-12-09 15:23
Every time I have to reauthenticate, my amazon password is expired (on the amazon website) and I'm required to make a new password. This is like somebody (or some program) tries to login a few times with the wrong password.

**Comment by Krocko** [comment] 2020-12-12 06:59
@martin3000 i have the same problem.

**Comment by alandtse** [comment] 2020-12-12 08:55
> Maybe I'm missing something, but this change "Add automatic relogin ([23c44c3](https://github.com/custom-components/alexa_media_player/commit/23c44c3b2b6f60b936a368a1fde2c9c6e4511d59))" I thought would resolve this, but maybe I just don't have my side configured correctly.

The only requirement for automatic relogin is that you haven't been disconnected within 1 minute of another login. However, it will fail if you are asked for a captcha or a OTP code since that needs user input. In my testing, once you have the built-in 2FA authenticator setup, it should be able to bypass the captcha and generate the OTP code fairly regularly.

**Comment by audioflyer** [comment] 2020-12-12 13:19
It hasn’t asked me to reauthenticate since the update. I think for me, that
fixed it. Thanks!

**Comment by sudo-robot-destroy** [comment] 2020-12-17 16:51
> There is a chance that it's just a quencidence and the only time I see that HACS and Alexa Media have updates available is when a reauthenticatation is required, I never had a reason to check other times. I'll try to keep a closer eye on it to see if that's happening.

It must have been a coincidence, HACS and Alexa Media Player have updated and I've not been asked to reauthenticate...maybe it's fixed now?

**Comment by Petro31** [comment] 2020-12-30 16:25
@alandtse I'm 100% ok with revalidation every few weeks, but do we need to have captcha & 2 factor?  It makes the process 100x harder.  Why is the captcha required if we have 2 factor?

**Comment by alandtse** [comment] 2020-12-30 17:56
You need to complain to Amazon. The component is just passing on the request from Amazon. If you set up the internal 2FA generator you won't have to worry about timing.

**Closed** 2020-12-31 02:43 UTC

**Comment by JackTalisker** [comment] 2020-12-31 08:33
How to force logout and relogin to generate oauth token?
thank you

**Comment by Silvenga** [comment] 2020-12-31 16:25
@JackTalisker call the `alexa_media.force_logout` service in HA.

**Comment by trapper629** [comment] 2021-01-19 10:53
After using this for many months I will now be uninstalling at.  Frequent re-authentications (often which fail) have made this too unstable for me.  Yes, it may be Amazon's fault but I can't have automations failing when I'm away for several weeks.

**Comment by StuckInLoop** [comment] 2021-09-16 21:28
does this problem still exists?   is there a new way to tackle this?

**Comment by martin3000** [comment] 2021-09-16 21:32
for me it works now, the problem is gone. maybe it was solved with the 2FA

**Comment by trapper629** [comment] 2021-09-16 22:33
Good for me now, thanks.

**Comment by pierpippo** [comment] 2021-11-15 08:18
I heve the same issue. "or 3 times a week I have to reautenticate. How can i solve this issue?
THX.

**Comment by martin3000** [comment] 2021-11-15 09:42
See #1398

**Comment by pierpippo** [comment] 2021-11-15 10:03
thx :)
