### ISSUE TITLE
Alexa TTS issue

### ISSUE THREAD

**Issue by Anon0ne** [custom-components/alexa_media_player#540] opened 2020-01-23 22:37 UTC
**Describe the bug**
Today, while setting up a new Alexa TTS (I had other ones working good) my Alexa TTS scripts started to say something odd before my message. It sounds like it's saying "Amazon Force Unit Selection test slash" my message "slash Amazon force unit selection".

I am not sure if the string is messed up, or if the data requirements have changed?

**To Reproduce**
1. Setup any automation or script using notify.alexa_media and setup as stated in the how-to.

**Expected behavior**
Normal TTS?

**Screenshots**
na

**Comment by vMeph** [comment] 2020-01-23 23:08
i can confirm same issue

**Comment by Marlor** [comment] 2020-01-23 23:09
I have the same Problem, now she is saying:
amazon force unit selection "Message" <amazon force unit selection>

alexa_media_player v2.5.3
Home Assistant 0.104.3
Setup via Integrationen on amazon.de

**Comment by 4meuwil** [comment] 2020-01-23 23:15
downgraded to 2.5.2 when last working....still has same issue

**Comment by 4meuwil** [comment] 2020-01-23 23:20
downgrade to 2.4.1 does not work either....seems this could be an issue on amazon's side of things...which makes me worry

**Comment by 4meuwil** [comment] 2020-01-23 23:29
announce function works correctly, just tts giving this error.

**Comment by rhysby** [comment] 2020-01-23 23:41
It also does this if you do a "Simon says..." command, so I think they might have broken something.

**Comment by rhysby** [comment] 2020-01-24 00:55
This is the response I have received from Amazon regarding the issue.

"I'd like to inform you that, there is an ongoing issue from our end and that's the reason why you're experiencing this issue.

There is no issue as far as your device and account is concerned.

We've reported this to our technical team, and they're working on taking care of it.

Please try again over the next few days. Errors like this are usually corrected shortly after they're reported.

Thanks for your patience while we fix this problem."

**Comment by alandtse** [comment] 2020-01-24 04:07
I just tested this and am not experiencing this. Can someone with the issue confirm if it's resolved?

**Comment by GrandadEvans** [comment] 2020-01-24 06:35
I can confirm that I am no longer receiving the weird TTS message on the end of the original message. I have no idea what time it was fixed (by Amazon I assume), but it appears to be over :-)

**Comment by alandtse** [comment] 2020-01-24 07:17
Great I'll close this then.

**Closed by alandtse** 2020-01-24 07:17 UTC
Labels: amazonissue
