### ISSUE TITLE
Captcha/ OTP not working

### ISSUE THREAD

**Issue by milkog** [custom-components/alexa_media_player#888] opened 2020-08-27 10:31 UTC
Captcha/ OTP not working

**To Reproduce**
1. Go to Notifications
2. Click on"configurator - Click button to configure Alexa Media Player - Captcha ***@***.***"
3. Enter captcha
4. Notification reappears

**Expected behavior**
I have OTP enabled, I'd expect OTP dialogue

**Screenshots**
<img width="1277" alt="Screenshot_27_08_2020__11_26" src="https://user-images.githubusercontent.com/7501020/91431516-6192d400-e858-11ea-88d8-8a1496b19f18.png">
<img width="1279" alt="Menubar_and_HACS_-_Home_Assistant" src="https://user-images.githubusercontent.com/7501020/91431520-62c40100-e858-11ea-8771-9983a3cdd454.png">

**System details**
 - Home-assistant (version): 0.114.4
- HACS: 1.5.2
 - Hassio No
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by broyuken** [comment] 2020-08-27 11:09
Your password is incorrect, it says so right there in the captcha image

**Comment by kmycek** [comment] 2020-08-27 15:16
Happened to me too. I tried captcha like 5-6 times, and now I am locked out - (even though I can login to my Amazon account from any browser, and finish the auth with 2FA.

**Comment by magaman** [comment] 2020-08-27 23:28
Happening as well, removed the integration, went through the process, authorized on browser and through amazon app, prompt for captcha submits and then goes into the endless cycle of asking again.

**Comment by guilhermelirio** [comment] 2020-08-28 00:53
Same here! =/

**Comment by alandtse** [comment] 2020-08-28 03:08
As mentioned by @broyuken the specific error you found is your password is wrong. To the extent others have chimed in that Amazon is saying it is sending information to you, that's a dupe of #807.

**Closed by alandtse** 2020-08-28 03:08 UTC

**Comment by exKAjFASH** [comment] 2020-08-28 12:49
+1 Solved using @guilhermelirio  steps

**Comment by miaosun** [comment] 2020-09-13 13:15
Have the exact same problem, have 2FA activated (and also added a back-up phone number in 2SV settings). 
Tried to uninstall and reinstall Alexa Media Player several times, was never able to get through captcha verification page, always shows the same error message "Your password is incorrect", I can assure that the password is correct and also tried changing the password, none of above methods worked. Please help.

![Image of Yaktocat](https://i.imgur.com/1mFD7Py.jpg)
