### ISSUE TITLE
TTS - Notify service not working

### ISSUE THREAD

**Issue by Gnaj** [custom-components/alexa_media_player#1459] opened 2021-12-09 06:16 UTC
TTS - Notify service not working

Services and everything was working fine yesterday i tried updating, reinstalling, deleting, new HASS instance and still not working, i'm getting 

2021-12-08 16:27:19 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API:

also this

2021-12-08 15:25:05 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2021-12-08 15:25:05 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=20 from 2021-12-08 11:31:36.867867)

and this

Alexa Test: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
12:19:46 AM – (ERROR) Automation (custom integration) - message first occurred at 12:19:46 AM and shows up 2 times

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

**Comment by alandtse** [comment] 2021-12-09 16:25
Please fill out the template.

**Comment by alandtse** [comment] 2021-12-11 21:51
Dupe of #1460

**Closed by alandtse** 2021-12-11 21:51 UTC
