### ISSUE TITLE
alexaapi._static_request:An error occured accessing AlexaAPI

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#704] opened 2020-05-11 08:54 UTC
**Describe the bug**
Installed: v2.7.1 and did the reboot. Everything ok. Did a reboot again and now I see those errors in the log until HA is restarted in Docker

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

**Logs**
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_bluetooth:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_device_preferences:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_dnd_state:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_notifications:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexalogin.login:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_devices:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_bluetooth:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_device_preferences:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_dnd_state:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_notifications:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexalogin.login:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_devices:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_bluetooth:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi.get_device_preferences:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'json'",)
2020-05-11 10:51:25 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
tail: /usr/share/hassio/homeassistant/home-assistant.log: file truncated

**Additional context**

**Comment by poudenes** [comment] 2020-05-11 12:04
I revert back to 2.7.0 and errors are gone.

**Comment by alandtse** [comment] 2020-05-11 19:57
Dupe of #705

**Closed by alandtse** 2020-05-11 19:57 UTC
Labels: duplicate
