### ISSUE TITLE
Alexa Media Player fails to reauthenticate due to Amazon outage

### ISSUE THREAD

**Issue by Cippo2019** [custom-components/alexa_media_player#1497] opened 2022-01-21 07:42 UTC
Hello...

Alexa Media Player 3.10.15
HA 2021.12.10
OS 7.1

After request to authenticate i put my opt and i get this error on log and alexa doesn't work

2022-01-21 08:40:42 WARNING (MainThread) [alexapy.helpers] alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f38dca2b850>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)

Usually after this procedure in the past it worked wothout problem

any idea ? 

opt is correct , I tested it on amazon web

thanks a lot
Tiziano

**Comment by Krocko** [comment] 2022-01-21 07:45
I have the same problem since this morning.

**Comment by rlewis187** [comment] 2022-01-21 07:45
I also have the same problem

**Comment by Cippo2019** [comment] 2022-01-21 07:46
......nice to know :-)

**Comment by richard-scott** [comment] 2022-01-21 07:47
Same here today. I’m in Amazon.co.uk, anyone else in .co.uk, or are you Amazon.com?

**Comment by zibous** [comment] 2022-01-21 07:47
I also have the same problem..

**Comment by rlewis187** [comment] 2022-01-21 07:48
I'm .co.uk

**Comment by Cippo2019** [comment] 2022-01-21 07:48
amazon.it for me

**Comment by 1onord** [comment] 2022-01-21 07:48
+1 the same over here amazon.de

**Comment by GabbaGand** [comment] 2022-01-21 07:49
same here for amazon.de

**Comment by maury77** [comment] 2022-01-21 07:50
same for amazon.it

**Comment by blaiser72** [comment] 2022-01-21 07:53
same for amazon.it

**Comment by rlewis187** [comment] 2022-01-21 07:53
My error log:
```
Logger: alexapy.helpers
Source: /usr/local/lib/python3.9/site-packages/alexapy/helpers.py:185
First occurred: 07:34:24 (18 occurrences)
Last logged: 07:46:28

alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0x7f74d63760>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f74d63760>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0x7f74d63760>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0x7f74d63760>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7f74d63760>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
```

**Comment by alexandertonino** [comment] 2022-01-21 07:56
Same issue here on amazon.de, I reinstalled AMP and reconfigured. It told me everything is fine. Got the "Reconfigure"-Message like 1 second later

**Comment by 77Force** [comment] 2022-01-21 07:57
+1 amazon.de

**Comment by oalbaf** [comment] 2022-01-21 07:58
Same issue here on amazon.es. Also my ECHO's have stopped working. Problems at Amazon's house?

**Comment by lorrainem77** [comment] 2022-01-21 07:59
6000 reports of alexa down since 7am (GMT) https://downdetector.co.uk/status/amazon-alexa/

**Comment by RandumbPrints** [comment] 2022-01-21 08:02
> 6000 reports of alexa down since 7am (GMT) https://downdetector.co.uk/status/amazon-alexa/
Was just coming to post exactly this.

**Comment by oalbaf** [comment] 2022-01-21 08:04
I have managed to authenticate my devices. ECHOs still don't respond to voice commands.

**Comment by oalbaf** [comment] 2022-01-21 08:07
ECHO devices appear added to HA, but not available. It remains for Amazon to solve your problem.

![image](https://user-images.githubusercontent.com/31956250/150489953-437d0664-f248-42a1-9275-0de03021369a.png)

![image](https://user-images.githubusercontent.com/31956250/150489988-32261505-032a-4df4-b2fe-539f9823eead.png)

**Comment by Jonnas90** [comment] 2022-01-21 08:10
For me it says reauthentication is successful but still remains in red on the integrations page and media player isn't available.

**Comment by oalbaf** [comment] 2022-01-21 08:15
@Jonnas90 I have removed the integration, restarted HA and installed again. It works, but the ECHOs remain off.

**Comment by KHOne23** [comment] 2022-01-21 08:21
same here

**Comment by samc449** [comment] 2022-01-21 08:25
Same here as of this morning.

**Comment by ashoktvm** [comment] 2022-01-21 08:25
> I have managed to authenticate my devices. ECHOs still don't respond to voice commands.



> @Jonnas90 I have removed the integration, restarted HA and installed again. It works, but the ECHOs remain off.

I tried the same but the extra card to reauthenticate still shows in Integrations

**Comment by Danoro73** [comment] 2022-01-21 08:27
Same here, Amazon.de

**Comment by jules51x** [comment] 2022-01-21 08:27
Same issue as others (amazon.co.uk), everything appears to work though, nothing unavailable I just can't clear the red reconfigure box on the integrations page.

**Comment by samc449** [comment] 2022-01-21 08:30
My echo devices are having trouble too. There doesn't seem to be any issues logged on the [API status](https://status.aws.amazon.com) page though. Not yet anyway.

**Comment by CelestinoMarini** [comment] 2022-01-21 08:33
same for me in Italy

**Comment by oalbaf** [comment] 2022-01-21 08:38
> ECHO devices appear added to HA, but not available. It remains for Amazon to solve your problem.
> 
> ![image](https://user-images.githubusercontent.com/31956250/150489953-437d0664-f248-42a1-9275-0de03021369a.png)
> 
> ![image](https://user-images.githubusercontent.com/31956250/150489988-32261505-032a-4df4-b2fe-539f9823eead.png)

One of my devices appears available to me, but all of them are still not responding to commands.

Now...

![image](https://user-images.githubusercontent.com/31956250/150494222-b071d4f3-37ce-4cd5-bee8-3de1160fb2ec.png)

**Comment by user514** [comment] 2022-01-21 08:45
> amazon.es

  Same here. amazon.es. Echo don't even answer questions...

**Comment by sk8er000** [comment] 2022-01-21 08:48
Same here using amazon.it 
I tried to set up a timer directly to my echo, the timer was set (into the alexa app) but no answer from the echo

**Comment by pjtxxx** [comment] 2022-01-21 08:55
Same issue with ha integration but unlike others my android app and echo's are working (amazon.co.uk)
At least  i now know it's not my system.

**Comment by alandtse** [comment] 2022-01-21 09:04
All, the me too posts don't help. +1 if you see someone with the same response. if the problem is there's too many to read... then well..... and please don't respond about this on multiple issues. 

If you have something new to add, that will help.

As of this writing, US still looks up so it may be localized to Europe for now.

**Comment by oalbaf** [comment] 2022-01-21 09:07
Now in amazon.es. status:

HA + integration: Works well, all OK!
ALEXA: Only one device on-line and works well

![image](https://user-images.githubusercontent.com/31956250/150498857-92ebf965-01ee-4598-bef2-c17c4607c615.png)

**Comment by thorrrr** [comment] 2022-01-21 09:07
> All, the me too posts don't help. +1 if you see someone with the same response. if the problem is there's too many to read... then well..... and please don't respond about this on multiple issues.
> 
> If you have something new to add, that will help.
> 
> As of this writing, US still looks up so it may be localized to Europe for now.

Hi Alan 
Sorry for same here comment i have added a log to see if it helps

**Comment by ashoktvm** [comment] 2022-01-21 09:11
> All, the me too posts don't help. +1 if you see someone with the same response. if the problem is there's too many to read... then well..... and please don't respond about this on multiple issues.
> 
> If you have something new to add, that will help.
> 
> As of this writing, US still looks up so it may be localized to Europe for now.

Happening in amazon.in integration as well

**Comment by alandtse** [comment] 2022-01-21 09:12
> Sorry for same here comment i have added a log to see if it helps

Yes thanks. I looked. Logs indicate Amazon servers are closing the connection. Might be a localized outage or it could be an API change. Some people are reporting it's coming back so it may just be a matter of waiting. If Amazon changed something, it may be a longer term outage as we figure out what changed.

**Comment by alexandertonino** [comment] 2022-01-21 09:14
Servers seem to be online again. Alexa Media Player works again

**Comment by oalbaf** [comment] 2022-01-21 09:18
My ECHO's are working normally again. The integration in HA has been successfully authenticated. However, the status does not correspond to what I am playing.

![image](https://user-images.githubusercontent.com/31956250/150500546-5e54565f-9407-4492-b75d-91742a98940f.png)

![image](https://user-images.githubusercontent.com/31956250/150500434-0693b1c2-4f36-440f-be3b-374eb894923c.png)

**Comment by oalbaf** [comment] 2022-01-21 09:21
Amazon.es work well now!

![image](https://user-images.githubusercontent.com/31956250/150501090-5b237d0d-cc02-4fc7-a029-fa420c770355.png)

**Comment by orangelizard** [comment] 2022-01-21 09:45
Still out in the UK I just get "Invalid Built-In 2FA key" on re-installation :(

**Comment by ashoktvm** [comment] 2022-01-21 09:56
Working now in India as well

**Comment by Kaibob2** [comment] 2022-01-21 10:13
Amazon.de is also working again after 2.5 outage.
I suppose this issue can be closed as it doesn't seem to be a long term api problem.

**Comment by isibizi** [comment] 2022-01-21 10:34
everything works fine, problem solved

**Comment by sk8er000** [comment] 2022-01-21 10:54
Working again (amazon.it)

**Comment by orangelizard** [comment] 2022-01-21 11:53
Had to restore the addon from last nights backup and reauthenticate. Now working UK. :)

**Closed** 2022-01-21 22:36 UTC
Labels: amazonissue
