### ISSUE TITLE
RuntimeError: Session is closed

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#663] opened 2020-04-27 12:00 UTC
**Describe the bug**
Log exception at every HA restart

**To Reproduce**
1. tail -f homeassitant.log
2. Restart HA
3. Check log

**Expected behavior**
Handle "Session closed" error during restart/shutdown

**System details**
 - Home-assistant (version): 0.109.b3
 - Hassio (Yes/No):  No
 - alexa_media  (version from `const.py` or HA startup): 2.5.15
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**

```
2020-04-27 13:53:41 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: Session is closed
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 277, in async_update_data
    ) = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 680, in get_devices
    "get", login, "/api/devices-v2/device", query=None
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 167, in _static_request
    ssl=login._ssl,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 294, in async_update_data
    await login_obj.login_with_cookie()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 168, in login_with_cookie
    await self.login(cookies=self._cookies)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 333, in login
    if cookies and await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 238, in test_loggedin
    self._prefix + self._url + "/api/bootstrap", cookies=cookies, ssl=self._ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

```

**Additional context**

**Comment by alandtse** [comment] 2020-04-27 22:29
This is low priority.

**Comment by genem2** [comment] 2020-05-12 19:57
I spent the morning trying to figure out why I could no longer restart HA from the UI. Each time I did, the Docker contain froze and I had to restart it at the Docker level.  I have a bunch of info that I'll attach here, but with that now complete, I'm now w/o the error, and I feel it might be related to this issue #663.

If you have the cycles, can you give me a quick review and any insiite you might have?  Thank you.

[MySubmission.txt](https://github.com/custom-components/alexa_media_player/files/4618128/MySubmission.txt)

**Comment by alandtse** [comment] 2020-05-12 20:35
@genem2 Thanks for the detail submission, I'm looking at the error already. 2.7.0 shouldn't have the error as it was caused by fixing a silent bug with 2.7.1. However, because we are now exposing the error the retry logic gets stuck in a loop.

**Comment by alandtse** [comment] 2020-05-12 21:23
So it turns out this was more than cosmetic once I fixed the fact it wasn't appropriately triggering the retry logic. So just wanted to acknowledge @chemelli74 was right. I think this should be gone now in 2.7.5. I'll close it but if anyone sees it again, let me know.

**Closed by alandtse** 2020-05-12 21:23 UTC
Labels: bug, help wanted

**Comment by chemelli74** [comment] 2020-05-12 23:38
2.7.5 seems perfect, neither stuck on reboot not errors logged .
Nice job!

Simone
