### ISSUE TITLE
500 server error when attempting to load integration 

### ISSUE THREAD

**Issue by sturtester** [custom-components/alexa_media_player#1963] opened 2023-06-12 17:58 UTC
**Describe the bug**

I was attempting to add the Alexa integration in the latest home assistant version but I keep receiving a 500 server got itself in trouble error. I have tried to google and search for the specific issue but I am not able to solve this on my own.

**To Reproduce**

1. Go to HACS 
3. Install Alexa Media Integration
4. Go to integrations
5. Add integration "Alexa Media"
6. Enter amazon server and login information
7. Follow link to connect Alexa to Home Assistant and receive error.

**Expected behavior**

I should be able to add the integration to my Home Assistant server so I can send TTS as well as change the media playing ect.

**Error log in HA**

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:886
Integration: Alexa Media Player (documentation, issues)
First occurred: 12:38:40 PM (2 occurrences)
Last logged: 12:38:43 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 886, in wrapped
    return await cls.handler(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
    resp = await getattr(self.session, method)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1517, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 347, in build_request
    headers = self._merge_headers(headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 414, in _merge_headers
    merged_headers.update(headers)
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 200, in update
    headers = Headers(headers)
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 71, in __init__
    self._list = [
                 ^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 75, in <listcomp>
    normalize_header_value(v, encoding),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 0: ordinal not in range(128)

**System details**

- Home-assistant (version): 2023.6.1
- alexa_media (version from `const.py` or HA startup): v4.6.4
- alexapy (version from `pip show alexapy` or HA startup): Can't locate
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : No

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

I put the error logs above

**Additional context**

So I had this previously working but several entities were unavailable for some reason so I deleted the integration and readded it as well as deleted the files from HACS and installed it and started getting the 500 error when I attempt to login with the integration.

**Comment by alandtse** [comment] 2023-06-13 21:45
Dupe of #1788

**Closed by alandtse** 2023-06-13 21:45 UTC
Labels: duplicate
